SELECT USER
FROM DUAL;


-- 프로시저 ======================================================================

-- ○ 1. 회원가입 생성 프로시저
CREATE OR REPLACE PROCEDURE PRC_USER_SIGNUP
( P_USER_LOGIN_ID IN VARCHAR2
, P_USER_PASSWORD IN VARCHAR2
, P_USER_PASSWORD_CHECK IN VARCHAR2
, P_USER_NAME IN VARCHAR2
, P_USER_SSN IN CHAR
, P_USER_EMAIL IN VARCHAR2
, P_USER_PHONE IN CHAR
, P_USER_ZIPCODE IN VARCHAR2
, P_USER_ADDRESS IN VARCHAR2
, P_USER_ADDRESS_DETAIL IN VARCHAR2
)
IS
    V_HAS_ID NUMBER(1);
    V_HAS_SSN NUMBER(1);
    V_BIRTH DATE;
    V_AGE NUMBER(3);
    
    
    ERR_DUPLICATE_ID EXCEPTION;
    ERR_DUPLICATE_SSN EXCEPTION;
    ERR_INVALID_SSN EXCEPTION;
    ERR_INVALID_FORMAT_LENGTH EXCEPTION;
    ERR_UNDERAGE EXCEPTION;
    ERR_WRONG_PWD EXCEPTION;
    ERR_INVALID_EMAIL EXCEPTION;
    ERR_NULL_VALUE EXCEPTION;

BEGIN
-- NULL 검사
    IF (P_USER_LOGIN_ID IS NULL OR P_USER_PASSWORD IS NULL 
        OR P_USER_PASSWORD IS NULL OR P_USER_NAME IS NULL OR P_USER_SSN IS NULL
        OR P_USER_SSN IS NULL OR P_USER_EMAIL IS NULL OR P_USER_PHONE IS NULL
        OR P_USER_ZIPCODE IS NULL OR P_USER_ADDRESS IS NULL OR P_USER_ADDRESS_DETAIL IS NULL)   THEN
            RAISE ERR_NULL_VALUE;
    END IF;

-- 아이디 중복 검사
    SELECT COUNT(*) INTO V_HAS_ID
    FROM USER_ACCOUNT
    WHERE USER_LOGIN_ID = P_USER_LOGIN_ID;
    
    IF(V_HAS_ID != 0) THEN
        RAISE ERR_DUPLICATE_ID;
    END IF;
    
-- 아이디 조건 검사(4글자이상 12자이하)
    IF(LENGTH(P_USER_LOGIN_ID)<4 OR LENGTH(P_USER_LOGIN_ID)>12) THEN
        RAISE ERR_INVALID_FORMAT_LENGTH;
    END IF;

-- 비밀번호 조건 검사(8자이상 16자이하)
    IF(LENGTH(P_USER_PASSWORD)<8 OR LENGTH(P_USER_PASSWORD)>16) THEN
        RAISE ERR_INVALID_FORMAT_LENGTH;
    END IF;
    
-- 비밀번호 확인
    IF(P_USER_PASSWORD != P_USER_PASSWORD_CHECK) THEN
        RAISE ERR_WRONG_PWD;
    END IF;
    
-- 주민번호 유효성 검사
    IF NOT REGEXP_LIKE(P_USER_SSN, '^[0-9]{6}[1-4][0-9]{6}$') THEN
        RAISE ERR_INVALID_SSN;
    END IF;
    
-- 주민번호 중복 검사
    SELECT COUNT(*) INTO V_HAS_SSN
    FROM USER_PROFILE
    WHERE USER_SSN = P_USER_SSN;
    
    IF(V_HAS_SSN != 0) THEN
        RAISE ERR_DUPLICATE_SSN;
    END IF;

-- 주민번호 미성년자 제외 검사
    V_BIRTH := TO_DATE(
        CASE
            WHEN SUBSTR(P_USER_SSN,7,1) IN ('3','4') THEN '20'
            ELSE '19'
        END || SUBSTR(P_USER_SSN,1,6), 'YYYYMMDD'
    );

    V_AGE := TRUNC(MONTHS_BETWEEN(SYSDATE, V_BIRTH)/12);
    
    IF(V_AGE<19) THEN
        RAISE ERR_UNDERAGE;
    END IF;

-- 이메일 유효성 검사
    -- ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$
     IF NOT REGEXP_LIKE(P_USER_EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
        RAISE ERR_INVALID_EMAIL;
    END IF;

-- 1. USERS INSERT
    INSERT INTO USERS VALUES(USERS_SEQ.NEXTVAL);
    
-- 2. USER_ACCOUNT INSERT
    INSERT INTO USER_ACCOUNT
    VALUES(USERS_SEQ.CURRVAL, P_USER_LOGIN_ID, P_USER_PASSWORD);

-- 3. USER_PROFILE INSERT
    INSERT INTO USER_PROFILE
    VALUES(USERS_SEQ.CURRVAL, P_USER_NAME, P_USER_SSN, P_USER_EMAIL, P_USER_PHONE
    , P_USER_ZIPCODE, P_USER_ADDRESS, P_USER_ADDRESS_DETAIL);
    

      
-- 4. ACCOUNT_EVENT_HISTORY INSERT
    INSERT INTO ACCOUNT_EVENT_HISTORY
    VALUES(ACCOUNT_EVENT_HISTORY_SEQ.NEXTVAL, USERS_SEQ.CURRVAL, 1, SYSDATE);

-- 예외 처리
    EXCEPTION 
        WHEN ERR_DUPLICATE_ID THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20001, '이미 존재하는 아이디입니다.');
        WHEN ERR_DUPLICATE_SSN THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20002, '이미 존재하는 주민등록번호입니다.');
        WHEN ERR_INVALID_SSN THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20003, '유효하지 않은 주민등록번호입니다.');   
        WHEN ERR_INVALID_FORMAT_LENGTH THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20005, '입력 범위가 맞지 않습니다.');
        WHEN ERR_UNDERAGE THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20006, '미성년자입니다.'); 
        WHEN ERR_WRONG_PWD THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20007, '비밀번호가 일치하지 않습니다.'); 
        WHEN ERR_INVALID_EMAIL THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20008, '올바른 이메일 형식이 아닙니다.');
        WHEN ERR_NULL_VALUE THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20014, '필수 입력 항목이 누락되었습니다.');
END;
/

-- ○ 2. 회원탈퇴 프로시저
CREATE OR REPLACE PROCEDURE PRC_USER_DELETE
( P_USER_ID IN USERS.USER_ID%TYPE
)
IS
     -- 커서 정의 (경매테이블)
     CURSOR CUR_USER_AUCTION IS
            SELECT AR.AUCTION_ID
            FROM AUCTION_REGISTRATION AR
                JOIN PRODUCT P 
            ON AR.PRODUCT_ID = P.PRODUCT_ID
            WHERE P.USER_ID = P_USER_ID;
            
    CURSOR CUR_USER_BID IS
        SELECT AR.AUCTION_ID
        FROM AUCTION_REGISTRATION AR
            JOIN AUCTION_BID_PARTICIPATION ABP
            ON ABP.AUCTION_ID = AR.AUCTION_ID
        WHERE ABP.USER_ID = P_USER_ID;

    V_AUCTION_ID AUCTION_REGISTRATION.AUCTION_ID%TYPE;
    V_BID_RESULT_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE;
    V_HAS_BID NUMBER;
    V_HAS_BID_2 NUMBER;
    V_PENALTY_SCORE    NUMBER;
    V_PENALTY_ID   PENALTY_HISTORY.PENALTY_ID%TYPE;
    V_NAME USER_PROFILE.USER_NAME%TYPE;
    V_SSN USER_PROFILE.USER_SSN%TYPE; 
    V_PHONE USER_PROFILE.USER_PHONE%TYPE; 
    V_EMAIL USER_PROFILE.USER_EMAIL%TYPE;
    V_ZIPCODE USER_PROFILE.USER_ZIPCODE%TYPE; 
    V_ADDRESS USER_PROFILE.USER_ADDRESS%TYPE;
    V_DETAIL USER_PROFILE.USER_ADDRESS_DETAIL%TYPE;
    
    ERR_HAS_ACTIVE_AUCTION EXCEPTION;
    ERR_HAS_ACTIVE_BID EXCEPTION;
    ERR_HAS_ACTIVE_WINNING EXCEPTION;
    ERR_HAS_MONEY EXCEPTION;
    ERR_HAS_PENALTY EXCEPTION;
    
BEGIN
    -- 진행 중인 경매 검사
    
        OPEN CUR_USER_AUCTION;
        LOOP
            FETCH CUR_USER_AUCTION INTO V_AUCTION_ID;
            EXIT WHEN CUR_USER_AUCTION%NOTFOUND;
            
            IF(FN_IS_AUCTION_FINISHED(V_AUCTION_ID) = 0) THEN
                CLOSE CUR_USER_AUCTION;
                RAISE ERR_HAS_ACTIVE_AUCTION;
            END IF;
        END LOOP;
        CLOSE CUR_USER_AUCTION;
        
    -- 진행 중인 입찰 검사
        -- 입찰 참여 테이블에서 USER_ID로 조회해서 나온 경매코드들로
        -- 그 경매코드가 진행중인지 검사
        
        OPEN CUR_USER_BID;
        LOOP
            FETCH CUR_USER_BID INTO V_AUCTION_ID;
            EXIT WHEN CUR_USER_BID%NOTFOUND;
            
            IF(FN_IS_AUCTION_FINISHED(V_AUCTION_ID) = 0) THEN
                CLOSE CUR_USER_BID;
                RAISE ERR_HAS_ACTIVE_BID;
            END IF;
        END LOOP;
         CLOSE CUR_USER_BID;

        -- 진행 중인 낙찰 검사
            SELECT COUNT(*) INTO V_HAS_BID
            FROM AUCTION_WINNING_RESULT AWR
            JOIN AUCTION_BID_PARTICIPATION ABP ON AWR.BID_ID = ABP.BID_ID
            WHERE ABP.USER_ID = P_USER_ID
            AND AWR.BID_RESULT_ID NOT IN (SELECT BID_RESULT_ID FROM BID_FAILURE_HISTORY) -- 실패 이력 없고
            AND AWR.BID_RESULT_ID NOT IN ( -- 거래 완료 이력도 없는 것 카운트
                SELECT BID_RESULT_ID FROM AUCTION_WINNING_PAYMENT AWP
                JOIN DELIVERY_COMPLETED DC ON AWP.PAYMENT_ID = DC.PAYMENT_ID
                JOIN PURCHASE_CONFIRM_HISTORY PCH ON DC.SHIPPING_ID = PCH.SHIPPING_ID
                JOIN TRANSACTION_COMPLETED TC ON PCH.PURCHASE_CONFIRM_ID = TC.PURCHASE_CONFIRM_ID);

            IF V_HAS_BID > 0 THEN
                RAISE ERR_HAS_ACTIVE_WINNING;
            END IF;
        
    -- 잔여머니가 있는지
        IF (FN_GET_USER_MONEY_BALANCE(P_USER_ID)>0) THEN
            RAISE ERR_HAS_MONEY;
        END IF;
    
    -- 회원의 상태가 영구정지 상태인지
        SELECT NVL(SUM(PENALTY_SCORE), 0) INTO V_PENALTY_SCORE
        FROM PENALTY_HISTORY
        WHERE USER_ID = P_USER_ID
        AND PENALTY_ID NOT IN (SELECT PENALTY_ID FROM PENALTY_CANCEL);

        IF V_PENALTY_SCORE >= 4 THEN
            RAISE ERR_HAS_PENALTY;
        END IF;

    
    -- USER_PROFILE 조회
        SELECT USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE
        , USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL 
        INTO V_NAME, V_SSN, V_EMAIL, V_PHONE, V_ZIPCODE, V_ADDRESS, V_DETAIL
        FROM USER_PROFILE
        WHERE USER_ID = P_USER_ID;

    -- DELETED_USER INSERT
        INSERT INTO DELETED_USER(USER_ID, USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE, USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL)
        VALUES(P_USER_ID, V_NAME, V_SSN, V_EMAIL, V_PHONE, V_ZIPCODE, V_ADDRESS, V_DETAIL);
    
    -- USER_PROFILE DELETE
        DELETE
        FROM USER_PROFILE
        WHERE USER_ID = P_USER_ID;

    -- ACCOUNT_EVENT_HISTORY INSERT
        INSERT INTO ACCOUNT_EVENT_HISTORY
        VALUES(ACCOUNT_EVENT_HISTORY_SEQ.NEXTVAL, P_USER_ID, 2, SYSDATE);
    
    EXCEPTION
        WHEN ERR_HAS_ACTIVE_AUCTION THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20016, '진행 중인 경매가 존재합니다.');
        WHEN ERR_HAS_ACTIVE_BID THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20026, '진행 중인 입찰이 존재합니다.');
        WHEN ERR_HAS_ACTIVE_WINNING THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20027, '진행 중인 낙찰이 존재합니다.');
        WHEN ERR_HAS_PENALTY THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20028, '영구정지 회원은 탈퇴가 불가능합니다.');
        WHEN ERR_HAS_MONEY THEN   
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20029, '잔여머니가 존재합니다.');
    
END;
/

-- ○ 3. 상품 등록 프로시저
CREATE OR REPLACE PROCEDURE PRC_PRODUCT_INSERT
(
      P_USER_ID              IN PRODUCT.USER_ID%TYPE              -- 회원고유키 (NN)
    , P_PRODUCT_RELEASE_NAME IN PRODUCT.PRODUCT_RELEASE_NAME%TYPE -- 상품 발매명
    , P_PRODUCT_ALIAS        IN PRODUCT.PRODUCT_ALIAS%TYPE        -- 상품 별칭
    , P_MANUFACTURER_ID      IN PRODUCT.MANUFACTURER_ID%TYPE      -- 제조사 코드
    , P_PRODUCT_GRADE_ID     IN PRODUCT.PRODUCT_GRADE_ID%TYPE     -- 등급 코드 (NN)
    , P_PRODUCT_GENRE_ID     IN PRODUCT.PRODUCT_GENRE_ID%TYPE     -- 장르 코드 (NN)
    , P_PRODUCT_SIZE_ID      IN PRODUCT.PRODUCT_SIZE_ID%TYPE      -- 사이즈 코드 (NN)
    , P_WORK_NAME            IN PRODUCT.WORK_NAME%TYPE            -- 작품명
    , P_CHARACTER_NAME       IN PRODUCT.CHARACTER_NAME%TYPE       -- 캐릭터명
    , P_PURCHASE_DATETIME    IN PRODUCT.PURCHASE_DATETIME%TYPE    -- 구매일시
    , P_IS_OPENED            IN PRODUCT.IS_OPENED%TYPE            -- 개봉여부 (NN)
    , P_IS_PARTS_MISSING     IN PRODUCT.IS_PARTS_MISSING%TYPE     -- 파츠 누락 여부 (NN)
    , P_DESCRIPTIONS         IN PRODUCT.DESCRIPTIONS%TYPE         -- 상세설명
    , P_IMAGE_PATH_1         IN PRODUCT.IMAGE_PATH_1%TYPE         -- 이미지 1 (NN)
    , P_IMAGE_PATH_2         IN PRODUCT.IMAGE_PATH_2%TYPE         -- 이미지 2 (NN)
    , P_IMAGE_PATH_3         IN PRODUCT.IMAGE_PATH_3%TYPE         -- 이미지 3 (NN)
    , P_IS_PUBLIC            IN PRODUCT.IS_PUBLIC%TYPE            -- 공개 여부 (NN)
)
IS
    V_CNT NUMBER;
BEGIN
   
    -- 회원 정보 체크
    IF P_USER_ID IS NULL THEN
        RAISE_APPLICATION_ERROR(-20010, '회원 정보가 유효하지 않습니다.');
    END IF;

    -- 선택사항 체크
    IF P_PRODUCT_GRADE_ID IS NULL OR P_PRODUCT_GENRE_ID IS NULL OR P_PRODUCT_SIZE_ID IS NULL THEN
        RAISE_APPLICATION_ERROR(-20011, '상품 등급, 장르, 사이즈는 필수 선택 사항입니다.');
    END IF;

    -- 상태 및 공개 여부 체크
    IF P_IS_OPENED IS NULL OR P_IS_PARTS_MISSING IS NULL OR P_IS_PUBLIC IS NULL THEN
        RAISE_APPLICATION_ERROR(-20012, '개봉/누락/공개 여부를 모두 선택해주세요.');
    END IF;

    -- 이미지 3장 필수 체크
    IF P_IMAGE_PATH_1 IS NULL OR P_IMAGE_PATH_2 IS NULL OR P_IMAGE_PATH_3 IS NULL THEN
        RAISE_APPLICATION_ERROR(-20013, '상품 사진은 최소 3장이 필요합니다.');
    END IF;

    INSERT INTO PRODUCT 
    (
          PRODUCT_ID,           USER_ID,              PRODUCT_RELEASE_NAME
        , PRODUCT_ALIAS,        MANUFACTURER_ID,      PRODUCT_GRADE_ID
        , PRODUCT_GENRE_ID,     PRODUCT_SIZE_ID,      WORK_NAME
        , CHARACTER_NAME,       PURCHASE_DATETIME,    IS_OPENED
        , IS_PARTS_MISSING,     DESCRIPTIONS,         IMAGE_PATH_1
        , IMAGE_PATH_2,         IMAGE_PATH_3,         IS_PUBLIC
        , CREATED_AT
    ) VALUES 
    (
          PRODUCT_SEQ.NEXTVAL,  P_USER_ID,            P_PRODUCT_RELEASE_NAME
        , P_PRODUCT_ALIAS,      P_MANUFACTURER_ID,    P_PRODUCT_GRADE_ID
        , P_PRODUCT_GENRE_ID,   P_PRODUCT_SIZE_ID,    P_WORK_NAME
        , P_CHARACTER_NAME,     P_PURCHASE_DATETIME,  P_IS_OPENED
        , P_IS_PARTS_MISSING,   P_DESCRIPTIONS,       P_IMAGE_PATH_1
        , P_IMAGE_PATH_2,       P_IMAGE_PATH_3,       P_IS_PUBLIC
        , SYSDATE
    );
    
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20015, '상품등록이 실패하였습니다.');
    END IF;

    COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- ○ 4. 상품 수정 프로시저
CREATE OR REPLACE PROCEDURE PRC_PRODUCT_UPDATE
(
      P_PRODUCT_ID           IN PRODUCT.PRODUCT_ID%TYPE           -- 상품코드 (PK)
    , P_USER_ID              IN PRODUCT.USER_ID%TYPE              -- 본인 확인용
    , P_PRODUCT_RELEASE_NAME IN PRODUCT.PRODUCT_RELEASE_NAME%TYPE -- 상품 발매명
    , P_PRODUCT_ALIAS        IN PRODUCT.PRODUCT_ALIAS%TYPE        -- 상품 별칭
    , P_MANUFACTURER_ID      IN PRODUCT.MANUFACTURER_ID%TYPE      -- 제조사 코드
    , P_PRODUCT_GRADE_ID     IN PRODUCT.PRODUCT_GRADE_ID%TYPE     -- 등급 코드 (NN)
    , P_PRODUCT_GENRE_ID     IN PRODUCT.PRODUCT_GENRE_ID%TYPE     -- 장르 코드 (NN)
    , P_PRODUCT_SIZE_ID      IN PRODUCT.PRODUCT_SIZE_ID%TYPE      -- 사이즈 코드 (NN)
    , P_WORK_NAME            IN PRODUCT.WORK_NAME%TYPE            -- 작품명
    , P_CHARACTER_NAME       IN PRODUCT.CHARACTER_NAME%TYPE       -- 캐릭터명
    , P_PURCHASE_DATETIME    IN PRODUCT.PURCHASE_DATETIME%TYPE    -- 구매일시
    , P_IS_OPENED            IN PRODUCT.IS_OPENED%TYPE            -- 개봉여부 (NN)
    , P_IS_PARTS_MISSING     IN PRODUCT.IS_PARTS_MISSING%TYPE     -- 파츠 누락 여부 (NN)
    , P_DESCRIPTIONS         IN PRODUCT.DESCRIPTIONS%TYPE         -- 상세설명
    , P_IMAGE_PATH_1         IN PRODUCT.IMAGE_PATH_1%TYPE         -- 이미지 1 (NN)
    , P_IMAGE_PATH_2         IN PRODUCT.IMAGE_PATH_2%TYPE         -- 이미지 2 (NN)
    , P_IMAGE_PATH_3         IN PRODUCT.IMAGE_PATH_3%TYPE         -- 이미지 3 (NN)
    , P_IS_PUBLIC            IN PRODUCT.IS_PUBLIC%TYPE            -- 공개 여부 (NN)
)
IS
    V_CNT NUMBER;
BEGIN
   
    -- 상품 정보 체크
    IF P_PRODUCT_ID IS NULL OR P_USER_ID IS NULL THEN
        RAISE_APPLICATION_ERROR(-20023, 'ERR_ID_REQUIRED');
    END IF;


    -- 선택사항 체크
    IF P_PRODUCT_GRADE_ID IS NULL OR P_PRODUCT_GENRE_ID IS NULL OR P_PRODUCT_SIZE_ID IS NULL THEN
        RAISE_APPLICATION_ERROR(-20011, '상품의 등급, 장르, 사이즈 정보는 필수입니다.');
    END IF;
    
    -- 상태 및 공개 여부 체크
    IF P_IS_OPENED IS NULL OR P_IS_PARTS_MISSING IS NULL OR P_IS_PUBLIC IS NULL THEN
        RAISE_APPLICATION_ERROR(-20012, '개봉 여부, 파츠 누락 여부, 공개 설정은 필수 선택 사항입니다.');
    END IF;
    
    -- 이미지 3장 필수 체크
    IF P_IMAGE_PATH_1 IS NULL OR P_IMAGE_PATH_2 IS NULL OR P_IMAGE_PATH_3 IS NULL THEN
        RAISE_APPLICATION_ERROR(-20013, '이미지 3장은 필수 항목입니다.');
    END IF;

    -- 상품 존재 및 본인 소유 여부 확인
    SELECT COUNT(*) INTO V_CNT
    FROM PRODUCT
    WHERE PRODUCT_ID = P_PRODUCT_ID AND USER_ID = P_USER_ID;

    IF V_CNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20021, '해당 상품이 없거나 수정 권한이 없습니다.');
    END IF;

    UPDATE PRODUCT
    SET PRODUCT_RELEASE_NAME = P_PRODUCT_RELEASE_NAME, PRODUCT_ALIAS = P_PRODUCT_ALIAS,   MANUFACTURER_ID    = P_MANUFACTURER_ID
     , PRODUCT_GRADE_ID     = P_PRODUCT_GRADE_ID,    PRODUCT_GENRE_ID = P_PRODUCT_GENRE_ID, PRODUCT_SIZE_ID  = P_PRODUCT_SIZE_ID
     , WORK_NAME            = P_WORK_NAME,           CHARACTER_NAME   = P_CHARACTER_NAME,   PURCHASE_DATETIME= P_PURCHASE_DATETIME
     , IS_OPENED            = P_IS_OPENED,           IS_PARTS_MISSING = P_IS_PARTS_MISSING, DESCRIPTIONS     = P_DESCRIPTIONS
     , IMAGE_PATH_1         = P_IMAGE_PATH_1,        IMAGE_PATH_2     = P_IMAGE_PATH_2,     IMAGE_PATH_3     = P_IMAGE_PATH_3
     , IS_PUBLIC            = P_IS_PUBLIC
    WHERE PRODUCT_ID = P_PRODUCT_ID;
    
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20022, '수정 대상이 존재하지 않습니다.');
    END IF;

    COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/


-- ○ 5. 상품 삭제 프로시저

CREATE OR REPLACE PROCEDURE PRC_PRODUCT_DELETE
(
      P_PRODUCT_ID IN PRODUCT.PRODUCT_ID%TYPE 
    , P_USER_ID    IN PRODUCT.USER_ID%TYPE  
)
IS
    V_CNT NUMBER;
BEGIN
    -- 파라미터 체크
    IF P_PRODUCT_ID IS NULL THEN
        RAISE_APPLICATION_ERROR(-20023, '삭제할 상품 번호가 입력되지 않았습니다.');
    END IF;
    
    IF P_USER_ID IS NULL THEN
        RAISE_APPLICATION_ERROR(-20010, '회원 정보가 유효하지 않습니다.');
    END IF;

    -- 상품 존재 및 본인 여부 확인
    SELECT COUNT(*) INTO V_CNT
    FROM PRODUCT
    WHERE PRODUCT_ID = P_PRODUCT_ID AND USER_ID = P_USER_ID;

    IF V_CNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20024, '삭제 권한이 없거나 이미 존재하지 않는 상품입니다.');
    END IF;

    -- 진행 중인 경매 여부 확인 (함수 FN_IS_AUCTION_FINISHED 활용)
    -- 해당 상품으로 등록된 경매들 중, 함수 결과 0 = 경매중
    SELECT COUNT(*) INTO V_CNT
    FROM AUCTION_REGISTRATION
    WHERE PRODUCT_ID = P_PRODUCT_ID
      AND FN_IS_AUCTION_FINISHED(AUCTION_ID) = 0; 

    IF V_CNT > 0 THEN
        RAISE_APPLICATION_ERROR(-20016, '진행 중인 경매가 존재합니다.');
    END IF;

    -- 이미지 테이블 삭제
    DELETE FROM PRODUCT_IMAGE
    WHERE PRODUCT_ID = P_PRODUCT_ID;
    
    -- 상품 삭제
    DELETE FROM PRODUCT
    WHERE PRODUCT_ID = P_PRODUCT_ID;
    
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20025, '삭제 대상이 존재하지 않습니다.');
    END IF;

    COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/


-- ○ 6. 경매 등록 프로시저
CREATE OR REPLACE PROCEDURE PRC_AUCTION_CREATE(
    P_USER_ID           IN NUMBER,              --회원 고유키
    P_PRODUCT_ID        IN NUMBER,              --상품코드
    P_AUCTION_TITLE     IN VARCHAR2,            --경매제목
    P_CONTENT           IN VARCHAR2,            --경매 글
    P_START_PRICE       IN NUMBER,              --시작가
    P_PERIOD_CODE       IN NUMBER               --경매기간
)
IS
    -- 에러 번호 변수 선언
    ERR_LACK_MONEY      CONSTANT NUMBER := -20004;
    ERR_UNKNOWN         CONSTANT NUMBER := -20009;

    V_CURRENT_MONEY     NUMBER := 0;
    V_AUCTION_ID        NUMBER;
BEGIN
    
    -- 해당 유저의 보증금 확인
    SELECT NVL(SUM(AMOUNT), 0) INTO v_current_money
    FROM MONEY_TRANSACTION_HISTORY
    WHERE USER_ID = P_USER_ID;

    -- 보증금 부족할 시 RAISE
    IF v_current_money < 30000 THEN
        RAISE_APPLICATION_ERROR(ERR_LACK_MONEY, '보증금이 부족합니다.');
    END IF;

    -- 경매 등록 테이블 INSERT
    INSERT INTO AUCTION_REGISTRATION (
        AUCTION_ID, PRODUCT_ID, AUCTION_TITLE, AUCTION_CONTENT, 
        START_PRICE, CREATED_AT, AUCTION_PERIOD_ID
    ) VALUES (
        AUCTION_SEQ.NEXTVAL, P_PRODUCT_ID, P_AUCTION_TITLE, 
        P_CONTENT, P_START_PRICE, SYSDATE, P_PERIOD_CODE
    ) RETURNING AUCTION_ID INTO V_AUCTION_ID;   -- 해당 AUCTION_ID를 바로 V변수에 담음
    

    -- 머니 차감 기록 INSERT
    INSERT INTO MONEY_TRANSACTION_HISTORY (
        MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT, CREATED_AT
    ) VALUES (
        MONEY_TRANSACTION_SEQ.NEXTVAL, P_USER_ID, 2, V_AUCTION_ID, -30000, SYSDATE
    );
EXCEPTION        
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE BETWEEN -20999 AND -20000 THEN
            RAISE; -- 이미 정의된 커스텀 에러는 그대로 통과
        ELSE
            RAISE_APPLICATION_ERROR(ERR_UNKNOWN, '예상치 못한 오류가 발생했습니다');
        END IF;
END;
/

-- ○ 7. 경매 취소 프로시저 
CREATE OR REPLACE PROCEDURE PRC_AUCTION_CANCEL(
    P_AUCTION_ID    NUMBER,
    P_USER_ID       NUMBER,
    P_CANCEL_REASON VARCHAR2
)
IS
    V_PENALTY_ID      NUMBER;
    V_TOTAL_SCORE     NUMBER := 0;
    V_END_DATE        DATE;        -- 정지 종료일
    
    CURSOR BIDDER_LIST IS
        SELECT DISTINCT USER_ID FROM AUCTION_BID_PARTICIPATION WHERE AUCTION_ID = P_AUCTION_ID;
BEGIN
    -- 1. 입찰자 전원 보증금 환급 
    FOR R IN BIDDER_LIST LOOP
        INSERT INTO MONEY_TRANSACTION_HISTORY (
            MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT, CREATED_AT
        ) VALUES (
            MONEY_TRANSACTION_SEQ.NEXTVAL, R.USER_ID, 5, P_AUCTION_ID, 30000, SYSDATE
        );
    END LOOP;

    -- 2. 판매자 보증금 몰수 기록
    INSERT INTO MONEY_TRANSACTION_HISTORY (
        MONEY_ID, USER_ID, MONEY_TYPE_ID, AUCTION_ID, AMOUNT, CREATED_AT
    ) VALUES (
        MONEY_TRANSACTION_SEQ.NEXTVAL, P_USER_ID, 7, P_AUCTION_ID, 0, SYSDATE
    );
    
    -- 3. 패널티 점수 계산 로직 (누적 점수 - 취소 점수)
    SELECT (
        (SELECT NVL(SUM(PENALTY_SCORE), 0) FROM PENALTY_HISTORY WHERE USER_ID = P_USER_ID) -
        (SELECT NVL(SUM(PH.PENALTY_SCORE), 0) 
         FROM PENALTY_CANCEL PC 
         JOIN PENALTY_HISTORY PH ON PC.PENALTY_ID = PH.PENALTY_ID 
         WHERE PH.USER_ID = P_USER_ID)
    ) INTO V_TOTAL_SCORE FROM DUAL;

    V_TOTAL_SCORE := V_TOTAL_SCORE + 1;

    -- 4. 패널티 단계별 정지 종료일 설정
    IF V_TOTAL_SCORE = 1 THEN
        V_END_DATE := SYSDATE; 
    ELSIF V_TOTAL_SCORE = 2 THEN
        V_END_DATE := SYSDATE + 7;
    ELSIF V_TOTAL_SCORE = 3 THEN
        V_END_DATE := SYSDATE + 30;
    ELSE
        V_END_DATE := TO_DATE('9999-12-31', 'YYYY-MM-DD');
    END IF;

    -- 5. 패널티 이력 INSERT
    V_PENALTY_ID := PENALTY_SEQ.NEXTVAL;
    INSERT INTO PENALTY_HISTORY (
        PENALTY_ID, USER_ID, PENALTY_TYPE_ID, ADMIN_ACCOUNT_ID, PENALTY_SCORE, CREATED_AT
    ) VALUES (
        V_PENALTY_ID, P_USER_ID, 1, NULL, 1, SYSDATE 
    );

    -- 6. 패널티 상태 기록
    INSERT INTO PENALTY_STATUS (
        PENALTY_STATUS_ID, PENALTY_ID, PENALTY_START_DATE, PENALTY_END_DATE
    ) VALUES (
        PENALTY_STATUS_SEQ.NEXTVAL, V_PENALTY_ID, SYSDATE, V_END_DATE
    );

    -- 7. 경매 취소 이력 기록
    INSERT INTO AUCTION_CANCEL_HISTORY (
        AUCTION_CANCEL_ID, AUCTION_ID, CANCEL_REASON, CANCEL_AT
    ) VALUES (
        AUCTION_CANCEL_SEQ.NEXTVAL, P_AUCTION_ID, P_CANCEL_REASON, SYSDATE
    );

    -- COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        
        IF SQLCODE BETWEEN -20999 AND -20000 THEN
            RAISE; -- 이미 정의된 커스텀 에러는 그대로 통과
        ELSE
            RAISE_APPLICATION_ERROR(ERR_UNKNOWN, '예상치 못한 오류가 발생했습니다');
        END IF;
END;
/

-- ○ 8. 입찰 생성 프로시저

-- ○ 9. 경매 마감 및 낙찰 처리 프로시저

-- ○ 10. 낙찰 결제 프로시저
CREATE OR REPLACE PROCEDURE PRC_WINNING_PAYMENT_CREATE
(
V_USER_ID USERS.USER_ID%TYPE
,V_RESULT_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE
,V_AMOUNT MONEY_TRANSACTION_HISTORY.AMOUNT%TYPE
)
AS
    N_BID_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE;
    N_AUCTION_ID AUCTION_BID_PARTICIPATION.AUCTION_ID%TYPE;
    N_USER_ID USERS.USER_ID%TYPE;
    N_MONEY_TYPE MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_CREATE_AT AUCTION_REGISTRATION.CREATED_AT%TYPE;
    N_AUCTION_PERIOD_ID AUCTION_PERIOD.AUCTION_PERIOD_ID%TYPE;
    
    N_AUCTION_PERIOD_NAME AUCTION_PERIOD.AUCTION_PERIOD_NAME%TYPE;
    
    N_END_CREATE_AT AUCTION_REGISTRATION.CREATED_AT%TYPE;
    
    N_START_PRICE AUCTION_REGISTRATION.START_PRICE%TYPE;
    
    N_AUCTION_PRICE AUCTION_BID_PARTICIPATION.BID_PRICE%TYPE;
    
    NEW_ERR EXCEPTION;
    NEW_ERR1 EXCEPTION;
BEGIN
 
    SELECT BID_ID INTO N_BID_ID
    FROM AUCTION_WINNING_RESULT
    WHERE BID_RESULT_ID = V_RESULT_ID;
    
    SELECT AUCTION_ID,USER_ID INTO N_AUCTION_ID,N_USER_ID
    FROM AUCTION_BID_PARTICIPATION
    WHERE BID_ID = N_BID_ID;
    
    IF(N_USER_ID != V_USER_ID)
        THEN RAISE NEW_ERR1;
    END IF;
    
    SELECT MONEY_TYPE_ID INTO N_MONEY_TYPE
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '결제 대금 입금';
    
    SELECT CREATED_AT,AUCTION_PERIOD_ID,START_PRICE INTO N_CREATE_AT,N_AUCTION_PERIOD_ID,N_START_PRICE
    FROM AUCTION_REGISTRATION
    WHERE AUCTION_ID = N_AUCTION_ID;
    
    SELECT AUCTION_PERIOD_NAME INTO N_AUCTION_PERIOD_NAME
    FROM AUCTION_PERIOD
    WHERE AUCTION_PERIOD_ID = N_AUCTION_PERIOD_ID;
    
    N_AUCTION_PERIOD_NAME := REPLACE(N_AUCTION_PERIOD_NAME,'일','');
    N_AUCTION_PERIOD_NAME := REPLACE(N_AUCTION_PERIOD_NAME,'시간','');
    
    N_END_CREATE_AT := N_CREATE_AT + N_AUCTION_PERIOD_NAME;
    
    IF(N_END_CREATE_AT > SYSTIMESTAMP)
        THEN RAISE NEW_ERR;
    END IF;
    
--    SELECT NVL(BID_ID,N_START_PRICE) INTO N_AUCTION_PRICE
--    FROM AUCTION_BID_PARTICIPATION
--    WHERE AUCTION_ID = N_AUCTION_ID
--    ORDER BY BID_PRICE DESC
--    OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY;
    
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID
    ,MONEY_TYPE_ID,AUCTION_ID,AMOUNT)
    VALUES(MONEY_TRANSACTION_SEQ.NEXTVAL,V_USER_ID
    ,N_MONEY_TYPE,N_AUCTION_ID,V_AMOUNT);
    
    INSERT INTO AUCTION_WINNING_PAYMENT(PAYMENT_ID
    ,BID_RESULT_ID,MONEY_ID)
    VALUES(PAYMENT_SEQ.NEXTVAL,V_RESULT_ID
    ,MONEY_TRANSACTION_SEQ.CURRVAL);
    
    COMMIT;
    
    EXCEPTION 
        WHEN NEW_ERR
        THEN RAISE_APPLICATION_ERROR(-20100,'경매기간이 마감되어 결제가 불가능합니다');
        ROLLBACK;
        WHEN NEW_ERR1
        THEN RAISE_APPLICATION_ERROR(-20101,'결제자와 입찰자가 다릅니다.');
        ROLLBACK;
        WHEN OTHERS
        THEN DBMS_OUTPUT.PUT_LINE('예외 발생 :'|| SQLERRM);
END;
/


-- ○ 11. 구매 확정 및 거래 완료 프로시저
CREATE OR REPLACE PROCEDURE PRC_PURCHASE_CONFIRM
(
V_USER_ID USERS.USER_ID%TYPE
,V_RESULT_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE
)
IS
    N_CHECK NUMBER;
    N_PAYMENT_ID AUCTION_WINNING_PAYMENT.PAYMENT_ID%TYPE;
    N_SHIPPING_ID DELIVERY_COMPLETED.SHIPPING_ID%TYPE;
    
    N_MONEY_TYPE1 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE2 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    
    N_MONEY_TYPE3 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE4 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    
    N_AUCTION_ID AUCTION_REGISTRATION.AUCTION_ID%TYPE;
    
    NEW_ERR EXCEPTION;
    NEW_ERR2 EXCEPTION;
BEGIN
    
    
    SELECT NVL(PAYMENT_ID,0) INTO N_PAYMENT_ID
    FROM AUCTION_WINNING_PAYMENT
    WHERE BID_RESULT_ID = V_RESULT_ID;
    
    IF(N_PAYMENT_ID = 0)
        THEN RAISE NEW_ERR;
    END IF;
    
    SELECT NVL(SHIPPING_ID,0) INTO N_SHIPPING_ID
    FROM DELIVERY_COMPLETED
    WHERE PAYMENT_ID = N_PAYMENT_ID;
    
    IF(N_SHIPPING_ID = 0)
        THEN RAISE NEW_ERR2;
    END IF;

    INSERT INTO PURCHASE_CONFIRM_HISTORY(PURCHASE_CONFIRM_ID,SHIPPING_ID)
    VALUES(PURCHASE_CONFIRM_SEQ.NEXTVAL,N_SHIPPING_ID);
    
    
    SELECT MONEY_TYPE_ID INTO N_MONEY_TYPE1
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 환급';
    
    SELECT MONEY_TYPE_ID INTO N_MONEY_TYPE2
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 환급';
    
    SELECT MONEY_TYPE_ID INTO N_MONEY_TYPE3
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 납부';
    
    SELECT MONEY_TYPE_ID INTO N_MONEY_TYPE4
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 납부';
    
    SELECT B.AUCTION_ID INTO N_AUCTION_ID
    FROM AUCTION_WINNING_RESULT A LEFT JOIN AUCTION_BID_PARTICIPATION B
    ON A.BID_ID = B.BID_ID
    WHERE A.BID_RESULT_ID = V_RESULT_ID;
    
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_SEQ.NEXTVAL,USER_ID,N_MONEY_TYPE1,AUCTION_ID,AMOUNT
    FROM MONEY_TRANSACTION_HISTORY
    WHERE AUCTION_ID = N_AUCTION_ID
    AND MONEY_TYPE_ID = N_MONEY_TYPE3;

    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_SEQ.NEXTVAL,USER_ID,N_MONEY_TYPE2,AUCTION_ID,AMOUNT
    FROM MONEY_TRANSACTION_HISTORY
    WHERE USER_ID = V_USER_ID
    AND AUCTION_ID = N_AUCTION_ID
    AND MONEY_TYPE_ID = N_MONEY_TYPE4; 
    
    INSERT INTO TRANSACTION_COMPLETED(TRANSACTION_ID,PURCHASE_CONFIRM_ID)
    VALUES(TRANSACTION_SEQ.NEXTVAL,PURCHASE_CONFIRM_SEQ.CURRVAL);
    
    COMMIT;
    
    EXCEPTION 
        WHEN NEW_ERR
        THEN ROLLBACK;
        RAISE_APPLICATION_ERROR(-20102,'입금되지않은 낙찰입니다.');
        
        WHEN NEW_ERR2
        THEN ROLLBACK;
        RAISE_APPLICATION_ERROR(-20103,'발송되지않은 낙찰입니다.');
        
END;
/

-- ○ 12. 낙찰 실패 처리 프로시저

-- ○ 13. 신고 접수 프로시저

-- ○ 14. 신고 처리 프로시저

-- ○ 15. 패널티 부여 프로시저


-- ○ 16. 패널티 취소 프로시저
CREATE OR REPLACE PROCEDURE PRC_PENALTY_CANCEL
( V_PENALTY_ID              IN          PENALTY_HISTORY.PENALTY_ID%TYPE
, V_ADMIN_ACCOUNT_ID        IN          ADMIN_ACCOUNT.ADMIN_ACCOUNT_ID%TYPE
, V_CANCEL_REASON           IN          PENALTY_CANCEL.CANCEL_REASON%TYPE
)
IS
BEGIN
    -- 패널티 취소 처리
    INSERT INTO PENALTY_CANCEL(PENALTY_CANCEL_ID, PENALTY_ID, ADMIN_ACCOUNT_ID, CANCEL_REASON, CANCELED_AT)
    VALUES(PENALTY_CANCEL_SEQ.NEXTVAL, V_PENALTY_ID, V_ADMIN_ACCOUNT_ID, V_CANCEL_REASON, SYSDATE);

	-- 패널티 취소에 대한 추가 로직 필요시 작성 가능...
END;


-- ○ 17. 낙찰 결제 기한 확인 스케줄러용 프로시저
CREATE OR REPLACE PROCEDURE REC_AUCTION_CLOSE
IS
    N_BID_FAIL_TYPE_ID BID_FAILURE_TYPE.BID_FAIL_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID MONEY_TYPE.MONEY_TYPE_ID%TYPE;
BEGIN

    SELECT NVL(BID_FAIL_TYPE_ID,0) INTO N_BID_FAIL_TYPE_ID
    FROM BID_FAILURE_TYPE
    WHERE BID_FAIL_TYPE_NAME = '기한만료';
    
    IF(N_BID_FAIL_TYPE_ID = 0)
        THEN RAISE_APPLICATION_ERROR(-20105,'낙찰실패타입 테이블에 "기한만료" 코드명이 존재하지 않습니다');
    END IF;

    INSERT INTO BID_FAILURE_HISTORY(BID_FAIL_HISTORY_ID,BID_RESULT_ID,BID_FAIL_TYPE_ID)
    SELECT BID_FAIL_HISTORY_SEQ.NEXTVAL,M.BID_RESULT_ID,N_BID_FAIL_TYPE_ID
    FROM
        (
            SELECT A.BID_RESULT_ID
            ,CASE 
             WHEN A.CREATED_AT IS NULL THEN '오류'
             WHEN A.CREATED_AT+1 >= SYSDATE THEN '안전'
             WHEN A.CREATED_AT+1 < SYSDATE THEN '마감'
             ELSE '오류'
             END AS CREATED_AT
            FROM AUCTION_WINNING_RESULT A LEFT JOIN AUCTION_WINNING_PAYMENT B
            ON A.BID_RESULT_ID = B.BID_RESULT_ID
            LEFT JOIN BID_FAILURE_HISTORY C
            ON A.BID_RESULT_ID = C.BID_RESULT_ID
            WHERE B.BID_RESULT_ID IS NULL AND C.BID_RESULT_ID IS NULL
        )M
    WHERE M.CREATED_AT = '마감';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '보증금 몰수';
    
    IF(N_MONEY_TYPE_ID = 0)
        THEN RAISE_APPLICATION_ERROR(-20106,'머니 분류 테이블에 "보증금 몰수" 코드명이 존재하지 않습니다');
    END IF;
    
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
     SELECT MONEY_SEQ.NEXTVAL,C.USER_ID,N_MONEY_TYPE_ID,C.AUCTION_ID,0
     FROM BID_FAILURE_HISTORY A INNER JOIN AUCTION_WINNING_RESULT B
     ON A.BID_RESULT_ID = B.BID_RESULT_ID
     INNER JOIN AUCTION_BID_PARTICIPATION C
     ON B.BID_ID = C.BID_ID
     LEFT JOIN MONEY_TRANSACTION_HISTORY D
     ON C.AUCTION_ID = D.AUCTION_ID AND C.USER_ID = D.USER_ID
     AND D.MONEY_TYPE_ID = N_MONEY_TYPE_ID
     WHERE D.MONEY_ID IS NULL;
     
    COMMIT;
    
    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN RAISE_APPLICATION_ERROR(-20105,'낙찰실패타입 테이블에 "기한만료" 코드명이 존재하지 않습니다');
    
END;
/

-- ○ 18. 구매 확정 자동 처리 스케줄러용 프로시저
CREATE OR REPLACE PROCEDURE PRC_AUTO_PURCHASE_CONFIRM
IS
BEGIN

    INSERT INTO PURCHASE_CONFIRM_HISTORY(PURCHASE_CONFIRM_ID,SHIPPING_ID)
    SELECT PURCHASE_CONFIRM_SEQ.NEXTVAL,M.SHIPPING_ID
    FROM
        (
            SELECT A.SHIPPING_ID
            FROM DELIVERY_COMPLETED A LEFT JOIN PURCHASE_CONFIRM_HISTORY B
            ON A.SHIPPING_ID = B.SHIPPING_ID
            WHERE B.SHIPPING_ID IS NULL
            AND A.CREATED_AT+3 < SYSDATE
        )M
    
    SELECT
    FROM PURCHASE_CONFIRM_HISTORY A LEFT JOIN TRANSACTION_COMPLETED B
    ON A.SHIPPING_ID = B.SHIPPING_ID
    WHERE B
    
    COMMIT;
END;
/


-- ○ 19. 탈퇴 회원 정리 스케줄러용 프로시저
CREATE OR REPLACE PROCEDURE PRC_DELETED_USER_CLEANUP
IS
    N_ACCOUNT_EVENT_TYPE_ID ACCOUNT_EVENT_TYPE.ACCOUNT_EVENT_TYPE_ID%TYPE;
BEGIN
    SELECT NVL(ACCOUNT_EVENT_TYPE_ID,0) INTO N_ACCOUNT_EVENT_TYPE_ID
    FROM ACCOUNT_EVENT_TYPE
    WHERE EVENT_NAME = '탈퇴';

    IF(N_ACCOUNT_EVENT_TYPE_ID = 0)
        THEN RAISE_APPLICATION_ERROR(-20106,'계정 이벤트 분류 코드명에 "탈퇴"인 이벤트명이없습니다');
    END IF;
    
    DELETE 
    FROM DELETED_USER A
    WHERE EXISTS
    (SELECT 1
    FROM ACCOUNT_EVENT_HISTORY B
    WHERE A.USER_ID = B.USER_ID
    AND B.ACCOUNT_EVENT_TYPE_ID = N_ACCOUNT_EVENT_TYPE_ID
    AND ADD_MONTHS(B.CREATED_AT,3) > SYSDATE  
    );
    
    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN RAISE_APPLICATION_ERROR(-20106,'계정 이벤트 분류 코드명에 "탈퇴"인 이벤트명이 비어있습니다');
END;



-- 함수 =========================================================================



-- ○ 1. 회원 잔여 머니 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_USER_MONEY_BALANCE
(P_USER_ID IN USERS.USER_ID%TYPE
)
RETURN NUMBER
IS
    V_MONEY1    NUMBER;
    V_MONEY2    NUMBER;
BEGIN

-- 머니입출금이력테이블에서 아이디로 조회해서 금액 계산한 값 +
-- 머니 충전 이력 테이블에서 아이디로 조회해서 금액 계산한 값

    SELECT NVL(SUM(AMOUNT), 0) INTO V_MONEY1
    FROM MONEY_TRANSACTION_HISTORY
    WHERE USER_ID = P_USER_ID;
    
    SELECT NVL(SUM(CHARGE_AMOUNT),0) INTO V_MONEY2
    FROM MONEY_CHARGE_HISTORY
    WHERE USER_ID = P_USER_ID;
    
    RETURN V_MONEY1+V_MONEY2;
    
    EXCEPTION 
        WHEN OTHERS THEN
            RETURN -1;
END;
/

-- ○ 2. 경매 현재가 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_AUCTION_CURRENT_PRICE
(
    P_AUCTION_ID IN NUMBER
)
RETURN NUMBER
IS
    V_CURRENT_PRICE NUMBER;
    V_START_PRICE   NUMBER;
    V_BID_COUNT     NUMBER;
BEGIN

    -- 경매 시작가 조회
    SELECT START_PRICE INTO V_START_PRICE
    FROM AUCTION_REGISTRATION
    WHERE AUCTION_ID = P_AUCTION_ID;

    -- 입찰자 수 확인
    SELECT COUNT(*) INTO V_BID_COUNT
    FROM AUCTION_BID_PARTICIPATION
    WHERE AUCTION_ID = P_AUCTION_ID;

    -- 0명 또는 1명이면 시작가 반환
    IF V_BID_COUNT <= 1 THEN
        RETURN V_START_PRICE;
    END IF;

    -- 2명 이상부터  →2등 금액 가져오기
    SELECT BID_PRICE INTO V_CURRENT_PRICE
    FROM AUCTION_BID_PARTICIPATION
    WHERE AUCTION_ID = P_AUCTION_ID
    ORDER BY BID_PRICE DESC
    OFFSET 1 ROW FETCH NEXT 1 ROW ONLY;

    RETURN V_CURRENT_PRICE;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
    WHEN OTHERS THEN
        RAISE;
END;
/

-- ○ 3. 경매 입찰 단위 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_BID_UNIT
(
    P_START_PRICE IN NUMBER  -- 경매 시작가
)
RETURN NUMBER
IS
    V_BID_UNIT NUMBER;
BEGIN
      
    IF P_START_PRICE < 1000000 THEN
        -- 100만원 미만
        V_BID_UNIT := 1000;
        
    ELSIF P_START_PRICE < 10000000 THEN
        -- 100만원 이상 ~ 1,000만원 미만
        V_BID_UNIT := 10000;
        
    ELSE
        -- 1,000만원 이상
        V_BID_UNIT := 100000;
        
    END IF;

    RETURN V_BID_UNIT;
END;
/

-- ○ 4. 경매 입찰 상한가 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_BID_MAX_LIMIT
(
    P_AUCTION_ID IN NUMBER
)
RETURN NUMBER
IS
    V_CURRENT_PRICE NUMBER;
BEGIN
    -- 현재가 조회 (2순위 금액)
    V_CURRENT_PRICE := FN_GET_AUCTION_CURRENT_PRICE(P_AUCTION_ID);

    -- 현재가의 2배
    RETURN V_CURRENT_PRICE * 2;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
    WHEN OTHERS THEN
        RAISE;
END;
/

-- ○ 5. 경매 최초 입찰 여부 확인 함수
CREATE OR REPLACE FUNCTION FN_IS_FIRST_BIDDER
(
    P_AUCTION_ID IN NUMBER
)
RETURN CHAR 
IS
    V_COUNT NUMBER;
    V_RESULT CHAR(1);
BEGIN
    -- 입찰 참여 테이블에서 해당 경매의 입찰 기록 개수를 카운트
    SELECT COUNT(*) INTO V_COUNT
    FROM AUCTION_BID_PARTICIPATION
    WHERE AUCTION_ID = P_AUCTION_ID;

    -- 0이면 최초 입찰(Y), 0보다 크면 입찰 기록 있음(N)
    IF V_COUNT = 0 THEN
        V_RESULT := 'Y';
    ELSE
        V_RESULT := 'N';
    END IF;

    RETURN V_RESULT;

EXCEPTION
    WHEN OTHERS THEN
        RETURN 'N'; -- 에러 발생 시 입찰취소로 예외 처리
END;
/

-- ○ 6. 회원 진행중 입찰 건수 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_ACTIVE_BID_COUNT
(
    P_USER_ID IN NUMBER
)
RETURN NUMBER
IS
    V_COUNT NUMBER;
BEGIN
    -- 1. 내가 입찰한 모든 기록 중에서
    -- 2. 그 경매가 '진행 중(0)'인 것만 개수를 셉니다.
    SELECT COUNT(*) INTO V_COUNT
    FROM AUCTION_BID_PARTICIPATION
    WHERE USER_ID = P_USER_ID
    AND FN_IS_AUCTION_FINISHED(AUCTION_ID) = 0; -- 0이면 경매 진행중

    RETURN V_COUNT;

EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END;
/

-- ○ 7. 회원 패널티 누적 점수 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_USER_PENALTY_SCORE (
    P_USER_ID NUMBER
) 
RETURN NUMBER
IS
    -- 총 점수 0으로 초기화
    V_TOTAL_SCORE       NUMBER := 0;            -- 총 패널티 누적 점수
    ERR_UNKNOWN         CONSTANT NUMBER := -20009;
    
BEGIN

    -- 전체 누적 점수에서 취소된 점수를 뺀 값을 계산
    SELECT (
        (SELECT NVL(SUM(PENALTY_SCORE), 0) 
         FROM PENALTY_HISTORY 
         WHERE USER_ID = P_USER_ID) 
        - 
        (SELECT NVL(SUM(PH.PENALTY_SCORE), 0) 
         FROM PENALTY_CANCEL PC 
         JOIN PENALTY_HISTORY PH ON PC.PENALTY_ID = PH.PENALTY_ID 
         WHERE PH.USER_ID = P_USER_ID)
    ) INTO V_TOTAL_SCORE
    FROM DUAL;

    -- 패널티 누적 점수 반환
    RETURN V_TOTAL_SCORE;
EXCEPTION
     WHEN OTHERS THEN
        RETURN 0;
        
        IF SQLCODE BETWEEN -20999 AND -20000 THEN
            RAISE; -- 이미 정의된 커스텀 에러는 그대로 통과
        ELSE
            RAISE_APPLICATION_ERROR(ERR_UNKNOWN, '예상치 못한 오류가 발생했습니다');
        END IF; 
END;
/

-- ○ 8. 회원 패널티 활성 상태 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_USER_PENALTY_STATUS (
    P_USER_ID NUMBER
)
RETURN NUMBER
IS
    V_STATUS    NUMBER;        -- 0이면 활성, 1이면 비활성
    ERR_UNKNOWN  CONSTANT NUMBER := -20009;

BEGIN
    IF FN_GET_USER_PENALTY_SCORE(P_USER_ID) > 0
    THEN V_STATUS := 0;
    ELSE
        V_STATUS := 1;
    END IF;
    
    RETURN V_STATUS;
EXCEPTION

     WHEN OTHERS THEN     
        IF SQLCODE BETWEEN -20999 AND -20000 THEN
            RAISE; -- 이미 정의된 커스텀 에러는 그대로 통과
        ELSE
            RAISE_APPLICATION_ERROR(ERR_UNKNOWN, '예상치 못한 오류가 발생했습니다');
        END IF; 
END;
/


-- ○ 9. 낙찰 입찰코드 조회 함수




-- ○ 10. 경매 마감여부 확인 함수
CREATE OR REPLACE FUNCTION FN_IS_AUCTION_FINISHED
(P_AUCTION_ID   IN AUCTION_REGISTRATION.AUCTION_ID%TYPE
)
RETURN NUMBER
IS
    V_START_DATE    DATE;
    V_AUCTION_PERIOD NUMBER;
    V_RESULT NUMBER;
BEGIN
    -- 경매 테이블에서 등록시간과 경매기간 조회
    SELECT AR.CREATED_AT, TO_NUMBER(REGEXP_REPLACE(AP.AUCTION_PERIOD_NAME, '[^0-9]', '')) 
            INTO V_START_DATE, V_AUCTION_PERIOD
    FROM AUCTION_REGISTRATION AR 
        JOIN AUCTION_PERIOD AP
        ON AP.AUCTION_PERIOD_ID = AR.AUCTION_PERIOD_ID
    WHERE AR.AUCTION_ID = P_AUCTION_ID;
    
    IF (SYSDATE < (V_START_DATE+V_AUCTION_PERIOD)) THEN
        RETURN 0;   -- 경매 중
    ELSE
        RETURN 1;   -- 경매 종료
    END IF;
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN -1; --(경매 정보가 없는 경우에 대한 예외 처리)
        WHEN OTHERS THEN
            RETURN -1;
END;
/

-- ○ 11. 경매 마감일자  확인 함수
CREATE OR REPLACE FUNCTION FN_GET_AUCTION_DUE_DATE
(P_AUCTION_ID   IN AUCTION_REGISTRATION.AUCTION_ID%TYPE
)
RETURN VARCHAR2
IS
    V_START_DATE    DATE;
    V_AUCTION_PERIOD NUMBER;
BEGIN
    -- 경매 테이블에서 등록시간과 경매기간 조회
    SELECT AR.CREATED_AT, TO_NUMBER(REGEXP_REPLACE(AP.AUCTION_PERIOD_NAME, '[^0-9]', '')) 
            INTO V_START_DATE, V_AUCTION_PERIOD
    FROM AUCTION_REGISTRATION AR 
        JOIN AUCTION_PERIOD AP
        ON AP.AUCTION_PERIOD_ID = AR.AUCTION_PERIOD_ID
    WHERE AR.AUCTION_ID = P_AUCTION_ID;
    
    
    RETURN TO_CHAR(V_START_DATE+V_AUCTION_PERIOD, 'YYYY-MM-DD HH24:MI');

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN '-'; 
        WHEN OTHERS THEN
            RETURN '-';
END;
/




-- 트리거 ========================================================================
-- ○ 1. 패널티 부여 후 상태 반영 트리거
CREATE OR REPLACE TRIGGER TRG_PENALTY_AFTER_INS
	AFTER INSERT ON PENALTY_HISTORY
	FOR EACH ROW
DECLARE
    V_TOTAL_PENALTY_SCORE       PENALTY_HISTORY.PENALTY_SCORE%TYPE;
    V_PENALTY_END_DATE          PENALTY_STATUS.PENALTY_END_DATE%TYPE;
BEGIN
    -- 패널티 점수를 받은 유저의 현재 총점 확인
    SELECT SUM(PH.PENALTY_SCORE) INTO V_TOTAL_PENALTY_SCORE
    FROM PENALTY_HISTORY PH LEFT OUTER JOIN PENALTY_CANCEL PC
         ON PH.PENALTY_ID = PC.PENALTY_ID
    WHERE PH.USER_ID = :NEW.USER_ID
      AND PENALTY_CANCEL_ID IS NULL;
    
    
    -- 패널티 점수가 일정치 이상(1점 초과)이면 제재 발생
    IF V_TOTAL_PENALTY_SCORE > 1 THEN
        CASE
            -- 4점 이상: 영구 정지
            WHEN V_TOTAL_PENALTY_SCORE >= 4
            THEN V_PENALTY_END_DATE := TO_DATE('9999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS');

            -- 3점 이상: 30일 정지
            -- 오늘을 기준으로 30일 뒤 23시59분59초까지 계정 정지
            WHEN V_TOTAL_PENALTY_SCORE >= 3
            THEN V_PENALTY_END_DATE := TRUNC(SYSDATE + 30) + (1 - 1/86400);

            -- 그 외(2점 이상): 7일 정지
            -- 오늘을 기준으로 7일 뒤 23시59분59초까지 계정 정지
            ELSE V_PENALTY_END_DATE := TRUNC(SYSDATE + 7) + (1 - 1/86400);
        END CASE;

        INSERT INTO PENALTY_STATUS (PENALTY_STATUS_ID, PENALTY_ID, PENALTY_START_DATE, PENALTY_END_DATE)
        VALUES (PENALTY_STATUS_SEQ.NEXTVAL, :NEW.PENALTY_ID, SYSDATE, V_PENALTY_END_DATE);
    END IF;
END;
/

-- ○ 2. 패널티 취소 후 상태 재계산 트리거
CREATE OR REPLACE TRIGGER TRG_PENALTY_CANCEL_AFTER_INS
	AFTER INSERT ON PENALTY_CANCEL
	FOR EACH ROW
DECLARE
BEGIN
    -- 패널티 취소로 상태(계정 정지)에 변경이 발생했다면,
    -- 해당 패널티에 연관된 패널티 상태 레코드 삭제
    -- (별도의 상태 분류가 가능한 컬럼이나 테이블이 없어 삭제로 처리)
    DELETE
    FROM PENALTY_STATUS
    WHERE PENALTY_ID = :NEW.PENALTY_ID;
END;
/

-- 스케줄러 ======================================================================

-- 낙찰 결제 기한 확인 스케줄러
BEGIN
    DBMS_SCHEDULER.CREATE_JOB
    (
    JOB_NAME => 'SCH_AUCTION_CLOSE'
    ,JOB_TYPE => 'STORED_PROCEDURE'
    ,JOB_ACTION => 'REC_AUCTION_CLOSE'
    ,REPEAT_INTERVAL => 'FREQ=MINUTELY'
    ,ENABLED => FALSE
    );
END;
/

-- 구매 확정 자동 처리 스케줄러
BEGIN
    DBMS_SCHEDULER.CREATE_JOB
    (
        JOB_NAME => 'SCH_AUTO_PURCHASE_CONFIRM'
        ,JOB_TYPE => 'STORED_PROCEDURE'
        ,JOB_ACTION => 'PRC_AUTO_PURCHASE_CONFIRM'
        ,REPEAT_INTERVAL => 'FREQ=MINUTELY'
        ,ENABLED => FALSE
    );
END;
/
-- 탈퇴 회원 정리 스케줄러
BEGIN
    DBMS_SCHEDULER.CREATE_JOB
    (
        JOB_NAME => 'SCH_DELETED_USER_CLEANUP'
        ,JOB_TYPE => 'STORED_PROCEDURE'
        ,JOB_ACTION => 'PRC_DELETED_USER_CLEANUP' 
        ,REPEAT_INTERVAL => 'FREQ=DAILY; BYHOUR=0'
        ,ENABLED => FALSE
    );
END;
/

