
-- 뷰 ===========================================================================

-- ○ 1. 회원 통합 정보 조회 뷰
CREATE OR REPLACE VIEW VW_USER_INFO
AS
SELECT U.USER_ID, UA.USER_LOGIN_ID, UA.USER_PASSWORD
, UP.USER_NAME, UP.USER_SSN, UP.USER_EMAIL, UP.USER_PHONE
, UP.USER_ZIPCODE, UP.USER_ADDRESS, UP.USER_ADDRESS_DETAIL
, FN_GET_USER_MONEY_BALANCE(U.USER_ID) AS TOTAL_MONEY
FROM USERS U JOIN USER_ACCOUNT UA
ON U.USER_ID = UA.USER_ID
JOIN USER_PROFILE UP
ON UA.USER_ID = UP.USER_ID;


-- ○ 2. 상품 통합 조회 뷰
CREATE OR REPLACE VIEW VW_PRODUCT_LIST
AS
SELECT 
    P.PRODUCT_ID, P.USER_ID, P.MANUFACTURER_ID, PM.MANUFACTURER_NAME, PM.PRODUCT_COUNTRY_ID, PC.PRODUCT_COUNTRY_NAME
    , P.PRODUCT_GRADE_ID, PG.PRODUCT_GRADE_NAME, P.PRODUCT_GENRE_ID, PGR.PRODUCT_GENRE_NAME, P.PRODUCT_SIZE_ID, PS.PRODUCT_SIZE_NAME
    , P.PRODUCT_RELEASE_NAME, P.PRODUCT_ALIAS, P.WORK_NAME, P.CHARACTER_NAME, P.PURCHASE_DATETIME
    ,CASE WHEN P.IS_OPENED = 0 THEN '개봉' ELSE '미개봉' END AS IS_OPENED
    ,CASE WHEN P.IS_PARTS_MISSING = 0 THEN '정상' ELSE '누락' END AS IS_PARTS_MISSING
    ,P.DESCRIPTIONS
    ,P.IMAGE_PATH_1
    ,P.IMAGE_PATH_2
    ,P.IMAGE_PATH_3
    ,MAX(DECODE(PI.IMAGE_ORDER, 1, PI.FILE_PATH)) AS IMAGE_PATH_4
    ,MAX(DECODE(PI.IMAGE_ORDER, 2, PI.FILE_PATH)) AS IMAGE_PATH_5
    ,MAX(DECODE(PI.IMAGE_ORDER, 3, PI.FILE_PATH)) AS IMAGE_PATH_6
    ,MAX(DECODE(PI.IMAGE_ORDER, 4, PI.FILE_PATH)) AS IMAGE_PATH_7
    ,MAX(DECODE(PI.IMAGE_ORDER, 5, PI.FILE_PATH)) AS IMAGE_PATH_8
    ,MAX(DECODE(PI.IMAGE_ORDER, 6, PI.FILE_PATH)) AS IMAGE_PATH_9
    ,MAX(DECODE(PI.IMAGE_ORDER, 7, PI.FILE_PATH)) AS IMAGE_PATH_10
    ,CASE WHEN P.IS_PUBLIC = 0 THEN '비공개' ELSE '공개' END AS IS_PUBLIC
    ,TO_CHAR(P.CREATED_AT, 'YYYY-MM-DD') AS CREATED_AT
FROM PRODUCT P
    JOIN PRODUCT_MANUFACTURER PM ON P.MANUFACTURER_ID = PM.MANUFACTURER_ID
    JOIN PRODUCT_COUNTRY PC      ON PM.PRODUCT_COUNTRY_ID = PC.PRODUCT_COUNTRY_ID
    JOIN PRODUCT_GRADE PG        ON P.PRODUCT_GRADE_ID = PG.PRODUCT_GRADE_ID
    JOIN PRODUCT_GENRE PGR       ON P.PRODUCT_GENRE_ID = PGR.PRODUCT_GENRE_ID
    JOIN PRODUCT_SIZE PS         ON P.PRODUCT_SIZE_ID = PS.PRODUCT_SIZE_ID
    LEFT JOIN PRODUCT_IMAGE PI   ON P.PRODUCT_ID = PI.PRODUCT_ID
GROUP BY 
    P.PRODUCT_ID, P.USER_ID,
    P.MANUFACTURER_ID, PM.MANUFACTURER_NAME, PM.PRODUCT_COUNTRY_ID, PC.PRODUCT_COUNTRY_NAME, 
    P.PRODUCT_GRADE_ID, PG.PRODUCT_GRADE_NAME,
    P.PRODUCT_GENRE_ID, PGR.PRODUCT_GENRE_NAME, 
    P.PRODUCT_SIZE_ID, PS.PRODUCT_SIZE_NAME, 
    P.PRODUCT_RELEASE_NAME, P.PRODUCT_ALIAS, P.WORK_NAME, P.CHARACTER_NAME,
    P.PURCHASE_DATETIME, P.IS_OPENED, P.IS_PARTS_MISSING, P.DESCRIPTIONS,
    P.IMAGE_PATH_1, P.IMAGE_PATH_2, P.IMAGE_PATH_3, P.IS_PUBLIC, P.CREATED_AT;


-- ○ 3. 경매 통합 조회 뷰
CREATE OR REPLACE VIEW VW_AUCTION_LIST
AS
WITH BID_RANK AS (
    SELECT 
        AUCTION_ID, BID_PRICE,
        ROW_NUMBER() OVER (PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS RK
    FROM AUCTION_BID_PARTICIPATION
)
SELECT 
    AR.AUCTION_ID, AR.AUCTION_TITLE, AR.AUCTION_CONTENT, AR.START_PRICE,
    AR.AUCTION_PERIOD_ID, AP.AUCTION_PERIOD_NAME,
    TO_CHAR(AR.CREATED_AT, 'YYYY-MM-DD HH24:MI') AS AUCTION_START_DATE,
    FN_GET_AUCTION_DUE_DATE(AR.AUCTION_ID) AS AUCTION_END_DATE,
    CASE WHEN FN_IS_AUCTION_FINISHED(AR.AUCTION_ID) = 0 THEN '진행중'
         ELSE '마감' 
    END AS IS_FINISHED,
    VPI.PRODUCT_ID, VPI.PRODUCT_RELEASE_NAME, VPI.PRODUCT_ALIAS,
    VPI.MANUFACTURER_NAME, VPI.PRODUCT_GRADE_NAME, VPI.IMAGE_PATH_1,
    NVL((SELECT BID_PRICE FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 2), AR.START_PRICE) AS BID_CURRENT_PRICE,
    (SELECT BID_PRICE FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 1) AS BID_MAX_PRICE,
    (SELECT COUNT(*) FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID) AS BID_COUNT
FROM AUCTION_REGISTRATION AR
JOIN VW_PRODUCT_LIST VPI ON AR.PRODUCT_ID = VPI.PRODUCT_ID
JOIN AUCTION_PERIOD AP   ON AR.AUCTION_PERIOD_ID = AP.AUCTION_PERIOD_ID;


-- ○ 4. 입찰 통합 조회 뷰
CREATE OR REPLACE VIEW VW_BID_LIST
AS
WITH BID_RANKING AS (
    -- 모든 입찰 기록에 대해 실시간 순위를 매김
    SELECT 
        BID_ID, AUCTION_ID, USER_ID, BID_PRICE, BID_TIME,
        ROW_NUMBER() OVER (PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS RK
    FROM AUCTION_BID_PARTICIPATION
)
SELECT 
    BR.BID_ID, BR.BID_PRICE,
    TO_CHAR(BR.BID_TIME, 'YYYY-MM-DD HH24:MI:SS.FF3') AS BID_TIME,
    BR.RK AS BID_RANK,
    CASE WHEN BR.RK = 1 THEN '낙찰유력' 
         WHEN BR.RK >4 THEN '순위권'
        ELSE '입찰중' END AS BID_STATUS,
    BR.USER_ID AS BIDDER_ID, UP.USER_ID , UA.USER_LOGIN_ID,
    AR.AUCTION_ID, AR.AUCTION_TITLE, AR.START_PRICE,
    FN_GET_AUCTION_DUE_DATE(AR.AUCTION_ID) AS AUCTION_END_DATE,
    CASE WHEN FN_IS_AUCTION_FINISHED(AR.AUCTION_ID) = 0 THEN '진행중' ELSE '마감' END AS AUCTION_STATUS,
    VPL.PRODUCT_ID, VPL.PRODUCT_RELEASE_NAME, VPL.MANUFACTURER_NAME,
    NVL(
        (SELECT BID_PRICE FROM BID_RANKING WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 2),
        AR.START_PRICE
    ) AS CURRENT_PRICE
FROM BID_RANKING BR
JOIN AUCTION_REGISTRATION AR ON BR.AUCTION_ID = AR.AUCTION_ID
JOIN USER_PROFILE UP ON BR.USER_ID = UP.USER_ID
JOIN USER_ACCOUNT UA ON UP.USER_ID = UA.USER_ID
JOIN VW_PRODUCT_LIST VPL ON AR.PRODUCT_ID = VPL.PRODUCT_ID;


-- ○ 5. 경매 낙찰 결제 통합 조회 뷰


-- ○ 6. 패널티 통합 조회 뷰
CREATE OR REPLACE VIEW VW_PENALTY_LIST
AS
WITH RAW_HISTORY AS (
    SELECT 
        PH.USER_ID, PH.PENALTY_ID, PH.PENALTY_SCORE, PH.CREATED_AT,
        SUM(CASE WHEN PC.PENALTY_ID IS NULL THEN PH.PENALTY_SCORE ELSE 0 END) 
            OVER (PARTITION BY PH.USER_ID ORDER BY PH.CREATED_AT ASC) AS ACCUMULATED_SCORE,
        PC.PENALTY_ID AS CANCEL_ID, PC.CANCEL_REASON
    FROM PENALTY_HISTORY PH
    LEFT JOIN PENALTY_CANCEL PC ON PH.PENALTY_ID = PC.PENALTY_ID
)
SELECT 
    RH.USER_ID, RH.PENALTY_ID, RH.PENALTY_SCORE AS GIVEN_SCORE,
    RH.ACCUMULATED_SCORE AS ACCUMULATED_SCORE,
    FN_GET_USER_PENALTY_SCORE(RH.USER_ID) AS TOTAL_SCORE,
    CASE 
        WHEN RH.CANCEL_ID IS NOT NULL THEN '취소'
        WHEN RH.ACCUMULATED_SCORE = 1 THEN '경고'
        WHEN RH.ACCUMULATED_SCORE = 2 THEN '7일 정지'
        WHEN RH.ACCUMULATED_SCORE = 3 THEN '30일 정지'
        WHEN RH.ACCUMULATED_SCORE >= 4 THEN '영구 정지'
        ELSE '정상'
    END AS PENALTY_STATUS,
    TO_CHAR(PS.PENALTY_START_DATE, 'YYYY-MM-DD HH24:MI') AS START_DATE,
    TO_CHAR(PS.PENALTY_END_DATE, 'YYYY-MM-DD HH24:MI') AS END_DATE,
    CASE 
        WHEN RH.CANCEL_ID IS NOT NULL THEN '취소완료'
        WHEN PS.PENALTY_END_DATE < SYSDATE THEN '기간만료'
        ELSE '제재 중'
    END AS HISTORY_STATUS
FROM RAW_HISTORY RH
LEFT JOIN PENALTY_STATUS PS ON RH.PENALTY_ID = PS.PENALTY_ID;

-- ○ 7. 신고 통합 조회 뷰


-- ○ 8. 경매 입찰 현재 순위 조회 뷰
CREATE OR REPLACE VIEW VW_AUCTION_BID_RANK
AS
SELECT 
    AUCTION_ID, USER_ID, BID_PRICE, 
    TO_CHAR(BID_TIME, 'YYYY-MM-DD HH24:MI:SS.FF3') AS BID_TIME,
    ROW_NUMBER() OVER (PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS CURRENT_RANK,
    COUNT(*) OVER (PARTITION BY AUCTION_ID) AS TOTAL_BIDDERS
FROM AUCTION_BID_PARTICIPATION;

-- ○ 9. 미결제 낙찰 대상 조회 뷰


-- ○ 10. 경매 마감 임박 순서 뷰
CREATE OR REPLACE VIEW VW_AUCTION_URGENT_LIST
AS
SELECT VA.AUCTION_ID, VA.AUCTION_TITLE, VA.IMAGE_PATH_1, VA.BID_CURRENT_PRICE, UA.USER_LOGIN_ID, VA.AUCTION_END_DATE
   , ROW_NUMBER() OVER(ORDER BY VA.AUCTION_END_DATE DESC) AS RK
FROM VW_AUCTION_LIST VA 
    JOIN PRODUCT P ON VA.PRODUCT_ID = P.PRODUCT_ID
    JOIN USER_ACCOUNT UA ON P.USER_ID = UA.USER_ID
WHERE TO_DATE(AUCTION_END_DATE,'YYYY-MM-DD HH24:MI:SS') > SYSDATE;


-- ○ 11. 머니 거래 내역 조회 뷰
CREATE OR REPLACE VIEW VW_MONEY_HISTORY
AS
SELECT 
    USER_ID,
    '충전' AS TRANSACTION_TYPE, 
    CHARGE_AMOUNT AS AMOUNT,     
    TO_CHAR(CHARGED_AT, 'YYYY-MM-DD HH24:MI:SS') AS TRANSACTION_DATE,
    MCM.MONEY_CHARGE_METHOD_NAME AS DESCRIPTION 
FROM MONEY_CHARGE_HISTORY MCH
JOIN MONEY_CHARGE_METHOD MCM ON MCH.MONEY_CHARGE_METHOD_ID = MCM.MONEY_CHARGE_METHOD_ID
UNION ALL
SELECT 
    USER_ID,
    MT.MONEY_TYPE_NAME AS TRANSACTION_TYPE, 
    AMOUNT,                 
    TO_CHAR(CREATED_AT, 'YYYY-MM-DD HH24:MI:SS') AS TRANSACTION_DATE,
    MT.MONEY_TYPE_NAME AS DESCRIPTION     
FROM MONEY_TRANSACTION_HISTORY MTH
JOIN MONEY_TYPE MT ON MTH.MONEY_TYPE_ID = MT.MONEY_TYPE_ID;










