SELECT USER
FROM DUAL;


-- ============================================================
-- 21. 머니 충전 수단
-- ============================================================
CREATE TABLE MONEY_CHARGE_METHOD 
(
      MONEY_CHARGE_METHOD_CODE NUMBER
    , MONEY_CHARGE_METHOD_NAME VARCHAR2(50) NOT NULL
    , CONSTRAINT MONEY_CHARGE_METHOD_MONEY_CHARGE_METHOD_ID_PK PRIMARY KEY (MONEY_CHARGE_METHOD_CODE)
    , CONSTRAINT MONEY_CHARGE_METHOD_MONEY_CHARGE_METHOD_NAME_UK UNIQUE (MONEY_CHARGE_METHOD_NAME)
);

-- ============================================================
-- 22. 머니 충전 이력
-- ============================================================
CREATE TABLE MONEY_CHARGE_HISTORY 
(
      MONEY_CHARGE_ID          NUMBER
    , USER_ID                  NUMBER NOT NULL
    , MONEY_CHARGE_METHOD_CODE NUMBER NOT NULL
    , CHARGE_AMOUNT            NUMBER NOT NULL
    , CHARGED_AT               DATE   DEFAULT SYSDATE NOT NULL
    , CONSTRAINT MONEY_CHARGE_HISTORY_MONEY_CHARGE_ID_PK PRIMARY KEY (MONEY_CHARGE_ID)
    , CONSTRAINT MONEY_CHARGE_HISTORY_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID)
    , CONSTRAINT MONEY_CHARGE_HISTORY_MONEY_CHARGE_METHOD_CODE_FK FOREIGN KEY (MONEY_CHARGE_METHOD_CODE) REFERENCES MONEY_CHARGE_METHOD(MONEY_CHARGE_METHOD_CODE)
);

-- ============================================================
-- 24. 경매 기간
-- ============================================================
CREATE TABLE AUCTION_PERIOD 
(
      AUCTION_PERIOD_CODE NUMBER
    , AUCTION_PERIOD_NAME VARCHAR2(10) NOT NULL
    , CONSTRAINT AUCTION_PERIOD_AUCTION_PERIOD_CODE_PK PRIMARY KEY (AUCTION_PERIOD_CODE)
    , CONSTRAINT AUCTION_PERIOD_AUCTION_PERIOD_NAME_UK UNIQUE (AUCTION_PERIOD_NAME)
);

-- ============================================================
-- 25. 경매 등록
-- ============================================================
CREATE TABLE AUCTION_REGISTRATION 
(
      AUCTION_ID          NUMBER
    , PRODUCT_ID          NUMBER         NOT NULL
    , AUCTION_TITLE       VARCHAR2(300)  NOT NULL
    , AUCTION_CONTENT     VARCHAR2(2000) NOT NULL
    , START_PRICE         NUMBER(12)     NOT NULL
    , CREATED_AT          DATE           DEFAULT SYSDATE NOT NULL
    , AUCTION_PERIOD_CODE NUMBER
    , CONSTRAINT AUCTION_REGISTRATION_AUCTION_ID_PK PRIMARY KEY (AUCTION_ID)
    , CONSTRAINT AUCTION_REGISTRATION_PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
    , CONSTRAINT AUCTION_REGISTRATION_AUCTION_PERIOD_CODE_FK FOREIGN KEY (AUCTION_PERIOD_CODE) REFERENCES AUCTION_PERIOD(AUCTION_PERIOD_CODE)
    , CONSTRAINT AUCTION_REGI_START_PRICE_CK CHECK (START_PRICE > 0)
);

-- ============================================================
-- 23. 머니 입출금 이력  ← AUCTION_REGISTRATION 이후에 생성
-- ============================================================
CREATE TABLE MONEY_TRANSACTION_HISTORY 
(
      MONEY_ID        NUMBER
    , USER_ID         NUMBER      NOT NULL
    , MONEY_TYPE_CODE NUMBER      NOT NULL
    , AUCTION_ID      NUMBER      NOT NULL
    , AMOUNT          NUMBER(12)  NOT NULL
    , CREATED_AT      DATE        DEFAULT SYSDATE NOT NULL
    , CONSTRAINT MONEY_TRANSACTION_HISTORY_MONEY_ID_PK PRIMARY KEY (MONEY_ID)
    , CONSTRAINT MONEY_TRANSACTION_HISTORY_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID)
    , CONSTRAINT MONEY_TRANSACTION_HISTORY_MONEY_TYPE_CODE_FK FOREIGN KEY (MONEY_TYPE_CODE) REFERENCES MONEY_TYPE(MONEY_TYPE_CODE)
    , CONSTRAINT MONEY_TRANSACTION_HISTORY_AUCTION_ID_FK FOREIGN KEY (AUCTION_ID) REFERENCES AUCTION_REGISTRATION(AUCTION_ID)
);

-- ============================================================
-- 26. 경매 취소 이력
-- ============================================================
CREATE TABLE AUCTION_CANCEL_HISTORY 
(
      AUCTION_CANCEL_ID NUMBER
    , AUCTION_ID        NUMBER        NOT NULL
    , CANCEL_REASON     VARCHAR2(500) NOT NULL
    , CANCEL_AT         DATE          DEFAULT SYSDATE NOT NULL
    , CONSTRAINT AUCTION_CANCEL_HISTORY_AUCTION_CANCEL_ID_PK PRIMARY KEY (AUCTION_CANCEL_ID)
    , CONSTRAINT AUCTION_CANCEL_HISTORY_AUCTION_ID_FK FOREIGN KEY (AUCTION_ID) REFERENCES AUCTION_REGISTRATION(AUCTION_ID)
    , CONSTRAINT AUCTION_CANCEL_HISTORY_AUCTION_ID_UK UNIQUE (AUCTION_ID)
);

-- ============================================================
-- 27. 입찰 참여
-- ============================================================
CREATE TABLE AUCTION_BID_PARTICIPATION 
(
      BID_ID     NUMBER
    , AUCTION_ID NUMBER     NOT NULL
    , USER_ID    NUMBER     NOT NULL
    , BID_TIME   TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL
    , BID_PRICE  NUMBER(10) NOT NULL
    , CONSTRAINT AUCTION_BID_PARTICIPATION_BID_ID_PK PRIMARY KEY (BID_ID)
    , CONSTRAINT AUCTION_BID_PARTICIPATION_AUCTION_ID_FK FOREIGN KEY (AUCTION_ID) REFERENCES AUCTION_REGISTRATION(AUCTION_ID)
    , CONSTRAINT AUCTION_BID_PARTICIPATION_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID)
    , CONSTRAINT AUCTION_BID_PARTICIPATION_AUCTION_ID_USER_ID_BID_TIME_UK UNIQUE (AUCTION_ID, USER_ID, BID_TIME)
);

-- ============================================================
-- 28. 낙찰 결과
-- ============================================================
CREATE TABLE AUCTION_WINNING_RESULT 
(
      BID_RESULT_ID NUMBER
    , BID_ID        NUMBER NOT NULL
    , CREATED_AT    DATE   DEFAULT SYSDATE NOT NULL
    , CONSTRAINT AUCTION_WINNING_RESULT_BID_RESULT_ID_PK PRIMARY KEY (BID_RESULT_ID)
    , CONSTRAINT AUCTION_WINNING_RESULT_BID_ID_FK FOREIGN KEY (BID_ID) REFERENCES AUCTION_BID_PARTICIPATION(BID_ID)
    , CONSTRAINT AUCTION_WINNING_RESULT_BID_ID_UK UNIQUE (BID_ID)
);

-- ============================================================
-- 29. 낙찰 실패 유형
-- ============================================================
CREATE TABLE BID_FAILURE_TYPE 
(
      BID_FAIL_TYPE_CODE NUMBER
    , BID_FAIL_TYPE_NAME VARCHAR2(50) NOT NULL
    , CONSTRAINT BID_FAILURE_TYPE_BID_FAIL_TYPE_CODE_PK PRIMARY KEY (BID_FAIL_TYPE_CODE)
    , CONSTRAINT BID_FAILURE_TYPE_BID_FAIL_TYPE_NAME_UK UNIQUE (BID_FAIL_TYPE_NAME)
);

-- ============================================================
-- 30. 낙찰 실패 이력
-- ============================================================
CREATE TABLE BID_FAILURE_HISTORY 
(
      BID_FAIL_HISTORY_ID NUMBER
    , BID_RESULT_ID       NUMBER NOT NULL
    , BID_FAIL_TYPE_CODE  NUMBER NOT NULL
    , CREATED_AT          DATE   DEFAULT SYSDATE NOT NULL
    , CONSTRAINT BID_FAILURE_HISTORY_BID_FAIL_HISTORY_ID_PK PRIMARY KEY (BID_FAIL_HISTORY_ID)
    , CONSTRAINT BID_FAILURE_HISTORY_BID_RESULT_ID_FK FOREIGN KEY (BID_RESULT_ID) REFERENCES AUCTION_WINNING_RESULT(BID_RESULT_ID)
    , CONSTRAINT BID_FAILURE_HISTORY_BID_FAIL_TYPE_CODE_FK FOREIGN KEY (BID_FAIL_TYPE_CODE) REFERENCES BID_FAILURE_TYPE(BID_FAIL_TYPE_CODE)
    , CONSTRAINT BID_FAILURE_HISTORY_BID_RESULT_ID_UK UNIQUE (BID_RESULT_ID)
);

-- ============================================================
-- 31. 낙찰 입금
-- ============================================================
CREATE TABLE AUCTION_WINNING_PAYMENT 
(
      PAYMENT_ID    NUMBER
    , BID_RESULT_ID NUMBER NOT NULL
    , MONEY_ID      NUMBER NOT NULL
    , CREATED_AT    DATE   DEFAULT SYSDATE NOT NULL
    , CONSTRAINT AUCTION_WINNING_PAYMENT_PAYMENT_ID_PK PRIMARY KEY (PAYMENT_ID)
    , CONSTRAINT AUCTION_WINNING_PAYMENT_BID_RESULT_ID_FK FOREIGN KEY (BID_RESULT_ID) REFERENCES AUCTION_WINNING_RESULT(BID_RESULT_ID)
    , CONSTRAINT AUCTION_WINNING_PAYMENT_MONEY_ID_FK FOREIGN KEY (MONEY_ID) REFERENCES MONEY_TRANSACTION_HISTORY(MONEY_ID)
    , CONSTRAINT AUCTION_WINNING_PAYMENT_BID_RESULT_ID_UK UNIQUE (BID_RESULT_ID)
);

-- ============================================================
-- 32. 발송 완료
-- ============================================================
CREATE TABLE DELIVERY_COMPLETED 
(
      SHIPPING_ID NUMBER
    , PAYMENT_ID  NUMBER NOT NULL
    , CREATED_AT  DATE   DEFAULT SYSDATE NOT NULL
    , CONSTRAINT DELIVERY_COMPLETED_SHIPPING_ID_PK PRIMARY KEY (SHIPPING_ID)
    , CONSTRAINT DELIVERY_COMPLETED_PAYMENT_ID_FK FOREIGN KEY (PAYMENT_ID) REFERENCES AUCTION_WINNING_PAYMENT(PAYMENT_ID)
    , CONSTRAINT DELIVERY_COMPLETED_PAYMENT_ID_UK UNIQUE (PAYMENT_ID)
);