SELECT USER
FROM DUAL;


DESC VW_USER_INFO;

-- 회원 정보
SELECT USER_ID, USER_LOGIN_ID, USER_PASSWORD
,USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE
, USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL
, TOTAL_MONEY, CREATED_AT, DELETED_AT
FROM VW_USER_INFO
;


SELECT USER_ID, USER_LOGIN_ID, USER_PASSWORD
,USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE
, USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL
, TOTAL_MONEY, CREATED_AT, DELETED_AT
FROM VW_USER_INFO
WHERE USER_LOGIN_ID = ? AND USER_PASSWORD = ?
;


-- 이름과 이메일로 아이디 찾기

SELECT USER_LOGIN_ID
FROM VW_USER_INFO
WHERE USER_NAME = '홍길동' AND USER_EMAIL='hong@test.com'
;


	SELECT USER_PASSWORD
				FROM VW_USER_INFO
				WHERE USER_LOGIN_ID ='user01' AND USER_NAME = '홍길동' AND USER_EMAIL='hong@test.com';




SELECT *
FROM VW_USER_INFO;

SELECT COUNT(*) AS COUNT
FROM USER_ACCOUNT
WHERE USER_LOGIN_ID = ?
;


