SELECT USER
FROM DUAL;

-- ○ 1. 회원가입 생성 프로시저
-- 회원 가입 시 회원 고유키, 회원 계정, 회원 정보, 회원 계정이벤트 이력 등에 이력 추가
CREATE OR REPLACE PROCEDURE PRC_USER_SIGNUP
( P_USER_LOGIN_ID IN VARCHAR2
, P_USER_PASSWORD IN VARCHAR2
, P_USER_PASSWORD_CHECK IN VARCHAR2
, P_USER_NAME IN VARCHAR2
, P_USER_SSN IN CHAR
, P_USER_EMAIL IN VARCHAR2
, P_USER_PHONE IN CHAR
, P_USER_ZIPCODE IN VARCHAR2
, P_USER_ADDRESS IN VARCHAR2
, P_USER_ADDRESS_DETAIL IN VARCHAR2
)
IS
    V_HAS_ID NUMBER(1);
    V_HAS_SSN NUMBER(1);
    V_BIRTH DATE;
    V_AGE NUMBER(3);
    
    
    ERR_DUPLICATE_ID EXCEPTION;
    ERR_DUPLICATE_SSN EXCEPTION;
    ERR_INVALID_SSN EXCEPTION;
    ERR_INVALID_FORMAT_LENGTH EXCEPTION;
    ERR_UNDERAGE EXCEPTION;
    ERR_WRONG_PWD EXCEPTION;
    ERR_INVALID_EMAIL EXCEPTION;
    ERR_NULL_VALUE EXCEPTION;

BEGIN
-- NULL 검사
    IF (P_USER_LOGIN_ID IS NULL OR P_USER_PASSWORD IS NULL 
        OR P_USER_PASSWORD IS NULL OR P_USER_NAME IS NULL OR P_USER_SSN IS NULL
        OR P_USER_SSN IS NULL OR P_USER_EMAIL IS NULL OR P_USER_PHONE IS NULL
        OR P_USER_ZIPCODE IS NULL OR P_USER_ADDRESS IS NULL OR P_USER_ADDRESS_DETAIL IS NULL)   THEN
            RAISE ERR_NULL_VALUE;
    END IF;

-- 아이디 중복 검사
    SELECT COUNT(*) INTO V_HAS_ID
    FROM USER_ACCOUNT
    WHERE USER_LOGIN_ID = P_USER_LOGIN_ID;
    
    IF(V_HAS_ID != 0) THEN
        RAISE ERR_DUPLICATE_ID;
    END IF;
    
-- 아이디 조건 검사(4글자이상 12자이하)
    IF(LENGTH(P_USER_LOGIN_ID)<4 OR LENGTH(P_USER_LOGIN_ID)>12) THEN
        RAISE ERR_INVALID_FORMAT_LENGTH;
    END IF;

-- 비밀번호 조건 검사(8자이상 16자이하)
    IF(LENGTH(P_USER_PASSWORD)<8 OR LENGTH(P_USER_PASSWORD)>16) THEN
        RAISE ERR_INVALID_FORMAT_LENGTH;
    END IF;
    
-- 비밀번호 확인
    IF(P_USER_PASSWORD != P_USER_PASSWORD_CHECK) THEN
        RAISE ERR_WRONG_PWD;
    END IF;
    
-- 주민번호 유효성 검사
    IF NOT REGEXP_LIKE(P_USER_SSN, '^[0-9]{6}[1-4][0-9]{6}$') THEN
        RAISE ERR_INVALID_SSN;
    END IF;
    
-- 주민번호 중복 검사
    SELECT COUNT(*) INTO V_HAS_SSN
    FROM USER_PROFILE
    WHERE USER_SSN = P_USER_SSN;
    
    IF(V_HAS_SSN != 0) THEN
        RAISE ERR_DUPLICATE_SSN;
    END IF;

-- 주민번호 미성년자 제외 검사
    V_BIRTH := TO_DATE(
        CASE
            WHEN SUBSTR(P_USER_SSN,7,1) IN ('3','4') THEN '20'
            ELSE '19'
        END || SUBSTR(P_USER_SSN,1,6), 'YYYYMMDD'
    );

    V_AGE := TRUNC(MONTHS_BETWEEN(SYSDATE, V_BIRTH)/12);
    
    IF(V_AGE<19) THEN
        RAISE ERR_UNDERAGE;
    END IF;

-- 이메일 유효성 검사
    -- ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$
     IF NOT REGEXP_LIKE(P_USER_EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
        RAISE ERR_INVALID_EMAIL;
    END IF;

-- 1. USERS INSERT
    INSERT INTO USERS VALUES(USERS_SEQ.NEXTVAL);
    
-- 2. USER_ACCOUNT INSERT
    INSERT INTO USER_ACCOUNT
    VALUES(USERS_SEQ.CURRVAL, P_USER_LOGIN_ID, P_USER_PASSWORD);

-- 3. USER_PROFILE INSERT
    INSERT INTO USER_PROFILE
    VALUES(USERS_SEQ.CURRVAL, P_USER_NAME, P_USER_SSN, P_USER_EMAIL, P_USER_PHONE
    , P_USER_ZIPCODE, P_USER_ADDRESS, P_USER_ADDRESS_DETAIL);
    

      
-- 4. ACCOUNT_EVENT_HISTORY INSERT
    INSERT INTO ACCOUNT_EVENT_HISTORY
    VALUES(ACCOUNT_EVENT_HISTORY_SEQ.NEXTVAL, USERS_SEQ.CURRVAL, 1, SYSDATE);

-- 예외 처리
    EXCEPTION 
        WHEN ERR_DUPLICATE_ID THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20001, '이미 존재하는 아이디입니다.');
        WHEN ERR_DUPLICATE_SSN THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20002, '이미 존재하는 주민등록번호입니다.');
        WHEN ERR_INVALID_SSN THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20003, '유효하지 않은 주민등록번호입니다.');   
        WHEN ERR_INVALID_FORMAT_LENGTH THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20005, '입력 범위가 맞지 않습니다.');
        WHEN ERR_UNDERAGE THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20006, '미성년자입니다.'); 
        WHEN ERR_WRONG_PWD THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20007, '비밀번호가 일치하지 않습니다.'); 
        WHEN ERR_INVALID_EMAIL THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20008, '올바른 이메일 형식이 아닙니다.');
        WHEN ERR_NULL_VALUE THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20014, '필수 입력 항목이 누락되었습니다.');
END;
/
-- Procedure PRC_USER_SIGNUP이(가) 컴파일되었습니다.





-- ○ 3. 특정 경매코드에 대해 현재 마감기한이 지났는지 확인하는 함수
--      진행중: 0, 마감: 1, 에러: -1
CREATE OR REPLACE FUNCTION FN_IS_AUCTION_FINISHED
(P_AUCTION_ID   IN AUCTION_REGISTRATION.AUCTION_ID%TYPE
)
RETURN NUMBER
IS
    V_START_DATE    DATE;
    V_AUCTION_PERIOD NUMBER;
    V_RESULT NUMBER;
BEGIN
    -- 경매 테이블에서 등록시간과 경매기간 조회
    SELECT AR.CREATED_AT, TO_NUMBER(REGEXP_REPLACE(AP.AUCTION_PERIOD_NAME, '[^0-9]', '')) 
            INTO V_START_DATE, V_AUCTION_PERIOD
    FROM AUCTION_REGISTRATION AR 
        JOIN AUCTION_PERIOD AP
        ON AP.AUCTION_PERIOD_ID = AR.AUCTION_PERIOD_ID
    WHERE AR.AUCTION_ID = P_AUCTION_ID;
    
    IF SYSDATE < (V_START_DATE+V_AUCTION_PERIOD) THEN
        RETURN 0;   -- 경매 중
    ELSE
        RETURN 1;   -- 경매 종료
    END IF;
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN -1; --(경매 정보가 없는 경우에 대한 예외 처리)
        WHEN OTHERS THEN
            RETURN -1;
END;
/
--Function FN_IS_AUCTION_FINISHED이(가) 컴파일되었습니다.



-- ○ 4. 회원 잔여 머니 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_USER_MONEY_BALANCE
(P_USER_ID IN USERS.USER_ID%TYPE
)
RETURN NUMBER
IS
    V_MONEY1    NUMBER;
    V_MONEY2    NUMBER;
BEGIN

-- 머니입출금이력테이블에서 아이디로 조회해서 금액 계산한 값 +
-- 머니 충전 이력 테이블에서 아이디로 조회해서 금액 계산한 값

    SELECT NVL(SUM(AMOUNT), 0) INTO V_MONEY1
    FROM MONEY_TRANSACTION_HISTORY
    WHERE USER_ID = P_USER_ID;
    
    SELECT NVL(SUM(CHARGE_AMOUNT),0) INTO V_MONEY2
    FROM MONEY_CHARGE_HISTORY
    WHERE USER_ID = P_USER_ID;
    
    RETURN V_MONEY1+V_MONEY2;
    
    EXCEPTION 
        WHEN OTHERS THEN
            RETURN -1;
END;
--Function FN_GET_USER_MONEY_BALANCE이(가) 컴파일되었습니다.







-- ○ 2. 회원탈퇴 프로시저
-- 회원 탈퇴 클릭 시, 회원 상세 정보 테이블에 있는 정보를 회원 탈퇴 테이블에 INSERT, 회원 계정 이벤트 이력에 INSERT
-- 진행 중인 경매가 있는지 확인, 진행 중인 입찰이 있는지 확인, 진행중인 낙찰이 있는지 확인, 잔여머니가 있는지 확인
-- 
CREATE OR REPLACE PROCEDURE PRC_USER_DELETE
( P_USER_ID IN USERS.USER_ID%TYPE
)
IS
     -- 커서 정의 (경매테이블)
     CURSOR CUR_USER_AUCTION IS
            SELECT AR.AUCTION_ID
            FROM AUCTION_REGISTRATION AR
                JOIN PRODUCT P 
            ON AR.PRODUCT_ID = P.PRODUCT_ID
            WHERE P.USER_ID = P_USER_ID;
            
    CURSOR CUR_USER_BID IS
        SELECT AR.AUCTION_ID
        FROM AUCTION_REGISTRATION AR
            JOIN AUCTION_BID_PARTICIPATION ABP
            ON ABP.AUCTION_ID = AR.AUCTION_ID
        WHERE ABP.USER_ID = P_USER_ID;
        
    CURSOR CUR_USER_WINNING IS
        SELECT AWR.BID_RESULT_ID
        FROM AUCTION_WINNING_REULT AWR
            JOIN AUCTION_BID_PARTICIPATION ABP
            ON AWR.BID_ID = ABR.BID_ID
        WHERE ABP.USER_ID = P_USER_ID;
    
    V_AUCTION_ID AUCTION_REGISTRATION.AUCTION_ID%TYPE;
    V_BID_RESULT_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE;
    V_HAS_BID NUMBER;
    V_HAS_BID_2 NUMBER;
    
    ERR_HAS_ACTIVE_AUCTION EXCEPTION;
    ERR_HAS_ACTIVE_BID EXCEPTION;
    ERR_HAS_ACTIVE_WINNING EXCEPTION;
    
BEGIN
    -- 진행 중인 경매 검사
    
        OPEN CUR_USER_AUCTION;
        LOOP
            FETCH CUR_USER_AUCTION INTO V_AUCTION_ID;
            EXIT WHEN CUR_USER_AUCTION%NOTFOUND;
            
            IF(FN_IS_AUCTION_FINISHED(V_AUCTION_ID) = 0) THEN
                CLOSE CUR_USER_AUCTION;
                RAISE ERR_HAS_ACTIVE_AUCTION;
            END IF;
        END LOOP;
        CLOSE CUR_USER_AUCTION;
        
    -- 진행 중인 입찰 검사
        -- 입찰 참여 테이블에서 USER_ID로 조회해서 나온 경매코드들로
        -- 그 경매코드가 진행중인지 검사
        
        OPEN CUR_USER_BID;
        LOOP
            FETCH CUR_USER_BID INTO V_AUCTION_ID;
            EXIT WHEN CUR_USER_BID%NOTFOUND;
            
            IF(FN_IS_AUCTION_FINISHED(V_AUCTION_ID) = 0) THEN
                CLOSE CUR_USER_BID;
                RAISE ERR_HAS_ACTIVE_BID;
            END IF;
        END LOOP;
         CLOSE CUR_USER_AUCTION;
        
    -- 진행 중인 낙찰이 있는지
        -- 아이디를 들고 입찰테이블에서 입찰코드를 받아서 낙찰 결과테이블에서 
        -- 낙찰 코드를 받음 그 낙찰 코드가 낙찰 실패 이력이나 거래완료 테이블에 없으면
        -- 진행중인 낙찰
        
        OPEN CUR_USER_WINNING;
        LOOP
            FETCH CUR_USER_WINNING INTO V_BID_RESULT_ID;
            EXIT WHEN CUR_USER_WINNING%NOTFOUND;
            
            SELECT COUNT(*) INTO V_HAS_BID
            FROM BID_FAILURE_HISTORY
            WHERE BID_RESULT_ID = V_BID_RESULT_ID;
            
            SELECT COUNT(*) INTO V_HAS_BID_2
            FROM AUCTION_WINNING_PAYMENT AWP
                JOIN DELIVERY_COMPLETED DC
                ON AWP.PAYMENT_ID = DC.PAYMENT_ID
                JOIN PURCHASE_CONFIRM_HISTORY PCH
                ON DC.SHIPPING_ID = PCH.SHIPPING_ID
                JOIN TRANSACTION_COMPLETED TC
                ON PCH.PURCHASE_CONFIRM_ID = TC.PURCHASE_CONFIRM_ID
            WHERE AWP.BID_RESULT_ID = V_BID_RESULT_ID;
            
            IF(V_HAS_BID=0 OR V_HAS_BID_2=0)THEN
                CLOSE CUR_USER_WINNING;
                RAISE ERR_HAS_ACTIVE_WINNING;
            END IF;
        END LOOP;
        CLOSE CUR_USER_WINNING;
        
    -- 잔여머니가 있는지
    
        -- 함수 이용 여기부터
    
    -- 회원의 상태가 영구정지 상태인지
    
    -- USER_PROFILE 조회
    -- DELETED_USER INSERT
    -- USER_PROFILE DELETE
    -- ACCOUNT_EVENT_HISTORY INSERT
    
    EXCEPTION
        WHEN ERR_HAS_ACTIVE_AUCTION THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20016, '진행 중인 경매가 존재합니다.');
        WHEN ERR_HAS_ACTIVE_BID THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20026, '진행 중인 입찰이 존재합니다.');
        WHEN ERR_HAS_ACTIVE_WINNING THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20027, '진행 중인 낙찰이 존재합니다.');
    
END;
/



