SELECT USER
FROM DUAL;

-- 테이블 생성
-- ○ 1. 회원 고유키 USER
CREATE TABLE USERS
( USER_ID   NUMBER  NOT NULL
, CONSTRAINT USER_USER_ID_PK PRIMARY KEY (USER_ID)
);


-- ○ 2. 회원 계정
CREATE TABLE USER_ACCOUNT
( USER_ID   NUMBER  NOT NULL
, USER_LOGIN_ID VARCHAR2(50) NOT NULL
, USER_PASSWORD VARCHAR2(100)   NOT NULL
, CONSTRAINT USER_ACCOUNT_USER_ID_PK PRIMARY KEY (USER_ID)
, CONSTRAINT USER_ACCOUNT_USER_ID_FK FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
, CONSTRAINT USER_ACCOUNT_ID_UK UNIQUE (USER_LOGIN_ID)
, CONSTRAINT USER_ACCOUNT_ID_CK CHECK (LENGTH(USER_LOGIN_ID) BETWEEN 4 AND 12)
, CONSTRAINT USER_ACCOUNT_PW_CK CHECK (LENGTH(USER_PASSWORD) BETWEEN 8 AND 16)
);


-- ○ 3. 회원 정보
CREATE TABLE USER_PROFILE
( USER_ID   NUMBER  NOT NULL    
, USER_NAME VARCHAR2(50)    NOT NULL
, USER_SSN  CHAR(13)    NOT NULL
, USER_EMAIL VARCHAR2(100)  NOT NULL
, USER_PHONE CHAR(11)   NOT NULL
, USER_ZIPCODE VARCHAR2(7) NOT NULL
, USER_ADDRESS VARCHAR2(300)    NOT NULL
, USER_ADDRESS_DETAIL VARCHAR2(300) NOT NULL
, CONSTRAINT USER_PROFILE_USER_ID_PK PRIMARY KEY(USER_ID)
, CONSTRAINT USER_PROFILE_USER_ID_FK FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
, CONSTRAINT USER_PROFILE_SSN_UK UNIQUE (USER_SSN)
, CONSTRAINT USER_PROFILE_EMAIL_UK UNIQUE (USER_EMAIL)
, CONSTRAINT USER_PROFILE_SSN_CK CHECK(LENGTH(USER_SSN)=13)
, CONSTRAINT USER_PROFILE_PHONE_CK CHECK(LENGTH(USER_PHONE)BETWEEN 10 AND 11) 
, CONSTRAINT USER_PROFILE_ZIPCODE_CK CHECK(LENGTH(USER_ZIPCODE)BETWEEN 5 AND 7)
);


-- ○ 4. 탈퇴 회원
CREATE TABLE DELETED_USER
( USER_ID   NUMBER  NOT NULL    
, USER_NAME VARCHAR2(50)    NOT NULL
, USER_SSN  CHAR(13)    NOT NULL
, USER_EMAIL VARCHAR2(100)  NOT NULL
, USER_PHONE CHAR(11)   NOT NULL
, USER_ZIPCODE VARCHAR2(7) NOT NULL
, USER_ADDRESS VARCHAR2(300)    NOT NULL
, USER_ADDRESS_DETAIL VARCHAR2(300) NOT NULL
, CONSTRAINT DELETED_USER_USER_ID_PK PRIMARY KEY(USER_ID)
, CONSTRAINT DELETED_USER_USER_ID_FK FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
, CONSTRAINT DELETED_USER_SSN_UK UNIQUE (USER_SSN)
, CONSTRAINT DELETED_USER_EMAIL_UK UNIQUE (USER_EMAIL)
, CONSTRAINT DELETED_USER_SSN_CK CHECK(LENGTH(USER_SSN)=13)
, CONSTRAINT DELETED_USER_PHONE_CK CHECK(LENGTH(USER_PHONE)BETWEEN 10 AND 11) 
, CONSTRAINT DELETED_USER_ZIPCODE_CK CHECK(LENGTH(USER_ZIPCODE)BETWEEN 5 AND 7)
);


-- ○ 5. 계정 이벤트 분류
CREATE TABLE ACCOUNT_EVENT_TYPE
( ACCOUNT_EVENT_TYPE_ID   NUMBER  NOT NULL
, EVENT_NAME    VARCHAR2(50)    NOT NULL
, CONSTRAINT ACCOUNT_EVENT_TYPE_ACCOUNT_EVENT_TYPE_ID_PK PRIMARY KEY(ACCOUNT_EVENT_TYPE_ID)
, CONSTRAINT ACCOUNT_EVENT_TYPE_EVENT_NAME_UK UNIQUE(EVENT_NAME)
);


-- ○ 6. 계정 이벤트 이력
CREATE TABLE ACCOUNT_EVENT_HISTORY
( ACCOUNT_EVENT_ID  NUMBER  NOT NULL
, USER_ID   NUMBER  NOT NULL
, ACCOUNT_EVENT_TYPE_ID NUMBER NOT NULL
, CREATED_AT DATE DEFAULT SYSDATE NOT NULL
, CONSTRAINT ACCOUNT_EVENT_HISTORY_ACCOUNT_EVENT_ID_PK PRIMARY KEY(ACCOUNT_EVENT_ID)
, CONSTRAINT ACCOUNT_EVENT_HISTORY_USER_ID_FK FOREIGN KEY(USER_ID)
            REFERENCES USERS(USER_ID)
, CONSTRAINT ACCOUNT_EVENT_HISTORY_ACCOUNT_EVENT_TYPE_ID_FK FOREIGN KEY(ACCOUNT_EVENT_TYPE_ID)
            REFERENCES ACCOUNT_EVENT_TYPE(ACCOUNT_EVENT_TYPE_ID)
, CONSTRAINT ACCOUNT_EVENT_HISTORY_USER_ID_ACCOUNT_EVENT_TYPE_ID_UK UNIQUE (USER_ID, ACCOUNT_EVENT_TYPE_ID)
);


-- ○ 7. 관리자 권한 코드
CREATE TABLE ADMIN_ROLE
( ADMIN_ROLE_ID   NUMBER  NOT NULL
, ADMIN_ROLE_NAME   VARCHAR2(50)    NOT NULL
, CONSTRAINT ADMIN_ROLE_ADMIN_ROLE_ID_PK PRIMARY KEY(ADMIN_ROLE_ID)
, CONSTRAINT ADMIN_ROLE_ADMIN_ROLE_NAME_UK UNIQUE(ADMIN_ROLE_NAME)
);


-- ○ 8. 관리자 계정
CREATE TABLE ADMIN_ACCOUNT
( ADMIN_ACCOUNT_ID  NUMBER  NOT NULL
, ADMIN_ROLE_ID   NUMBER  NOT NULL
, ADMIN_LOGIN_ID    VARCHAR2(50)    NOT NULL
, ADMIN_PASSWORD    VARCHAR2(100)   NOT NULL
, CONSTRAINT ADMIN_ACCOUNT_ADMIN_ACCOUNT_ID_PK PRIMARY KEY(ADMIN_ACCOUNT_ID)
, CONSTRAINT ADMIN_ACCOUNT_ADMIN_ROLE_ID_FK FOREIGN KEY(ADMIN_ROLE_ID)
        REFERENCES ADMIN_ROLE(ADMIN_ROLE_ID)
, CONSTRAINT ADMIN_LOGIN_ID_UK UNIQUE(ADMIN_LOGIN_ID)
, CONSTRAINT ADMIN_ACCOUNT_ID_CK CHECK(LENGTH(ADMIN_LOGIN_ID) BETWEEN 4 AND 12)
, CONSTRAINT ADMIN_ACCOUNT_PW_CK CHECK(LENGTH(ADMIN_PASSWORD) BETWEEN 8 AND 16)
);


-- ○ 9. 관리자 정보
CREATE TABLE ADMIN_PROFILE
( EMPLOYEE_ID   NUMBER  NOT NULL
, EMPLOYEE_NAME VARCHAR2(50)    NOT NULL
, DEPARTMENT    VARCHAR2(50)    NOT NULL
, CONSTRAINT ADMIN_PROFILE_EMPLOYEE_ID_PK PRIMARY KEY(EMPLOYEE_ID)
);


-- ○ 10. 관리자 계정 이력
CREATE TABLE ADMIN_ACCOUNT_HISTORY
( ADMIN_HISTORY_ID  NUMBER  NOT NULL
, ADMIN_ACCOUNT_ID  NUMBER  NOT NULL
, EMPLOYEE_ID   NUMBER  NOT NULL
, ACCOUNT_START_DATE    DATE    DEFAULT SYSDATE  NOT NULL
, ACCOUNT_END_DATE  DATE     NULL
, CONSTRAINT ADMIN_ACCOUNT_HISTORY_ADMIN_HISTORY_ID_PK PRIMARY KEY(ADMIN_HISTORY_ID)
, CONSTRAINT ADMIN_ACCOUNT_HISTORY_ADMIN_ACCOUNT_ID_FK FOREIGN KEY(ADMIN_ACCOUNT_ID)
            REFERENCES ADMIN_ACCOUNT(ADMIN_ACCOUNT_ID)
, CONSTRAINT ADMIN_ACCOUNT_HISTORY_EMPLOYEE_ID_FK FOREIGN KEY(EMPLOYEE_ID)
            REFERENCES ADMIN_PROFILE(EMPLOYEE_ID)
, CONSTRAINT ADMIN_ACCOUNT_HISTORY_ADMIN_ACCOUNT_ID_ACCOUNT_START_DATE_UK 
            UNIQUE(ADMIN_ACCOUNT_ID, ACCOUNT_START_DATE)
);


-- 유니크인덱스: 사용중인 계정은 관리자당 하나여야 함
CREATE UNIQUE INDEX UIX_ADMIN_CURRENT_ONLY
ON ADMIN_ACCOUNT_HISTORY
((CASE WHEN ACCOUNT_END_DATE IS NULL THEN ADMIN_ACCOUNT_ID
ELSE NULL
END));



-- ○ 11. 공통 여부 테이블
CREATE TABLE COMMON
( COMMON_YN_ID    NUMBER(1)   NOT NULL
, COMMON_YN_NAME    CHAR(1) NOT NULL
, CONSTRAINT COMMON_COMMON_YN_ID_PK PRIMARY KEY(COMMON_YN_ID)
, CONSTRAINT COMMON_COMMON_YN_NAME_UK UNIQUE(COMMON_YN_NAME)
, CONSTRAINT COMMON_COMMON_YN_NAME_CK CHECK(COMMON_YN_NAME IN ('Y','N'))
);



-- ○ 12. 상품 제조국
CREATE TABLE PRODUCT_COUNTRY
( PRODUCT_COUNTRY_ID CHAR(2) NOT NULL
, PRODUCT_COUNTRY_NAME VARCHAR2(50) NOT NULL
, CONSTRAINT PRODUCT_COUNTRY_PRODUCT_COUNTRY_ID_PK PRIMARY KEY(PRODUCT_COUNTRY_ID)
, CONSTRAINT PRODUCT_COUNTRY_NAME_UK UNIQUE(PRODUCT_COUNTRY_NAME)
, CONSTRAINT PRODUCT_COUNTRY_ID_CK CHECK (LENGTH(PRODUCT_COUNTRY_ID)=2) 
);


-- ○ 13. 상품 제조사
CREATE TABLE PRODUCT_MANUFACTURER
( MANUFACTURER_ID NUMBER NOT NULL
, PRODUCT_COUNTRY_ID CHAR(2) NOT NULL
, MANUFACTURER_NAME VARCHAR2(50) NOT NULL
, CONSTRAINT PRODUCT_MANUFACTURER_MANUFACTURER_ID_PK PRIMARY KEY(MANUFACTURER_ID)
, CONSTRAINT PRODUCT_MANUFACTURER_PRODUCT_COUNTRY_ID_FK FOREIGN KEY(PRODUCT_COUNTRY_ID)
            REFERENCES PRODUCT_COUNTRY(PRODUCT_COUNTRY_ID)
, CONSTRAINT PRODUCT_MANUFACTURER_PRODUCT_COUNTRY_ID_MANUFACTURER_NAME_UK UNIQUE(PRODUCT_COUNTRY_ID, MANUFACTURER_NAME)
);



-- ○ 14. 상품 등급
CREATE TABLE PRODUCT_GRADE
( PRODUCT_GRADE_ID NUMBER NOT NULL
, PRODUCT_GRADE_NAME VARCHAR2(50)   NOT NULL
, CONSTRAINT PRODUCT_GRADE_PRODUCT_GRADE_ID_PK PRIMARY KEY(PRODUCT_GRADE_ID)
, CONSTRAINT PRODUCT_GRADE_PRODUCT_GRADE_NAME_UK UNIQUE(PRODUCT_GRADE_NAME)
);


-- ○ 15. 상품 장르
CREATE TABLE PRODUCT_GENRE
( PRODUCT_GENRE_ID    NUMBER  NOT NULL
, PRODUCT_GENRE_NAME    VARCHAR2(50)    NOT NULL
, CONSTRAINT PRODUCT_GENRE_PRODUCT_GENRE_ID_PK PRIMARY KEY(PRODUCT_GENRE_ID)
, CONSTRAINT PRODUCT_GENRE_PRODUCT_GENRE_NAME_UK UNIQUE(PRODUCT_GENRE_NAME)
);


-- ○ 16. 상품 사이즈
CREATE TABLE PRODUCT_SIZE
( PRODUCT_SIZE_ID NUMBER  NOT NULL
, PRODUCT_SIZE_NAME VARCHAR2(10)    NOT NULL
, CONSTRAINT PRODUCT_SIZE_PRODUCT_SIZE_ID_PK PRIMARY KEY(PRODUCT_SIZE_ID)
, CONSTRAINT PRODUCT_SIZE_PRODUCT_SIZE_NAME_UK UNIQUE(PRODUCT_SIZE_NAME)
);


-- ○ 17. 상품 등록/관리
CREATE TABLE PRODUCT
( PRODUCT_ID    NUMBER  NOT NULL
, PRODUCT_RELEASE_NAME  VARCHAR2(500)
, PRODUCT_ALIAS VARCHAR2(500)
, USER_ID   NUMBER  NOT NULL
, MANUFACTURER_ID NUMBER  NOT NULL
, PRODUCT_GRADE_ID    NUMBER  NOT NULL
, PRODUCT_GENRE_ID    NUMBER  NOT NULL
, PRODUCT_SIZE_ID NUMBER  NOT NULL
, WORK_NAME VARCHAR2(20)
, CHARACTER_NAME    VARCHAR2(20)
, PURCHASE_DATETIME DATE
, IS_OPENED NUMBER(1) NOT NULL
, IS_PARTS_MISSING NUMBER(1)  NOT NULL
, DESCRIPTIONS  VARCHAR2(2000)
, IMAGE_PATH_1  VARCHAR2(500)   NOT NULL
, IMAGE_PATH_2  VARCHAR2(500)   NOT NULL
, IMAGE_PATH_3  VARCHAR2(500)   NOT NULL
, IS_PUBLIC NUMBER(1) NOT NULL
, CREATED_AT    DATE  DEFAULT SYSDATE NOT NULL 
, CONSTRAINT PRODUCT_PRODUCT_ID_PK PRIMARY KEY(PRODUCT_ID)
, CONSTRAINT PRODUCT_USER_ID_FK FOREIGN KEY(USER_ID)
        REFERENCES USERS(USER_ID)
, CONSTRAINT  PRODUCT_MANUFACTURER_ID_FK FOREIGN KEY(MANUFACTURER_ID)
        REFERENCES PRODUCT_MANUFACTURER(MANUFACTURER_ID)
, CONSTRAINT PRODUCT_PRODUCT_GRADE_ID_FK FOREIGN KEY(PRODUCT_GRADE_ID)
        REFERENCES PRODUCT_GRADE(PRODUCT_GRADE_ID)
, CONSTRAINT PRODUCT_PRODUCT_GENRE_ID_FK FOREIGN KEY(PRODUCT_GENRE_ID)
        REFERENCES PRODUCT_GENRE(PRODUCT_GENRE_ID)
, CONSTRAINT PRODUCT_PRODUCT_SIZE_ID_FK FOREIGN KEY(PRODUCT_SIZE_ID)
        REFERENCES PRODUCT_SIZE(PRODUCT_SIZE_ID)
, CONSTRAINT PRODUCT_IS_OPENED_FK FOREIGN KEY(IS_OPENED)
        REFERENCES COMMON(COMMON_YN_ID)
, CONSTRAINT PRODUCT_IS_PARTS_MISSING_FK FOREIGN KEY(IS_PARTS_MISSING)
        REFERENCES COMMON(COMMON_YN_ID)
, CONSTRAINT PRODUCT_IS_PUBLIC_FK FOREIGN KEY(IS_PUBLIC)
        REFERENCES COMMON(COMMON_YN_ID)
);


-- ○ 18. 추가 이미지
CREATE TABLE PRODUCT_IMAGE
( PRODUCT_IMAGE_ID NUMBER NOT NULL
, PRODUCT_ID    NUMBER  NOT NULL
, IMAGE_ORDER   NUMBER(1)   NOT NULL
, FILE_PATH VARCHAR2(500)   NOT NULL
, CREATED_AT    DATE DEFAULT SYSDATE
, CONSTRAINT PRODUCT_IMAGE_PRODUCT_IMAGE_ID_PK PRIMARY KEY(PRODUCT_IMAGE_ID)
, CONSTRAINT PRODUCT_IMAGE_PRODUCT_ID_FK FOREIGN KEY(PRODUCT_ID)
        REFERENCES PRODUCT(PRODUCT_ID)
, CONSTRAINT PRODUCT_IMAGE_PRODUCT_ID_IMAGE_ORDER_UK UNIQUE (PRODUCT_ID, IMAGE_ORDER)
);


-- ○ 19. 관심 상품
CREATE TABLE PRODUCT_WISHLIST
( WISHLIST_ID NUMBER    NOT NULL
, USER_ID   NUMBER  NOT NULL
, PRODUCT_ID    NUMBER  NOT NULL
, CREATED_AT    DATE    DEFAULT SYSDATE NOT NULL
, CONSTRAINT PRODUCT_WISHLIST_WISHLIST_ID_PK PRIMARY KEY(WISHLIST_ID)
, CONSTRAINT PRODUCT_WISHLIST_USER_ID_FK FOREIGN KEY(USER_ID)
            REFERENCES USERS(USER_ID)
, CONSTRAINT PRODUCT_WISHLIST_PRODUCT_ID_FK FOREIGN KEY(PRODUCT_ID)
            REFERENCES PRODUCT(PRODUCT_ID)
, CONSTRAINT PRODUCT_WISHLIST_USER_ID_PRODUCT_ID_UK UNIQUE(USER_ID, PRODUCT_ID)

);


-- ○ 20. 머니 분류
CREATE TABLE MONEY_TYPE
( MONEY_TYPE_ID NUMBER    NOT NULL
, MONEY_TYPE_NAME VARCHAR2(50)  NOT NULL
, CONSTRAINT MONEY_TYPE_MONEY_TYPE_ID_PK PRIMARY KEY(MONEY_TYPE_ID)
, CONSTRAINT MONEY_TYPE_MONEY_TYPE_NAME_UK UNIQUE(MONEY_TYPE_NAME)
);


-- ○ 21. 머니 충전 수단
CREATE TABLE MONEY_CHARGE_METHOD 
(
      MONEY_CHARGE_METHOD_ID NUMBER
    , MONEY_CHARGE_METHOD_NAME VARCHAR2(50) NOT NULL
    , CONSTRAINT MONEY_CHARGE_METHOD_MONEY_CHARGE_METHOD_ID_PK PRIMARY KEY (MONEY_CHARGE_METHOD_ID)
    , CONSTRAINT MONEY_CHARGE_METHOD_MONEY_CHARGE_METHOD_NAME_UK UNIQUE (MONEY_CHARGE_METHOD_NAME)
);

-- ○ 22. 머니 충전 이력
CREATE TABLE MONEY_CHARGE_HISTORY 
(
      MONEY_CHARGE_ID          NUMBER
    , USER_ID                  NUMBER NOT NULL
    , MONEY_CHARGE_METHOD_ID NUMBER NOT NULL
    , CHARGE_AMOUNT            NUMBER NOT NULL
    , CHARGED_AT               DATE   DEFAULT SYSDATE NOT NULL
    , CONSTRAINT MONEY_CHARGE_HISTORY_MONEY_CHARGE_ID_PK PRIMARY KEY (MONEY_CHARGE_ID)
    , CONSTRAINT MONEY_CHARGE_HISTORY_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
    , CONSTRAINT MONEY_CHARGE_HISTORY_MONEY_CHARGE_METHOD_ID_FK FOREIGN KEY (MONEY_CHARGE_METHOD_ID) REFERENCES MONEY_CHARGE_METHOD(MONEY_CHARGE_METHOD_ID)
);

-- ○ 23. 경매 기간
CREATE TABLE AUCTION_PERIOD 
(
      AUCTION_PERIOD_ID NUMBER
    , AUCTION_PERIOD_NAME VARCHAR2(10) NOT NULL
    , CONSTRAINT AUCTION_PERIOD_AUCTION_PERIOD_ID_PK PRIMARY KEY (AUCTION_PERIOD_ID)
    , CONSTRAINT AUCTION_PERIOD_AUCTION_PERIOD_NAME_UK UNIQUE (AUCTION_PERIOD_NAME)
);

-- ○ 24. 경매 등록
CREATE TABLE AUCTION_REGISTRATION 
(
      AUCTION_ID          NUMBER
    , PRODUCT_ID          NUMBER         NOT NULL
    , AUCTION_TITLE       VARCHAR2(300)  NOT NULL
    , AUCTION_CONTENT     VARCHAR2(2000) NOT NULL
    , START_PRICE         NUMBER(12)     NOT NULL
    , CREATED_AT          DATE           DEFAULT SYSDATE NOT NULL
    , AUCTION_PERIOD_ID NUMBER
    , CONSTRAINT AUCTION_REGISTRATION_AUCTION_ID_PK PRIMARY KEY (AUCTION_ID)
    , CONSTRAINT AUCTION_REGISTRATION_PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
    , CONSTRAINT AUCTION_REGISTRATION_AUCTION_PERIOD_ID_FK FOREIGN KEY (AUCTION_PERIOD_ID) REFERENCES AUCTION_PERIOD(AUCTION_PERIOD_ID)
    , CONSTRAINT AUCTION_REGISTRATION_START_PRICE_CK CHECK (START_PRICE > 0)
);


-- ○ 25. 머니 입출금 이력  ← AUCTION_REGISTRATION 이후에 생성
CREATE TABLE MONEY_TRANSACTION_HISTORY 
(
      MONEY_ID        NUMBER
    , USER_ID         NUMBER      NOT NULL
    , MONEY_TYPE_ID NUMBER      NOT NULL
    , AUCTION_ID      NUMBER      
    , AMOUNT          NUMBER(12)  NOT NULL
    , CREATED_AT      DATE        DEFAULT SYSDATE NOT NULL
    , CONSTRAINT MONEY_TRANSACTION_HISTORY_MONEY_ID_PK PRIMARY KEY (MONEY_ID)
    , CONSTRAINT MONEY_TRANSACTION_HISTORY_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
    , CONSTRAINT MONEY_TRANSACTION_HISTORY_MONEY_TYPE_ID_FK FOREIGN KEY (MONEY_TYPE_ID) REFERENCES MONEY_TYPE(MONEY_TYPE_ID)
    , CONSTRAINT MONEY_TRANSACTION_HISTORY_AUCTION_ID_FK FOREIGN KEY (AUCTION_ID) REFERENCES AUCTION_REGISTRATION(AUCTION_ID)
);

-- ○ 26. 경매 취소 이력
CREATE TABLE AUCTION_CANCEL_HISTORY 
(
      AUCTION_CANCEL_ID NUMBER
    , AUCTION_ID        NUMBER        NOT NULL
    , CANCEL_REASON     VARCHAR2(500) NOT NULL
    , CANCEL_AT         DATE          DEFAULT SYSDATE NOT NULL
    , CONSTRAINT AUCTION_CANCEL_HISTORY_AUCTION_CANCEL_ID_PK PRIMARY KEY (AUCTION_CANCEL_ID)
    , CONSTRAINT AUCTION_CANCEL_HISTORY_AUCTION_ID_FK FOREIGN KEY (AUCTION_ID) REFERENCES AUCTION_REGISTRATION(AUCTION_ID)
    , CONSTRAINT AUCTION_CANCEL_HISTORY_AUCTION_ID_UK UNIQUE (AUCTION_ID)
);

-- ○ 27. 입찰 참여
CREATE TABLE AUCTION_BID_PARTICIPATION 
(
      BID_ID     NUMBER
    , AUCTION_ID NUMBER     NOT NULL
    , USER_ID    NUMBER     NOT NULL
    , BID_TIME   TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL
    , BID_PRICE  NUMBER(10) NOT NULL
    , CONSTRAINT AUCTION_BID_PARTICIPATION_BID_ID_PK PRIMARY KEY (BID_ID)
    , CONSTRAINT AUCTION_BID_PARTICIPATION_AUCTION_ID_FK FOREIGN KEY (AUCTION_ID) REFERENCES AUCTION_REGISTRATION(AUCTION_ID)
    , CONSTRAINT AUCTION_BID_PARTICIPATION_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
    , CONSTRAINT AUCTION_BID_PARTICIPATION_AUCTION_ID_USER_ID_BID_TIME_UK UNIQUE (AUCTION_ID, USER_ID, BID_TIME)
);

-- ○ 28. 낙찰 결과
CREATE TABLE AUCTION_WINNING_RESULT 
(
      BID_RESULT_ID NUMBER
    , BID_ID        NUMBER NOT NULL
    , CREATED_AT    DATE   DEFAULT SYSDATE NOT NULL
    , CONSTRAINT AUCTION_WINNING_RESULT_BID_RESULT_ID_PK PRIMARY KEY (BID_RESULT_ID)
    , CONSTRAINT AUCTION_WINNING_RESULT_BID_ID_FK FOREIGN KEY (BID_ID) REFERENCES AUCTION_BID_PARTICIPATION(BID_ID)
    , CONSTRAINT AUCTION_WINNING_RESULT_BID_ID_UK UNIQUE (BID_ID)
);

-- ○ 29. 낙찰 실패 유형
CREATE TABLE BID_FAILURE_TYPE 
(
      BID_FAIL_TYPE_ID NUMBER
    , BID_FAIL_TYPE_NAME VARCHAR2(50) NOT NULL
    , CONSTRAINT BID_FAILURE_TYPE_BID_FAIL_TYPE_ID_PK PRIMARY KEY (BID_FAIL_TYPE_ID)
    , CONSTRAINT BID_FAILURE_TYPE_BID_FAIL_TYPE_NAME_UK UNIQUE (BID_FAIL_TYPE_NAME)
);

-- ○ 30. 낙찰 실패 이력
CREATE TABLE BID_FAILURE_HISTORY 
(
      BID_FAIL_HISTORY_ID NUMBER
    , BID_RESULT_ID       NUMBER NOT NULL
    , BID_FAIL_TYPE_ID  NUMBER NOT NULL
    , CREATED_AT          DATE   DEFAULT SYSDATE NOT NULL
    , CONSTRAINT BID_FAILURE_HISTORY_BID_FAIL_HISTORY_ID_PK PRIMARY KEY (BID_FAIL_HISTORY_ID)
    , CONSTRAINT BID_FAILURE_HISTORY_BID_RESULT_ID_FK FOREIGN KEY (BID_RESULT_ID) REFERENCES AUCTION_WINNING_RESULT(BID_RESULT_ID)
    , CONSTRAINT BID_FAILURE_HISTORY_BID_FAIL_TYPE_ID_FK FOREIGN KEY (BID_FAIL_TYPE_ID) REFERENCES BID_FAILURE_TYPE(BID_FAIL_TYPE_ID)
    , CONSTRAINT BID_FAILURE_HISTORY_BID_RESULT_ID_UK UNIQUE (BID_RESULT_ID)
);

-- ○ 31. 낙찰 입금
CREATE TABLE AUCTION_WINNING_PAYMENT 
(
      PAYMENT_ID    NUMBER
    , BID_RESULT_ID NUMBER NOT NULL
    , MONEY_ID      NUMBER NOT NULL
    , CREATED_AT    DATE   DEFAULT SYSDATE NOT NULL
    , CONSTRAINT AUCTION_WINNING_PAYMENT_PAYMENT_ID_PK PRIMARY KEY (PAYMENT_ID)
    , CONSTRAINT AUCTION_WINNING_PAYMENT_BID_RESULT_ID_FK FOREIGN KEY (BID_RESULT_ID) REFERENCES AUCTION_WINNING_RESULT(BID_RESULT_ID)
    , CONSTRAINT AUCTION_WINNING_PAYMENT_MONEY_ID_FK FOREIGN KEY (MONEY_ID) REFERENCES MONEY_TRANSACTION_HISTORY(MONEY_ID)
    , CONSTRAINT AUCTION_WINNING_PAYMENT_BID_RESULT_ID_UK UNIQUE (BID_RESULT_ID)
);

-- ○ 32. 발송 완료
CREATE TABLE DELIVERY_COMPLETED 
(
      SHIPPING_ID NUMBER
    , PAYMENT_ID  NUMBER NOT NULL
    , CREATED_AT  DATE   DEFAULT SYSDATE NOT NULL
    , CONSTRAINT DELIVERY_COMPLETED_SHIPPING_ID_PK PRIMARY KEY (SHIPPING_ID)
    , CONSTRAINT DELIVERY_COMPLETED_PAYMENT_ID_FK FOREIGN KEY (PAYMENT_ID) REFERENCES AUCTION_WINNING_PAYMENT(PAYMENT_ID)
    , CONSTRAINT DELIVERY_COMPLETED_PAYMENT_ID_UK UNIQUE (PAYMENT_ID)
);



-- ○ 33. 구매 확정 이력
CREATE TABLE PURCHASE_CONFIRM_HISTORY
(
PURCHASE_CONFIRM_ID NUMBER
,SHIPPING_ID NUMBER NOT NULL
,CREATED_AT DATE DEFAULT SYSDATE NOT NULL
,CONSTRAINT PURCHASE_CONFIRM_HISTORY_PURCHASE_CONFIRM_ID_PK PRIMARY KEY(PURCHASE_CONFIRM_ID)
,CONSTRAINT PURCHASE_CONFIRM_HISTORY_SHIPPING_ID_FK FOREIGN KEY(SHIPPING_ID)
                                                    REFERENCES DELIVERY_COMPLETED(SHIPPING_ID)                                             
);

-- ○ 34. 거래 완료
CREATE TABLE TRANSACTION_COMPLETED
(
TRANSACTION_ID NUMBER
,PURCHASE_CONFIRM_ID NUMBER NOT NULL 
,CREATED_AT DATE DEFAULT SYSDATE NOT NULL
,CONSTRAINT TRANSACTION_COMPLETED_TRANSACTION_ID_PK PRIMARY KEY(TRANSACTION_ID)
,CONSTRAINT TRANSACTION_COMPLETED_PURCHASE_CONFIRM_ID_FK FOREIGN KEY(PURCHASE_CONFIRM_ID)
                                                         REFERENCES PURCHASE_CONFIRM_HISTORY(PURCHASE_CONFIRM_ID)
);

-- ○ 35. 패널티 부여 구분
CREATE TABLE PENALTY_ASSIGN_TYPE
(
PENALTY_TYPE_ID NUMBER
,PENALTY_TYPE_NAME VARCHAR2(50) NOT NULL
,CONSTRAINT PENALTY_ASSIGN_TYPE_PENALTY_ASSIGN_TYPE_ID_PK PRIMARY KEY(PENALTY_TYPE_ID)
,CONSTRAINT PENALTY_ASSIGN_TYPE_PENALTY_TYPE_NAME_UK UNIQUE(PENALTY_TYPE_NAME)
);

-- ○ 36. 패널티 이력
CREATE TABLE PENALTY_HISTORY
(
PENALTY_ID NUMBER
,USER_ID NUMBER NOT NULL
,PENALTY_TYPE_ID NUMBER NOT NULL
,ADMIN_ACCOUNT_ID NUMBER NOT NULL
,PENALTY_SCORE NUMBER NOT NULL
,PENALTY_START_DATE DATE NOT NULL
,PENALTY_END_DATE DATE NOT NULL
,CREATED_AT DATE DEFAULT SYSDATE NOT NULL
,CONSTRAINT PENALTY_HISTORY_PENALTY_HISTORY_ID_PK PRIMARY KEY(PENALTY_ID)
,CONSTRAINT PENALTY_HISTORY_USER_ID_FK FOREIGN KEY(USER_ID)
                                        REFERENCES USERS(USER_ID)
,CONSTRAINT PENALTY_HISTORY_PENALTY_TYPE_ID_FK FOREIGN KEY(PENALTY_TYPE_ID)
                                                  REFERENCES PENALTY_ASSIGN_TYPE(PENALTY_TYPE_ID)
,CONSTRAINT PENALTY_HISTORY_ADMIN_ACCOUNT_ID_FK FOREIGN KEY(ADMIN_ACCOUNT_ID)
                                             REFERENCES ADMIN_ACCOUNT(ADMIN_ACCOUNT_ID)
,CONSTRAINT PENALTY_HISTORY_SCORE_CK CHECK(PENALTY_SCORE BETWEEN 1 AND 4)
);

-- ○ 37. 패널티 취소
CREATE TABLE PENALTY_CANCEL
(
PENALTY_CANCEL_ID NUMBER
,PENALTY_ID NUMBER NOT NULL
,ADMIN_ACCOUNT_ID NUMBER NOT NULL
,CANCEL_REASON VARCHAR2(500) NOT NULL
,CANCELED_AT DATE DEFAULT SYSDATE NOT NULL
,CONSTRAINT PENALTY_CANCEL_PENALTY_CANCEL_ID_PK PRIMARY KEY(PENALTY_CANCEL_ID)
,CONSTRAINT PENALTY_CANCEL_PENALTY_ID_FK FOREIGN KEY(PENALTY_ID)
                                        REFERENCES PENALTY_HISTORY(PENALTY_ID)
,CONSTRAINT PENALTY_CANCEL_ADMIN_ACCOUNT_ID_FK FOREIGN KEY(ADMIN_ACCOUNT_ID)
                                                REFERENCES ADMIN_ACCOUNT(ADMIN_ACCOUNT_ID)
,CONSTRAINT PENALTY_CANCEL_PENALTY_ID_UK UNIQUE(PENALTY_ID)                                                                                          
);

-- ○ 38. 신고 유형
CREATE TABLE REPORT_TYPE
(
REPORT_TYPE_ID NUMBER
,REPORT_TYPE_NAME VARCHAR2(50) NOT NULL
,CONSTRAINT REPORT_TYPE_REPORT_TYPE_ID_PK PRIMARY KEY(REPORT_TYPE_ID)
,CONSTRAINT REPORT_TYPE_REPORT_TYPE_NAME_UK UNIQUE(REPORT_TYPE_NAME)
);

-- ○ 39. 신고 대상
CREATE TABLE REPORT_TARGET
(
REPORT_TARGET_ID NUMBER
,REPORT_TARGET_NAME VARCHAR2(50) NOT NULL
,CONSTRAINT REPORT_TARGET_REPORT_TARGET_ID_PK PRIMARY KEY(REPORT_TARGET_ID)
,CONSTRAINT REPORT_TARGET_REPORT_TARGET_NAME_UK UNIQUE(REPORT_TARGET_NAME)
);

-- ○ 40. 신고 신청
CREATE TABLE REPORT_SUBMISSION
(
REPORT_SUBMISSION_ID NUMBER
,USER_ID NUMBER NOT NULL
,REPORT_TARGET_ID NUMBER NOT NULL
,REPORT_TYPE_ID NUMBER NOT NULL
,REPORT_REASON VARCHAR2(500)
,CREATED_AT DATE DEFAULT SYSDATE NOT NULL
,CONSTRAINT REPORT_SUBMISSION_REPORT_SUBMISSION_ID_PK PRIMARY KEY(REPORT_SUBMISSION_ID)
,CONSTRAINT REPORT_SUBMISSION_USER_ID_FK FOREIGN KEY(USER_ID)
                                         REFERENCES USERS(USER_ID)
,CONSTRAINT REPORT_SUBMISSION_REPORT_TARGET_ID_FK FOREIGN KEY(REPORT_TARGET_ID)
                                                    REFERENCES REPORT_TARGET(REPORT_TARGET_ID)
,CONSTRAINT REPORT_SUBMISSION_REPORT_TYPE_ID_FK FOREIGN KEY(REPORT_TYPE_ID)
                                                   REFERENCES REPORT_TYPE(REPORT_TYPE_ID)
);

-- ○ 41. 상품 신고
CREATE TABLE PRODUCT_REPORT
(
PRODUCT_REPORT_ID NUMBER
,REPORT_ID NUMBER NOT NULL
,PRODUCT_ID NUMBER NOT NULL
,CONSTRAINT PRODUCT_REPORT_PRODUCT_REPORT_ID_PK PRIMARY KEY(PRODUCT_REPORT_ID)
,CONSTRAINT PRODUCT_REPORT_REPORT_ID_FK FOREIGN KEY(REPORT_ID)
                                        REFERENCES REPORT_SUBMISSION(REPORT_ID)
,CONSTRAINT PRODUCT_REPORT_PRODUCT_ID_FK FOREIGN KEY(PRODUCT_ID)
                                         REFERENCES PRODUCT(PRODUCT_ID)
);

-- ○ 42. 경매 신고
CREATE TABLE AUCTION_REPORT
(
AUCTION_REPORT_ID NUMBER
,REPORT_ID NUMBER NOT NULL
,AUCTION_ID NUMBER NOT NULL
,CONSTRAINT AUCTION_REPORT_AUCTION_REPORT_ID_PK PRIMARY KEY(AUCTION_REPORT_ID)
,CONSTRAINT AUCTION_REPORT_REPORT_ID_FK FOREIGN KEY(REPORT_ID)
                                        REFERENCES REPORT_SUBMISSION(REPORT_ID)
,CONSTRAINT AUCTION_REPORT_AUCTION_ID_FK FOREIGN KEY(AUCTION_ID)
                                          REFERENCES AUCTION_REGISTRATION(AUCTION_ID)
);

-- ○ 43. 신고 처리 결과
CREATE TABLE REPORT_RESULT
(
REPORT_RESULT_ID NUMBER
,REPORT_RESULT_NAME VARCHAR2(50) NOT NULL
,CONSTRAINT REPORT_RESULT_REPORT_RESULT_ID_PK PRIMARY KEY(REPORT_RESULT_ID)
,CONSTRAINT REPORT_RESULT_REPORT_RESULT_NAME_UK UNIQUE(REPORT_RESULT_NAME)
);

-- ○ 44. 신고 처리
CREATE TABLE REPORT_PROCESS
(
REPORT_PROCESS_ID NUMBER
,REPORT_ID NUMBER NOT NULL
,ADMIN_ACCOUNT_ID NUMBER NOT NULL
,REPORT_RESULT_ID NUMBER NOT NULL
,PROCESS_REASON VARCHAR2(500) NOT NULL
,PROCESSED_AT DATE DEFAULT SYSDATE NOT NULL
,CONSTRAINT REPORT_PROCESS_REPORT_PROCESS_ID_PK PRIMARY KEY(REPORT_PROCESS_ID)
,CONSTRAINT REPORT_PROCESS_REPORT_ID_FK FOREIGN KEY(REPORT_ID)
                                        REFERENCES REPORT_SUBMISSION(REPORT_ID)
,CONSTRAINT REPORT_PROCESS_ADMIN_ACCOUNT_ID_FK FOREIGN KEY(ADMIN_ACCOUNT_ID)
                                                REFERENCES ADMIN_ACCOUNT(ADMIN_ACCOUNT_ID)
,CONSTRAINT REPORT_PROCESS_REPORT_RESULT_ID_FK FOREIGN KEY(REPORT_RESULT_ID)                                               
                                                  REFERENCES REPORT_RESULT(REPORT_RESULT_ID)
);





--CREATE SEQUENCE ==========================================================================
-- [ 회원 관련 시퀀스 ]
-- 1. USERS 테이블용
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 5. ACCOUNT_EVENT_TYPE 테이블용 (분류 코드를 시퀀스로 할 경우)
CREATE SEQUENCE ACCOUNT_EVENT_TYPE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 6. ACCOUNT_EVENT_HISTORY 테이블용
CREATE SEQUENCE ACCOUNT_EVENT_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;


-- [ 관리자 관련 시퀀스 ]
-- 7. ADMIN_ROLE 테이블용
CREATE SEQUENCE ADMIN_ROLE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 8. ADMIN_ACCOUNT 테이블용
CREATE SEQUENCE ADMIN_ACCOUNT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 9. ADMIN_PROFILE 테이블용 (사번/관리자고유번호)
CREATE SEQUENCE ADMIN_PROFILE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 10. ADMIN_ACCOUNT_HISTORY 테이블용
CREATE SEQUENCE ADMIN_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;


-- [ 상품 관련 시퀀스 ]
-- 13. PRODUCT_MANUFACTURER 테이블용
CREATE SEQUENCE MANUFACTURER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 14. PRODUCT_GRADE 테이블용
CREATE SEQUENCE PRODUCT_GRADE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 15. PRODUCT_GENRE 테이블용
CREATE SEQUENCE PRODUCT_GENRE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 16. PRODUCT_SIZE 테이블용
CREATE SEQUENCE PRODUCT_SIZE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 17. PRODUCT 테이블용
CREATE SEQUENCE PRODUCT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 18. PRODUCT_IMAGE 테이블용
CREATE SEQUENCE PRODUCT_IMAGE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 19. PRODUCT_WISHLIST 테이블용
CREATE SEQUENCE WISHLIST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;


-- [ 머니 및 결제 관련 시퀀스 ]
-- 20. MONEY_TYPE 테이블용
CREATE SEQUENCE MONEY_TYPE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 21. MONEY_CHARGE_METHOD 테이블용
CREATE SEQUENCE MONEY_CHARGE_METHOD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 22. MONEY_CHARGE_HISTORY 테이블용
CREATE SEQUENCE MONEY_CHARGE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 25. MONEY_TRANSACTION_HISTORY 테이블용
CREATE SEQUENCE MONEY_TRANSACTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;


-- [ 경매 관련 시퀀스 ]
-- 23. AUCTION_PERIOD 테이블용
CREATE SEQUENCE AUCTION_PERIOD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 24. AUCTION_REGISTRATION 테이블용
CREATE SEQUENCE AUCTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 26. AUCTION_CANCEL_HISTORY 테이블용
CREATE SEQUENCE AUCTION_CANCEL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 27. AUCTION_BID_PARTICIPATION 테이블용
CREATE SEQUENCE BID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 28. AUCTION_WINNING_RESULT 테이블용
CREATE SEQUENCE BID_RESULT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 31. AUCTION_WINNING_PAYMENT 테이블용
CREATE SEQUENCE PAYMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;


-- [ 낙찰 실패/배송/확정 관련 시퀀스 ]
-- 29. BID_FAILURE_TYPE 테이블용
CREATE SEQUENCE BID_FAIL_TYPE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 30. BID_FAILURE_HISTORY 테이블용
CREATE SEQUENCE BID_FAIL_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 32. DELIVERY_COMPLETED 테이블용
CREATE SEQUENCE SHIPPING_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 33. PURCHASE_CONFIRM_HISTORY 테이블용
CREATE SEQUENCE PURCHASE_CONFIRM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 34. TRANSACTION_COMPLETED 테이블용
CREATE SEQUENCE TRANSACTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;


-- [ 패널티 및 신고 관련 시퀀스 ]
-- 35. PENALTY_ASSIGN_TYPE 테이블용
CREATE SEQUENCE PENALTY_TYPE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 36. PENALTY_HISTORY 테이블용
CREATE SEQUENCE PENALTY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 37. PENALTY_CANCEL 테이블용
CREATE SEQUENCE PENALTY_CANCEL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 38. REPORT_TYPE 테이블용
CREATE SEQUENCE REPORT_TYPE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 39. REPORT_TARGET 테이블용
CREATE SEQUENCE REPORT_TARGET_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 40. REPORT_SUBMISSION 테이블용
CREATE SEQUENCE REPORT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 41. PRODUCT_REPORT 테이블용
CREATE SEQUENCE PRODUCT_REPORT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 42. AUCTION_REPORT 테이블용
CREATE SEQUENCE AUCTION_REPORT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 43. REPORT_RESULT 테이블용
CREATE SEQUENCE REPORT_RESULT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 44. REPORT_PROCESS 테이블용
CREATE SEQUENCE REPORT_PROCESS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
--CREATE SEQUENCE ==========================================================================






--DROP SEQUENCE ==========================================================================
DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE ACCOUNT_EVENT_TYPE_SEQ;
DROP SEQUENCE ACCOUNT_EVENT_HISTORY_SEQ;
DROP SEQUENCE ADMIN_ROLE_SEQ;
DROP SEQUENCE ADMIN_ACCOUNT_SEQ;
DROP SEQUENCE ADMIN_PROFILE_SEQ;
DROP SEQUENCE ADMIN_HISTORY_SEQ;
DROP SEQUENCE MANUFACTURER_SEQ;
DROP SEQUENCE PRODUCT_GRADE_SEQ;
DROP SEQUENCE PRODUCT_GENRE_SEQ;
DROP SEQUENCE PRODUCT_SIZE_SEQ;
DROP SEQUENCE PRODUCT_SEQ;
DROP SEQUENCE PRODUCT_IMAGE_SEQ;
DROP SEQUENCE WISHLIST_SEQ;
DROP SEQUENCE MONEY_TYPE_SEQ;
DROP SEQUENCE MONEY_CHARGE_METHOD_SEQ;
DROP SEQUENCE MONEY_CHARGE_SEQ;
DROP SEQUENCE MONEY_TRANSACTION_SEQ;
DROP SEQUENCE AUCTION_PERIOD_SEQ;
DROP SEQUENCE AUCTION_SEQ;
DROP SEQUENCE AUCTION_CANCEL_SEQ;
DROP SEQUENCE BID_SEQ;
DROP SEQUENCE BID_RESULT_SEQ;
DROP SEQUENCE PAYMENT_SEQ;
DROP SEQUENCE BID_FAIL_TYPE_SEQ;
DROP SEQUENCE BID_FAIL_HISTORY_SEQ;
DROP SEQUENCE SHIPPING_SEQ;
DROP SEQUENCE PURCHASE_CONFIRM_SEQ;
DROP SEQUENCE TRANSACTION_SEQ;
DROP SEQUENCE PENALTY_TYPE_SEQ;
DROP SEQUENCE PENALTY_SEQ;
DROP SEQUENCE PENALTY_CANCEL_SEQ;
DROP SEQUENCE REPORT_TYPE_SEQ;
DROP SEQUENCE REPORT_TARGET_SEQ;
DROP SEQUENCE REPORT_SEQ;
DROP SEQUENCE PRODUCT_REPORT_SEQ;
DROP SEQUENCE AUCTION_REPORT_SEQ;
DROP SEQUENCE REPORT_RESULT_SEQ;
DROP SEQUENCE REPORT_PROCESS_SEQ;

--DROP SEQUENCE ==========================================================================







--DROP TABLE ==========================================================================

DROP TABLE REPORT_PROCESS;
DROP TABLE REPORT_RESULT;
DROP TABLE AUCTION_REPORT;
DROP TABLE PRODUCT_REPORT;
DROP TABLE REPORT_SUBMISSION;
DROP TABLE REPORT_TARGET;
DROP TABLE REPORT_TYPE;
DROP TABLE PENALTY_CANCEL;
DROP TABLE PENALTY_HISTORY;
DROP TABLE PENALTY_ASSIGN_TYPE;
DROP TABLE TRANSACTION_COMPLETED;
DROP TABLE PURCHASE_CONFIRM_HISTORY;
DROP TABLE DELIVERY_COMPLETED;
DROP TABLE AUCTION_WINNING_PAYMENT;
DROP TABLE BID_FAILURE_HISTORY;
DROP TABLE BID_FAILURE_TYPE;
DROP TABLE AUCTION_WINNING_RESULT;
DROP TABLE AUCTION_BID_PARTICIPATION;
DROP TABLE AUCTION_CANCEL_HISTORY;
DROP TABLE MONEY_TRANSACTION_HISTORY;
DROP TABLE AUCTION_REGISTRATION;
DROP TABLE AUCTION_PERIOD;
DROP TABLE MONEY_CHARGE_HISTORY;
DROP TABLE MONEY_CHARGE_METHOD;
DROP TABLE MONEY_TYPE;
DROP TABLE PRODUCT_WISHLIST;
DROP TABLE PRODUCT_IMAGE;
DROP TABLE PRODUCT;
DROP TABLE PRODUCT_SIZE;
DROP TABLE PRODUCT_GENRE;
DROP TABLE PRODUCT_GRADE;
DROP TABLE PRODUCT_MANUFACTURER;
DROP TABLE PRODUCT_COUNTRY;
DROP TABLE COMMON;
DROP TABLE ADMIN_ACCOUNT_HISTORY;
DROP TABLE ADMIN_PROFILE;
DROP TABLE ADMIN_ACCOUNT;
DROP TABLE ADMIN_ROLE;
DROP TABLE ACCOUNT_EVENT_HISTORY;
DROP TABLE ACCOUNT_EVENT_TYPE;
DROP TABLE DELETED_USER;
DROP TABLE USER_PROFILE;
DROP TABLE USER_ACCOUNT;
DROP TABLE USERS;

--DROP TABLE ==========================================================================