SELECT USER
FROM DUAL;

-- 범례테이블 데이터 생성 ======================================================

-- 5. ACCOUNT_EVENT_TYPE
INSERT INTO ACCOUNT_EVENT_TYPE (ACCOUNT_EVENT_TYPE_ID, EVENT_NAME)
VALUES (ACCOUNT_EVENT_TYPE_SEQ.NEXTVAL, '가입');
INSERT INTO ACCOUNT_EVENT_TYPE (ACCOUNT_EVENT_TYPE_ID, EVENT_NAME)
VALUES (ACCOUNT_EVENT_TYPE_SEQ.NEXTVAL, '탈퇴');

SELECT *
FROM ACCOUNT_EVENT_TYPE;
/*
1	가입
2	탈퇴
*/

-- 7. ADMIN_ROLE
INSERT INTO ADMIN_ROLE (ADMIN_ROLE_ID, ADMIN_ROLE_NAME)
VALUES (ADMIN_ROLE_SEQ.NEXTVAL, '최고관리자');
INSERT INTO ADMIN_ROLE (ADMIN_ROLE_ID, ADMIN_ROLE_NAME)
VALUES (ADMIN_ROLE_SEQ.NEXTVAL, '관리자');

SELECT *
FROM ADMIN_ROLE;
/*
1	최고관리자
2	관리자
*/

-- 11. COMMON
INSERT INTO COMMON (COMMON_YN_ID, COMMON_YN_NAME)
VALUES (0, 'N'); 
INSERT INTO COMMON (COMMON_YN_ID, COMMON_YN_NAME)
VALUES (1, 'Y'); 

SELECT *
FROM COMMON;
/*
0	N
1	Y
*/




-- 14. PRODUCT_GRADE
INSERT INTO PRODUCT_GRADE (PRODUCT_GRADE_ID, PRODUCT_GRADE_NAME)
VALUES (PRODUCT_GRADE_SEQ.NEXTVAL, '최상');
INSERT INTO PRODUCT_GRADE (PRODUCT_GRADE_ID, PRODUCT_GRADE_NAME)
VALUES (PRODUCT_GRADE_SEQ.NEXTVAL, '상');
INSERT INTO PRODUCT_GRADE (PRODUCT_GRADE_ID, PRODUCT_GRADE_NAME)
VALUES (PRODUCT_GRADE_SEQ.NEXTVAL, '중');
INSERT INTO PRODUCT_GRADE (PRODUCT_GRADE_ID, PRODUCT_GRADE_NAME)
VALUES (PRODUCT_GRADE_SEQ.NEXTVAL, '하');

SELECT *
FROM PRODUCT_GRADE;
/*
1	최상
2	상
3	중
4	하
*/


-- 15. PRODUCT_GENRE
INSERT INTO PRODUCT_GENRE (PRODUCT_GENRE_ID, PRODUCT_GENRE_NAME)
VALUES (PRODUCT_GENRE_SEQ.NEXTVAL, '영화');
INSERT INTO PRODUCT_GENRE (PRODUCT_GENRE_ID, PRODUCT_GENRE_NAME)
VALUES (PRODUCT_GENRE_SEQ.NEXTVAL, '애니메이션');
INSERT INTO PRODUCT_GENRE (PRODUCT_GENRE_ID, PRODUCT_GENRE_NAME)
VALUES (PRODUCT_GENRE_SEQ.NEXTVAL, '만화(코믹스)');
INSERT INTO PRODUCT_GENRE (PRODUCT_GENRE_ID, PRODUCT_GENRE_NAME)
VALUES (PRODUCT_GENRE_SEQ.NEXTVAL, '게임');
INSERT INTO PRODUCT_GENRE (PRODUCT_GENRE_ID, PRODUCT_GENRE_NAME)
VALUES (PRODUCT_GENRE_SEQ.NEXTVAL, '연예인');
INSERT INTO PRODUCT_GENRE (PRODUCT_GENRE_ID, PRODUCT_GENRE_NAME)
VALUES (PRODUCT_GENRE_SEQ.NEXTVAL, '버튜버');
INSERT INTO PRODUCT_GENRE (PRODUCT_GENRE_ID, PRODUCT_GENRE_NAME)
VALUES (PRODUCT_GENRE_SEQ.NEXTVAL, '기타');

SELECT *
FROM PRODUCT_GENRE;
/*
1	영화
3	애니메이션
4	만화(코믹스)
5	게임
6	연예인
7	버튜버
8	기타
*/


-- 16. PRODUCT_SIZE
INSERT INTO PRODUCT_SIZE (PRODUCT_SIZE_ID, PRODUCT_SIZE_NAME)
VALUES (PRODUCT_SIZE_SEQ.NEXTVAL, '대');
INSERT INTO PRODUCT_SIZE (PRODUCT_SIZE_ID, PRODUCT_SIZE_NAME)
VALUES (PRODUCT_SIZE_SEQ.NEXTVAL, '중');
INSERT INTO PRODUCT_SIZE (PRODUCT_SIZE_ID, PRODUCT_SIZE_NAME)
VALUES (PRODUCT_SIZE_SEQ.NEXTVAL, '소');

SELECT *
FROM PRODUCT_SIZE;
/*
1	대
2	중
3	소
*/

-- 20. MONEY_TYPE
INSERT INTO MONEY_TYPE (MONEY_TYPE_ID, MONEY_TYPE_NAME)
VALUES (MONEY_TYPE_SEQ.NEXTVAL, '결제');
INSERT INTO MONEY_TYPE (MONEY_TYPE_ID, MONEY_TYPE_NAME)
VALUES (MONEY_TYPE_SEQ.NEXTVAL, '판매 보증금 납부');
INSERT INTO MONEY_TYPE (MONEY_TYPE_ID, MONEY_TYPE_NAME)
VALUES (MONEY_TYPE_SEQ.NEXTVAL, '구매 보증금 납부');
INSERT INTO MONEY_TYPE (MONEY_TYPE_ID, MONEY_TYPE_NAME)
VALUES (MONEY_TYPE_SEQ.NEXTVAL, '판매 보증금 환급');
INSERT INTO MONEY_TYPE (MONEY_TYPE_ID, MONEY_TYPE_NAME)
VALUES (MONEY_TYPE_SEQ.NEXTVAL, '구매 보증금 환급');
INSERT INTO MONEY_TYPE (MONEY_TYPE_ID, MONEY_TYPE_NAME)
VALUES (MONEY_TYPE_SEQ.NEXTVAL, '결제 취소');
INSERT INTO MONEY_TYPE (MONEY_TYPE_ID, MONEY_TYPE_NAME)
VALUES (MONEY_TYPE_SEQ.NEXTVAL, '결제 대금');
INSERT INTO MONEY_TYPE (MONEY_TYPE_ID, MONEY_TYPE_NAME)
VALUES (MONEY_TYPE_SEQ.NEXTVAL, '보증금 몰수');

SELECT *
FROM MONEY_TYPE;
/*
1	결제
2	판매 보증금 납부
3	구매 보증금 납부
4	판매 보증금 환급
5	구매 보증금 환급
6	결제 취소
7	결제 대금
8	보증금 몰수
*/

-- 21. MONEY_CHARGE_METHOD
INSERT INTO MONEY_CHARGE_METHOD (MONEY_CHARGE_METHOD_ID, MONEY_CHARGE_METHOD_NAME)
VALUES (MONEY_CHARGE_METHOD_SEQ.NEXTVAL, '무통장');
INSERT INTO MONEY_CHARGE_METHOD (MONEY_CHARGE_METHOD_ID, MONEY_CHARGE_METHOD_NAME)
VALUES (MONEY_CHARGE_METHOD_SEQ.NEXTVAL, '신용카드');

SELECT *
FROM MONEY_CHARGE_METHOD;
/*
1	무통장
2	신용카드
*/


-- 23. AUCTION_PERIOD
INSERT INTO AUCTION_PERIOD (AUCTION_PERIOD_ID, AUCTION_PERIOD_NAME)
VALUES (AUCTION_PERIOD_SEQ.NEXTVAL, '1일');
INSERT INTO AUCTION_PERIOD (AUCTION_PERIOD_ID, AUCTION_PERIOD_NAME)
VALUES (AUCTION_PERIOD_SEQ.NEXTVAL, '2일');
INSERT INTO AUCTION_PERIOD (AUCTION_PERIOD_ID, AUCTION_PERIOD_NAME)
VALUES (AUCTION_PERIOD_SEQ.NEXTVAL, '3일');
INSERT INTO AUCTION_PERIOD (AUCTION_PERIOD_ID, AUCTION_PERIOD_NAME)
VALUES (AUCTION_PERIOD_SEQ.NEXTVAL, '4일');
INSERT INTO AUCTION_PERIOD (AUCTION_PERIOD_ID, AUCTION_PERIOD_NAME)
VALUES (AUCTION_PERIOD_SEQ.NEXTVAL, '5일');
INSERT INTO AUCTION_PERIOD (AUCTION_PERIOD_ID, AUCTION_PERIOD_NAME)
VALUES (AUCTION_PERIOD_SEQ.NEXTVAL, '6일');
INSERT INTO AUCTION_PERIOD (AUCTION_PERIOD_ID, AUCTION_PERIOD_NAME)
VALUES (AUCTION_PERIOD_SEQ.NEXTVAL, '7일');

SELECT *
FROM AUCTION_PERIOD;
/*
1	1일
2	2일
3	3일
4	4일
5	5일
6	6일
7	7일
*/


-- 29. BID_FAILURE_TYPE
INSERT INTO BID_FAILURE_TYPE (BID_FAIL_TYPE_ID, BID_FAIL_TYPE_NAME)
VALUES (BID_FAIL_TYPE_SEQ.NEXTVAL, '결제기한만료');
INSERT INTO BID_FAILURE_TYPE (BID_FAIL_TYPE_ID, BID_FAIL_TYPE_NAME)
VALUES (BID_FAIL_TYPE_SEQ.NEXTVAL, '낙찰포기');

SELECT *
FROM BID_FAILURE_TYPE;
/*
1	결제기한만료
2	낙찰포기
*/

-- 35. PENALTY_ASSIGN_TYPE
INSERT INTO PENALTY_ASSIGN_TYPE (PENALTY_TYPE_ID, PENALTY_TYPE_NAME)
VALUES (PENALTY_TYPE_SEQ.NEXTVAL, '자동');
INSERT INTO PENALTY_ASSIGN_TYPE (PENALTY_TYPE_ID, PENALTY_TYPE_NAME)
VALUES (PENALTY_TYPE_SEQ.NEXTVAL, '수동');

SELECT *
FROM PENALTY_ASSIGN_TYPE;
/*
1	자동
2	수동
*/


-- 38. REPORT_TYPE
INSERT INTO REPORT_TYPE (REPORT_TYPE_ID, REPORT_TYPE_NAME)
VALUES (REPORT_TYPE_SEQ.NEXTVAL, '도배');
INSERT INTO REPORT_TYPE (REPORT_TYPE_ID, REPORT_TYPE_NAME)
VALUES (REPORT_TYPE_SEQ.NEXTVAL, '광고');
INSERT INTO REPORT_TYPE (REPORT_TYPE_ID, REPORT_TYPE_NAME)
VALUES (REPORT_TYPE_SEQ.NEXTVAL, '개인정보 노출');
INSERT INTO REPORT_TYPE (REPORT_TYPE_ID, REPORT_TYPE_NAME)
VALUES (REPORT_TYPE_SEQ.NEXTVAL, '불법정보');
INSERT INTO REPORT_TYPE (REPORT_TYPE_ID, REPORT_TYPE_NAME)
VALUES (REPORT_TYPE_SEQ.NEXTVAL, '음란물');
INSERT INTO REPORT_TYPE (REPORT_TYPE_ID, REPORT_TYPE_NAME)
VALUES (REPORT_TYPE_SEQ.NEXTVAL, '욕설/혐오/차별적 표현');

SELECT *
FROM REPORT_TYPE;
/*
1	도배
2	광고
3	개인정보 노출
4	불법정보
5	음란물
6	욕설/혐오/차별적 표현
*/



-- 39. REPORT_TARGET
INSERT INTO REPORT_TARGET (REPORT_TARGET_ID, REPORT_TARGET_NAME)
VALUES (REPORT_TARGET_SEQ.NEXTVAL, '상품');
INSERT INTO REPORT_TARGET (REPORT_TARGET_ID, REPORT_TARGET_NAME)
VALUES (REPORT_TARGET_SEQ.NEXTVAL, '경매');

SELECT *
FROM REPORT_TARGET;
/*
1	상품
2	경매
*/


-- 43. REPORT_RESULT
INSERT INTO REPORT_RESULT (REPORT_RESULT_ID, REPORT_RESULT_NAME)
VALUES (REPORT_RESULT_SEQ.NEXTVAL, '승인');
INSERT INTO REPORT_RESULT (REPORT_RESULT_ID, REPORT_RESULT_NAME)
VALUES (REPORT_RESULT_SEQ.NEXTVAL, '반려');

SELECT *
FROM REPORT_RESULT;
/*
1	승인
2	반려
*/
-- 12. PRODUCT_COUNTRY
INSERT INTO PRODUCT_COUNTRY (PRODUCT_COUNTRY_ID, PRODUCT_COUNTRY_NAME)
VALUES ('KR', '한국');
INSERT INTO PRODUCT_COUNTRY (PRODUCT_COUNTRY_ID, PRODUCT_COUNTRY_NAME)
VALUES ('JP', '일본');
INSERT INTO PRODUCT_COUNTRY (PRODUCT_COUNTRY_ID, PRODUCT_COUNTRY_NAME)
VALUES ('CN', '중국');
INSERT INTO PRODUCT_COUNTRY (PRODUCT_COUNTRY_ID, PRODUCT_COUNTRY_NAME)
VALUES ('US', '미국');
INSERT INTO PRODUCT_COUNTRY (PRODUCT_COUNTRY_ID, PRODUCT_COUNTRY_NAME)
VALUES ('HK', '홍콩');
INSERT INTO PRODUCT_COUNTRY (PRODUCT_COUNTRY_ID, PRODUCT_COUNTRY_NAME)
VALUES ('EU', '유럽');

SELECT *
FROM PRODUCT_COUNTRY;
/*
KR	한국
JP	일본
CN	중국
US	미국
HK	홍콩
EU	유럽
*/

--###### 추가하기 #######
-- 13. PRODUCT_MANUFACTURER
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME)
VALUES (MANUFACTURER_SEQ.NEXTVAL, ?, ?);



-- 범례테이블 데이터 생성 ======================================================
