SELECT USER
FROM DUAL;

-- 범례테이블 데이터 생성 ======================================================

-- 5. ACCOUNT_EVENT_TYPE
INSERT INTO ACCOUNT_EVENT_TYPE (ACCOUNT_EVENT_TYPE_ID, EVENT_NAME)
VALUES (ACCOUNT_EVENT_TYPE_SEQ.NEXTVAL, '가입');
INSERT INTO ACCOUNT_EVENT_TYPE (ACCOUNT_EVENT_TYPE_ID, EVENT_NAME)
VALUES (ACCOUNT_EVENT_TYPE_SEQ.NEXTVAL, '탈퇴');

SELECT *
FROM ACCOUNT_EVENT_TYPE;
/*
1	가입
2	탈퇴
*/

-- 7. ADMIN_ROLE
INSERT INTO ADMIN_ROLE (ADMIN_ROLE_ID, ADMIN_ROLE_NAME)
VALUES (ADMIN_ROLE_SEQ.NEXTVAL, '최고관리자');
INSERT INTO ADMIN_ROLE (ADMIN_ROLE_ID, ADMIN_ROLE_NAME)
VALUES (ADMIN_ROLE_SEQ.NEXTVAL, '관리자');

SELECT *
FROM ADMIN_ROLE;
/*
1	최고관리자
2	관리자
*/

-- 11. COMMON
INSERT INTO COMMON (COMMON_YN_ID, COMMON_YN_NAME)
VALUES (0, 'N'); 
INSERT INTO COMMON (COMMON_YN_ID, COMMON_YN_NAME)
VALUES (1, 'Y'); 

SELECT *
FROM COMMON;
/*
0	N
1	Y
*/




-- 14. PRODUCT_GRADE
INSERT INTO PRODUCT_GRADE (PRODUCT_GRADE_ID, PRODUCT_GRADE_NAME)
VALUES (PRODUCT_GRADE_SEQ.NEXTVAL, '최상');
INSERT INTO PRODUCT_GRADE (PRODUCT_GRADE_ID, PRODUCT_GRADE_NAME)
VALUES (PRODUCT_GRADE_SEQ.NEXTVAL, '상');
INSERT INTO PRODUCT_GRADE (PRODUCT_GRADE_ID, PRODUCT_GRADE_NAME)
VALUES (PRODUCT_GRADE_SEQ.NEXTVAL, '중');
INSERT INTO PRODUCT_GRADE (PRODUCT_GRADE_ID, PRODUCT_GRADE_NAME)
VALUES (PRODUCT_GRADE_SEQ.NEXTVAL, '하');

SELECT *
FROM PRODUCT_GRADE;
/*
1	최상
2	상
3	중
4	하
*/


-- 15. PRODUCT_GENRE
INSERT INTO PRODUCT_GENRE (PRODUCT_GENRE_ID, PRODUCT_GENRE_NAME)
VALUES (PRODUCT_GENRE_SEQ.NEXTVAL, '영화');
INSERT INTO PRODUCT_GENRE (PRODUCT_GENRE_ID, PRODUCT_GENRE_NAME)
VALUES (PRODUCT_GENRE_SEQ.NEXTVAL, '애니메이션');
INSERT INTO PRODUCT_GENRE (PRODUCT_GENRE_ID, PRODUCT_GENRE_NAME)
VALUES (PRODUCT_GENRE_SEQ.NEXTVAL, '만화(코믹스)');
INSERT INTO PRODUCT_GENRE (PRODUCT_GENRE_ID, PRODUCT_GENRE_NAME)
VALUES (PRODUCT_GENRE_SEQ.NEXTVAL, '게임');
INSERT INTO PRODUCT_GENRE (PRODUCT_GENRE_ID, PRODUCT_GENRE_NAME)
VALUES (PRODUCT_GENRE_SEQ.NEXTVAL, '연예인');
INSERT INTO PRODUCT_GENRE (PRODUCT_GENRE_ID, PRODUCT_GENRE_NAME)
VALUES (PRODUCT_GENRE_SEQ.NEXTVAL, '버튜버');
INSERT INTO PRODUCT_GENRE (PRODUCT_GENRE_ID, PRODUCT_GENRE_NAME)
VALUES (PRODUCT_GENRE_SEQ.NEXTVAL, '기타');

SELECT *
FROM PRODUCT_GENRE;
/*
1	영화
3	애니메이션
4	만화(코믹스)
5	게임
6	연예인
7	버튜버
8	기타
*/


-- 16. PRODUCT_SIZE
INSERT INTO PRODUCT_SIZE (PRODUCT_SIZE_ID, PRODUCT_SIZE_NAME)
VALUES (PRODUCT_SIZE_SEQ.NEXTVAL, '대');
INSERT INTO PRODUCT_SIZE (PRODUCT_SIZE_ID, PRODUCT_SIZE_NAME)
VALUES (PRODUCT_SIZE_SEQ.NEXTVAL, '중');
INSERT INTO PRODUCT_SIZE (PRODUCT_SIZE_ID, PRODUCT_SIZE_NAME)
VALUES (PRODUCT_SIZE_SEQ.NEXTVAL, '소');

SELECT *
FROM PRODUCT_SIZE;
/*
1	대
2	중
3	소
*/

-- 20. MONEY_TYPE
INSERT INTO MONEY_TYPE (MONEY_TYPE_ID, MONEY_TYPE_NAME)
VALUES (MONEY_TYPE_SEQ.NEXTVAL, '결제');
INSERT INTO MONEY_TYPE (MONEY_TYPE_ID, MONEY_TYPE_NAME)
VALUES (MONEY_TYPE_SEQ.NEXTVAL, '판매 보증금 납부');
INSERT INTO MONEY_TYPE (MONEY_TYPE_ID, MONEY_TYPE_NAME)
VALUES (MONEY_TYPE_SEQ.NEXTVAL, '구매 보증금 납부');
INSERT INTO MONEY_TYPE (MONEY_TYPE_ID, MONEY_TYPE_NAME)
VALUES (MONEY_TYPE_SEQ.NEXTVAL, '판매 보증금 환급');
INSERT INTO MONEY_TYPE (MONEY_TYPE_ID, MONEY_TYPE_NAME)
VALUES (MONEY_TYPE_SEQ.NEXTVAL, '구매 보증금 환급');
INSERT INTO MONEY_TYPE (MONEY_TYPE_ID, MONEY_TYPE_NAME)
VALUES (MONEY_TYPE_SEQ.NEXTVAL, '결제 취소');
INSERT INTO MONEY_TYPE (MONEY_TYPE_ID, MONEY_TYPE_NAME)
VALUES (MONEY_TYPE_SEQ.NEXTVAL, '결제 대금');
INSERT INTO MONEY_TYPE (MONEY_TYPE_ID, MONEY_TYPE_NAME)
VALUES (MONEY_TYPE_SEQ.NEXTVAL, '보증금 몰수');

SELECT *
FROM MONEY_TYPE;
/*
1	결제
2	판매 보증금 납부
3	구매 보증금 납부
4	판매 보증금 환급
5	구매 보증금 환급
6	결제 취소
7	결제 대금
8	보증금 몰수
*/

-- 21. MONEY_CHARGE_METHOD
INSERT INTO MONEY_CHARGE_METHOD (MONEY_CHARGE_METHOD_ID, MONEY_CHARGE_METHOD_NAME)
VALUES (MONEY_CHARGE_METHOD_SEQ.NEXTVAL, '무통장');
INSERT INTO MONEY_CHARGE_METHOD (MONEY_CHARGE_METHOD_ID, MONEY_CHARGE_METHOD_NAME)
VALUES (MONEY_CHARGE_METHOD_SEQ.NEXTVAL, '신용카드');

SELECT *
FROM MONEY_CHARGE_METHOD;
/*
1	무통장
2	신용카드
*/


-- 23. AUCTION_PERIOD
INSERT INTO AUCTION_PERIOD (AUCTION_PERIOD_ID, AUCTION_PERIOD_NAME)
VALUES (AUCTION_PERIOD_SEQ.NEXTVAL, '1일');
INSERT INTO AUCTION_PERIOD (AUCTION_PERIOD_ID, AUCTION_PERIOD_NAME)
VALUES (AUCTION_PERIOD_SEQ.NEXTVAL, '2일');
INSERT INTO AUCTION_PERIOD (AUCTION_PERIOD_ID, AUCTION_PERIOD_NAME)
VALUES (AUCTION_PERIOD_SEQ.NEXTVAL, '3일');
INSERT INTO AUCTION_PERIOD (AUCTION_PERIOD_ID, AUCTION_PERIOD_NAME)
VALUES (AUCTION_PERIOD_SEQ.NEXTVAL, '4일');
INSERT INTO AUCTION_PERIOD (AUCTION_PERIOD_ID, AUCTION_PERIOD_NAME)
VALUES (AUCTION_PERIOD_SEQ.NEXTVAL, '5일');
INSERT INTO AUCTION_PERIOD (AUCTION_PERIOD_ID, AUCTION_PERIOD_NAME)
VALUES (AUCTION_PERIOD_SEQ.NEXTVAL, '6일');
INSERT INTO AUCTION_PERIOD (AUCTION_PERIOD_ID, AUCTION_PERIOD_NAME)
VALUES (AUCTION_PERIOD_SEQ.NEXTVAL, '7일');

SELECT *
FROM AUCTION_PERIOD;
/*
1	1일
2	2일
3	3일
4	4일
5	5일
6	6일
7	7일
*/


-- 29. BID_FAILURE_TYPE
INSERT INTO BID_FAILURE_TYPE (BID_FAIL_TYPE_ID, BID_FAIL_TYPE_NAME)
VALUES (BID_FAIL_TYPE_SEQ.NEXTVAL, '결제기한만료');
INSERT INTO BID_FAILURE_TYPE (BID_FAIL_TYPE_ID, BID_FAIL_TYPE_NAME)
VALUES (BID_FAIL_TYPE_SEQ.NEXTVAL, '낙찰포기');

SELECT *
FROM BID_FAILURE_TYPE;
/*
1	결제기한만료
2	낙찰포기
*/

-- 35. PENALTY_ASSIGN_TYPE
INSERT INTO PENALTY_ASSIGN_TYPE (PENALTY_TYPE_ID, PENALTY_TYPE_NAME)
VALUES (PENALTY_TYPE_SEQ.NEXTVAL, '자동');
INSERT INTO PENALTY_ASSIGN_TYPE (PENALTY_TYPE_ID, PENALTY_TYPE_NAME)
VALUES (PENALTY_TYPE_SEQ.NEXTVAL, '수동');

SELECT *
FROM PENALTY_ASSIGN_TYPE;
/*
1	자동
2	수동
*/


-- 38. REPORT_TYPE
INSERT INTO REPORT_TYPE (REPORT_TYPE_ID, REPORT_TYPE_NAME)
VALUES (REPORT_TYPE_SEQ.NEXTVAL, '도배');
INSERT INTO REPORT_TYPE (REPORT_TYPE_ID, REPORT_TYPE_NAME)
VALUES (REPORT_TYPE_SEQ.NEXTVAL, '광고');
INSERT INTO REPORT_TYPE (REPORT_TYPE_ID, REPORT_TYPE_NAME)
VALUES (REPORT_TYPE_SEQ.NEXTVAL, '개인정보 노출');
INSERT INTO REPORT_TYPE (REPORT_TYPE_ID, REPORT_TYPE_NAME)
VALUES (REPORT_TYPE_SEQ.NEXTVAL, '불법정보');
INSERT INTO REPORT_TYPE (REPORT_TYPE_ID, REPORT_TYPE_NAME)
VALUES (REPORT_TYPE_SEQ.NEXTVAL, '음란물');
INSERT INTO REPORT_TYPE (REPORT_TYPE_ID, REPORT_TYPE_NAME)
VALUES (REPORT_TYPE_SEQ.NEXTVAL, '욕설/혐오/차별적 표현');

SELECT *
FROM REPORT_TYPE;
/*
1	도배
2	광고
3	개인정보 노출
4	불법정보
5	음란물
6	욕설/혐오/차별적 표현
*/



-- 39. REPORT_TARGET
INSERT INTO REPORT_TARGET (REPORT_TARGET_ID, REPORT_TARGET_NAME)
VALUES (REPORT_TARGET_SEQ.NEXTVAL, '상품');
INSERT INTO REPORT_TARGET (REPORT_TARGET_ID, REPORT_TARGET_NAME)
VALUES (REPORT_TARGET_SEQ.NEXTVAL, '경매');

SELECT *
FROM REPORT_TARGET;
/*
1	상품
2	경매
*/


-- 43. REPORT_RESULT
INSERT INTO REPORT_RESULT (REPORT_RESULT_ID, REPORT_RESULT_NAME)
VALUES (REPORT_RESULT_SEQ.NEXTVAL, '승인');
INSERT INTO REPORT_RESULT (REPORT_RESULT_ID, REPORT_RESULT_NAME)
VALUES (REPORT_RESULT_SEQ.NEXTVAL, '반려');

SELECT *
FROM REPORT_RESULT;
/*
1	승인
2	반려
*/
-- 12. PRODUCT_COUNTRY
INSERT INTO PRODUCT_COUNTRY (PRODUCT_COUNTRY_ID, PRODUCT_COUNTRY_NAME)
VALUES ('KR', '한국');
INSERT INTO PRODUCT_COUNTRY (PRODUCT_COUNTRY_ID, PRODUCT_COUNTRY_NAME)
VALUES ('JP', '일본');
INSERT INTO PRODUCT_COUNTRY (PRODUCT_COUNTRY_ID, PRODUCT_COUNTRY_NAME)
VALUES ('CN', '중국');
INSERT INTO PRODUCT_COUNTRY (PRODUCT_COUNTRY_ID, PRODUCT_COUNTRY_NAME)
VALUES ('US', '미국');
INSERT INTO PRODUCT_COUNTRY (PRODUCT_COUNTRY_ID, PRODUCT_COUNTRY_NAME)
VALUES ('HK', '홍콩');
INSERT INTO PRODUCT_COUNTRY (PRODUCT_COUNTRY_ID, PRODUCT_COUNTRY_NAME)
VALUES ('EU', '유럽');
INSERT INTO PRODUCT_COUNTRY (PRODUCT_COUNTRY_ID, PRODUCT_COUNTRY_NAME)
VALUES ('ZZ', '알 수 없음');


SELECT *
FROM PRODUCT_COUNTRY;
/*
KR	한국
JP	일본
CN	중국
US	미국
HK	홍콩
EU	유럽
*/


-- 13. PRODUCT_MANUFACTURER
-- 한국 (KR)
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME) 
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'KR', '블리츠웨이');
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME) 
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'KR', '오프로 스튜디오');
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME) 
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'KR', 'JND 스튜디오');

-- 일본 (JP)
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME)
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'JP', '굿스마일 컴퍼니');
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME) 
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'JP', '반다이');
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME) 
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'JP', '알터');
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME) 
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'JP', '메가하우스');
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME) 
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'JP', '코토부키야');

-- 미국 (US)
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME)
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'US', '사이드쇼');
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME) 
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'US', '네카');
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME) 
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'US', '해즈브로');

-- 홍콩 (HK)
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME) 
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'HK', '핫토이');
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME) 
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'HK', '쓰리제로');

-- 중국 (CN)
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME)
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'CN', '에이펙스');
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME) 
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'CN', '모쇼토이즈');

-- 유럽(EU)
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME)
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'EU', '츠메아트');

-- 알 수 없음 (ZZ)
INSERT INTO PRODUCT_MANUFACTURER (MANUFACTURER_ID, PRODUCT_COUNTRY_ID, MANUFACTURER_NAME) 
VALUES (MANUFACTURER_SEQ.NEXTVAL, 'ZZ', '제조사 미확인');

SELECT *
FROM PRODUCT_MANUFACTURER;
/*
1	KR	블리츠웨이
2	KR	오프로 스튜디오
3	KR	JND 스튜디오
4	JP	굿스마일 컴퍼니
5	JP	반다이
6	JP	알터
7	JP	메가하우스
8	JP	코토부키야
9	US	사이드쇼
10	US	네카
11	US	해즈브로
12	HK	핫토이
13	HK	쓰리제로
14	CN	에이펙스
15	CN	모쇼토이즈
16	EU	츠메아트
17	ZZ	제조사 미확인
*/

-- 범례테이블 데이터 생성 ======================================================



-- 샘플 데이터 생성 ============================================================

SELECT *
FROM USERS;

-- [1] 사용자 생성 (기본키 → 계정 → 프로필)
INSERT INTO USERS (USER_ID) VALUES (USERS_SEQ.NEXTVAL); -- 1번 사용자
INSERT INTO USER_ACCOUNT (USER_ID, USER_LOGIN_ID, USER_PASSWORD) 
VALUES (USERS_SEQ.CURRVAL, 'user01', '0123456789');
INSERT INTO USER_PROFILE (USER_ID, USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE, USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL)
VALUES (USERS_SEQ.CURRVAL, '홍길동', '9001011234567', 'hong@test.com', '01012345678', '06035', '서울 강남구 가로수길', '101호');

INSERT INTO USERS (USER_ID) VALUES (USERS_SEQ.NEXTVAL); -- 2번 사용자
INSERT INTO USER_ACCOUNT (USER_ID, USER_LOGIN_ID, USER_PASSWORD) 
VALUES (USERS_SEQ.CURRVAL, 'user02', '0123456789');
INSERT INTO USER_PROFILE (USER_ID, USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE, USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL)
VALUES (USERS_SEQ.CURRVAL, '김철수', '9205052345678', 'kim@test.com', '01098765432', '04524', '서울 중구 세종대로', '202호');


-- 사용자 전체 정보 조회
SELECT U.USER_ID, UA.USER_LOGIN_ID, UA.USER_PASSWORD
, UP.USER_NAME, UP.USER_SSN, UP.USER_EMAIL, UP.USER_PHONE
, UP.USER_ZIPCODE, UP.USER_ADDRESS, UP.USER_ADDRESS_DETAIL
FROM USERS U JOIN USER_ACCOUNT UA
ON U.USER_ID = UA.USER_ID
JOIN USER_PROFILE UP
ON UA.USER_ID = UP.USER_ID;


-- [2] 머니 충전 (2번 사용자가 경매 참여를 위해 50만 원 충전)
INSERT INTO MONEY_CHARGE_HISTORY (MONEY_CHARGE_ID, USER_ID, MONEY_CHARGE_METHOD_ID, CHARGE_AMOUNT)
VALUES (MONEY_CHARGE_SEQ.NEXTVAL, 2, 2, 500000); -- 신용카드로 50만 원 충전

SELECT *
FROM MONEY_CHARGE_HISTORY;


-- [3] 상품 등록 (1번 사용자가 핫토이 아이언맨 피규어 등록)
-- 범례: 최상(1), 애니메이션(3), 중(2), Y(1), N(0)
INSERT INTO PRODUCT (
    PRODUCT_ID, PRODUCT_RELEASE_NAME, PRODUCT_ALIAS, USER_ID, MANUFACTURER_ID, 
    PRODUCT_GRADE_ID, PRODUCT_GENRE_ID, PRODUCT_SIZE_ID, WORK_NAME, CHARACTER_NAME, 
    IS_OPENED, IS_PARTS_MISSING, DESCRIPTIONS, IMAGE_PATH_1, IMAGE_PATH_2, IMAGE_PATH_3, IS_PUBLIC
) VALUES (
    PRODUCT_SEQ.NEXTVAL, 'Hot Toys Iron Man Mark 85', '핫토이 마크85', 1, 12, 
    1, 1, 1, '어벤져스: 엔드게임', '아이언맨', 
    1, 0, '단순 개봉 풀박스입니다. 상태 매우 좋습니다.', 'images/ironman_1.png', 'images/ironman_2.png', 'images/ironman_3.png', 1
);



-- [4] 추가 이미지 등록 (PRODUCT_IMAGE 테이블 활용)
-- 상품 상세컷 
INSERT INTO PRODUCT_IMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, IMAGE_ORDER, FILE_PATH)
VALUES (PRODUCT_IMAGE_SEQ.NEXTVAL, PRODUCT_SEQ.CURRVAL, 1, 'images/ironman_4.png');

-- 상품 상세컷 2 
INSERT INTO PRODUCT_IMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, IMAGE_ORDER, FILE_PATH)
VALUES (PRODUCT_IMAGE_SEQ.NEXTVAL, PRODUCT_SEQ.CURRVAL, 2, 'images/ironman_5.png');

/*
SELECT  P.PRODUCT_ID, P.PRODUCT_RELEASE_NAME, P.PRODUCT_ALIAS
,P.USER_ID, P.MANUFACTURER_ID, P.PRODUCT_GRADE_ID, PRODUCT_GENRE_ID, PRODUCT_SIZE_ID
, P.WORK_NAME, P.CHARACTER_NAME, P.IS_OPNED, P.IS_PARTS_MISSING, P.DESCRIPTIONS
, P.IS_PUBLIC, P.IMAGE_PATH_1, P.IMAGE_PATH_2, P.IMAGE_PATH_3
*/

/*
SELECT PRODUCT_IMAGE_ID, IMAGE_ORDER, FILE_PATH
FROM PRODUCT_IMAGE
GROUP BY PRODUCT_ID;
*/

SELECT 
    P.*, 
    MAX(DECODE(PI.IMAGE_ORDER, 1, PI.FILE_PATH)) AS PHOTO_1,
    MAX(DECODE(PI.IMAGE_ORDER, 2, PI.FILE_PATH)) AS PHOTO_2
FROM PRODUCT P
LEFT JOIN PRODUCT_IMAGE PI ON P.PRODUCT_ID = PI.PRODUCT_ID
GROUP BY 
    P.PRODUCT_ID, P.PRODUCT_RELEASE_NAME, P.PRODUCT_ALIAS, P.USER_ID, P.MANUFACTURER_ID, 
    P.PRODUCT_GRADE_ID, P.PRODUCT_GENRE_ID, P.PRODUCT_SIZE_ID, P.WORK_NAME, P.CHARACTER_NAME, 
    P.PURCHASE_DATETIME, P.IS_OPENED, P.IS_PARTS_MISSING, P.DESCRIPTIONS, 
    P.IMAGE_PATH_1, P.IMAGE_PATH_2, P.IMAGE_PATH_3, P.IS_PUBLIC, P.CREATED_AT;



-- [4] 경매 등록 (등록한 상품을 7일간 경매 진행)
-- 범례: 7일(7)
INSERT INTO AUCTION_REGISTRATION (
    AUCTION_ID, PRODUCT_ID, AUCTION_TITLE, AUCTION_CONTENT, START_PRICE, AUCTION_PERIOD_ID
) VALUES (
    AUCTION_SEQ.NEXTVAL, PRODUCT_SEQ.CURRVAL, '핫토이 마크85 풀구성 급처합니다', '전시만 했던 상품입니다.', 300000, 7
);


-- [5] 입찰 참여 (2번 사용자가 35만 원에 입찰)
INSERT INTO AUCTION_BID_PARTICIPATION (
    BID_ID, AUCTION_ID, USER_ID, BID_PRICE
) VALUES (
    BID_SEQ.NEXTVAL, AUCTION_SEQ.CURRVAL, 2, 350000
);

COMMIT;



-- 샘플 데이터 생성 ============================================================



















