--● 미결제 낙찰 대상 조회 뷰 (VW_UNPAID_WINNING_TARGET)

CREATE OR REPLACE VIEW VW_UNPAID_WINNING_TARGET
AS
SELECT 
     A.AUCTION_ID          AS "경매번호"
    ,A.AUCTION_TITLE       AS "경매제목"
    ,U.USER_ID             AS "낙찰자번호"
    ,UA.USER_LOGIN_ID      AS "낙찰자ID"
    ,B.BID_PRICE           AS "낙찰금액"
    ,W.CREATED_AT          AS "낙찰일시"
     W.BID_RESULT_ID       AS "낙찰결과번호"
FROM AUCTION_WINNING_RESULT W
JOIN AUCTION_BID_PARTICIPATION B ON W.BID_ID = B.BID_ID
JOIN AUCTION_REGISTRATION A     ON B.AUCTION_ID = A.AUCTION_ID
JOIN USERS U                    ON B.USER_ID = U.USER_ID
JOIN USER_ACCOUNT UA            ON U.USER_ID = UA.USER_ID
WHERE NOT EXISTS (
    -- 이미 결제가 완료된 건 제외
    SELECT 1 
    FROM AUCTION_WINNING_PAYMENT P 
    WHERE P.BID_RESULT_ID = W.BID_RESULT_ID
)
AND NOT EXISTS (
    -- 이미 낙찰 실패 처리가 된 건 제외
    SELECT 1 
    FROM BID_FAILURE_HISTORY F 
    WHERE F.BID_RESULT_ID = W.BID_RESULT_ID
);

--------------------------------------------------------------------------------

--● 신고 통합 조회 뷰

CREATE OR REPLACE VIEW VW_REPORT_LIST
AS
SELECT 
    -- 1. 신고 기본 정보
    RS.REPORT_SUBMISSION_ID AS "신고번호",
    RS.CREATED_AT           AS "신고일시",
    RT.REPORT_TARGET_NAME   AS "신고대상구분",
    RTYPE.REPORT_TYPE_NAME  AS "신고유형",
    RS.REPORT_REASON        AS "신고사유",

    -- 2. 신고자 정보
    RS.USER_ID              AS "신고자_ID",
    UP.USER_NAME            AS "신고자명",

    -- 3. 피신고 대상 정보 (상품 또는 경매)
    -- 상품 신고일 경우 상품명, 경매 신고일 경우 경매제목을 표시
    CASE 
        WHEN PR.PRODUCT_ID IS NOT NULL THEN '상품'
        WHEN AR.AUCTION_ID IS NOT NULL THEN '경매'
        ELSE '기타'
    END AS "카테고리",
    COALESCE(P.PRODUCT_RELEASE_NAME, A.AUCTION_TITLE) AS "신고대상명",
    COALESCE(PR.PRODUCT_ID, AR.AUCTION_ID)           AS "대상코드_ID",

    -- 4. 신고 처리 현황
    RR.REPORT_RESULT_NAME   AS "처리결과",
    RP.PROCESS_REASON     AS "처리내용",
    RP.PROCESSED_AT         AS "처리일시",
    ADM.ADMIN_LOGIN_ID      AS "담당관리자"

FROM REPORT_SUBMISSION RS
-- 신고 유형 및 대상 분류 조인
LEFT JOIN REPORT_TARGET RT ON RS.REPORT_TARGET_ID = RT.REPORT_TARGET_ID
LEFT JOIN REPORT_TYPE RTYPE ON RS.REPORT_TYPE_ID = RTYPE.REPORT_TYPE_ID

-- 신고자 이름 조인
LEFT JOIN USER_PROFILE UP ON RS.USER_ID = UP.USER_ID

-- 상품 신고 상세 조인
LEFT JOIN PRODUCT_REPORT PR ON RS.REPORT_SUBMISSION_ID = PR.REPORT_SUBMISSION_ID
LEFT JOIN PRODUCT P ON PR.PRODUCT_ID = P.PRODUCT_ID

-- 경매 신고 상세 조인
LEFT JOIN AUCTION_REPORT AR ON RS.REPORT_SUBMISSION_ID = AR.REPORT_SUBMISSION_ID
LEFT JOIN AUCTION_REGISTRATION A ON AR.AUCTION_ID = A.AUCTION_ID

-- 신고 처리 정보 조인
LEFT JOIN REPORT_PROCESS RP ON RS.REPORT_SUBMISSION_ID = RP.REPORT_SUBMISSION_ID
LEFT JOIN REPORT_RESULT RR ON RP.REPORT_RESULT_ID = RR.REPORT_RESULT_ID
LEFT JOIN ADMIN_ACCOUNT ADM ON RP.ADMIN_ACCOUNT_ID = ADM.ADMIN_ACCOUNT_ID;