--CREATE OR REPLACE VIEW VW_AUCTION_WINNING_RESULT
--AS
SELECT
	  ---------- 경매 기본 정보 SELECT ----------
		AR_INFO.AUCTION_ID AS AUCTION_ID
	  , AR_INFO.PRODUCT_ID AS PRODUCT_ID
	  , AR_INFO.AUCTION_TITLE AS AUCTION_TITLE
	  , AR_INFO.AUCTION_CONTENT AS AUCTION_CONTENT
	  , AR_INFO.START_PRICE AS START_PRICE
	  , AR_INFO.CREATED_AT AS CREATED_AT
	  , AR_INFO.AUCTION_PERIOD_ID AS AUCTION_PERIOD_ID
	  
	  ---------- 경매 낙찰 정보 SELECT ----------
	  , AR_WINNING_INFO.USER_ID AS WINNING_USER_ID
	  , AR_WINNING_INFO.BID_ID AS WINNING_BID_ID
	  , AR_WINNING_INFO.BID_TIME AS WINNING_BID_TIME
	  , AR_WINNING_INFO.BID_PRICE AS WINNING_BID_PRICE
	  
	  -- 현재가 처리 (2건 이상 입찰: 2번째 입찰가 출력 | 1건 입찰 : 경매 시작가)
	  --  ㄴ 사전에 계산한 경매 현재가(낙찰가)의 계산 공식에서
	  --     2번째 값이 없을 경우(입찰이 1건일 경우) NULL 이 나오므로
	  --     그에 대한 추가 처리 진행.
	  , CASE WHEN AR_WINNING_INFO.SECOND_BID_PRICE IS NULL
			 THEN AR_INFO.START_PRICE
			 
			 ELSE AR_WINNING_INFO.SECOND_BID_PRICE
		END AS AUCTION_FINAL_PRICE
		
	  -- 경매 진행 여부 (현재 시간과 경매 종료 일시를 비교)
	  , CASE WHEN AR_INFO.AUCTION_END_DATE > SYSDATE
			 THEN 'Active' -- 경매 진행중
			 
			 ELSE 'Closed' -- 경매 종료
	    END AS AUCTION_STATUS

	  ---------- 낙찰 정보 SELECT ----------
	  , CASE WHEN AR_INFO.AUCTION_END_DATE > SYSDATE
			 THEN 'In Progress' -- 낙찰자 미확정(경매 진행중)

			 WHEN AR_INFO.AUCTION_END_DATE <= SYSDATE AND AWR.BID_RESULT_ID IS NOT NULL
				  -- 경매 종료 AND 낙찰자 확정
			 THEN 'Sold' -- 낙찰 완료

			 ELSE 'No Winner' -- 낙찰자 없음
	  END WINNING_STATUS

	  
	  -- [작성 예정] 결제 여부,  배송 상태 , 구매확정 여부
	  
FROM
	-- 경매 정보 테이블 (경매 종료 시간 포함)
	(
		SELECT AR.*
			 , CASE
				 	-- 경매 기간 1일~7일
				 	WHEN AUCTION_PERIOD_ID >= 1 AND AUCTION_PERIOD_ID <= 7
				 	THEN CREATED_AT + AUCTION_PERIOD_ID
				 	
				 	-- 8번 이상 코드 생길 경우, 이 아래에 추가 작성...
				END AS AUCTION_END_DATE
		FROM AUCTION_REGISTRATION AR
	) AR_INFO
	
	-- (입찰 기록을 기반으로) 각 경매의 <최고 입찰>의 '입찰코드' 및 '경매의 현재가(낙찰가)'
	JOIN
	(
		SELECT *
		FROM (
				SELECT ABP.*
					 , ROW_NUMBER() OVER(PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS BID_RANK
					 , LEAD(BID_PRICE) OVER(PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS SECOND_BID_PRICE
				FROM AUCTION_BID_PARTICIPATION ABP
			 )
		WHERE BID_RANK = 1
	) AR_WINNING_INFO
	ON AR_INFO.AUCTION_ID = AR_WINNING_INFO.AUCTION_ID

	-- 낙찰 결과 테이블 OUTER JOIN
	LEFT OUTER JOIN AUCTION_WINNING_RESULT AWR
	ON AR_WINNING_INFO.BID_ID = AWR.BID_ID
	
	-- 낙찰 실패 이력 테이블 OUTER JOIN
	LEFT OUTER JOIN BID_FAILURE_HISTORY BFH
	ON AWR.BID_RESULT_ID = BFH.BID_RESULT_ID
	
	-- 낙찰 입금 테이블 OUTER JOIN
	LEFT OUTER JOIN AUCTION_WINNING_PAYMENT AWP
	ON AWR.BID_RESULT_ID = AWP.BID_RESULT_ID
