SELECT USER
FROM DUAL;

-- ○ 1. 회원가입 생성 프로시저
-- 회원 가입 시 회원 고유키, 회원 계정, 회원 정보, 회원 계정이벤트 이력 등에 이력 추가
CREATE OR REPLACE PROCEDURE PRC_USER_SIGNUP
( P_USER_LOGIN_ID IN VARCHAR2
, P_USER_PASSWORD IN VARCHAR2
, P_USER_PASSWORD_CHECK IN VARCHAR2
, P_USER_NAME IN VARCHAR2
, P_USER_SSN IN CHAR
, P_USER_EMAIL IN VARCHAR2
, P_USER_PHONE IN CHAR
, P_USER_ZIPCODE IN VARCHAR2
, P_USER_ADDRESS IN VARCHAR2
, P_USER_ADDRESS_DETAIL IN VARCHAR2
)
IS
    V_HAS_ID NUMBER(1);
    V_HAS_SSN NUMBER(1);
    V_BIRTH DATE;
    V_AGE NUMBER(3);
    
    
    ERR_DUPLICATE_ID EXCEPTION;
    ERR_DUPLICATE_SSN EXCEPTION;
    ERR_INVALID_SSN EXCEPTION;
    ERR_INVALID_FORMAT_LENGTH EXCEPTION;
    ERR_UNDERAGE EXCEPTION;
    ERR_WRONG_PWD EXCEPTION;
    ERR_INVALID_EMAIL EXCEPTION;
    ERR_NULL_VALUE EXCEPTION;

BEGIN
-- NULL 검사
    IF (P_USER_LOGIN_ID IS NULL OR P_USER_PASSWORD IS NULL 
        OR P_USER_PASSWORD IS NULL OR P_USER_NAME IS NULL OR P_USER_SSN IS NULL
        OR P_USER_SSN IS NULL OR P_USER_EMAIL IS NULL OR P_USER_PHONE IS NULL
        OR P_USER_ZIPCODE IS NULL OR P_USER_ADDRESS IS NULL OR P_USER_ADDRESS_DETAIL IS NULL)   THEN
            RAISE ERR_NULL_VALUE;
    END IF;

-- 아이디 중복 검사
    SELECT COUNT(*) INTO V_HAS_ID
    FROM USER_ACCOUNT
    WHERE USER_LOGIN_ID = P_USER_LOGIN_ID;
    
    IF(V_HAS_ID != 0) THEN
        RAISE ERR_DUPLICATE_ID;
    END IF;
    
-- 아이디 조건 검사(4글자이상 12자이하)
    IF(LENGTH(P_USER_LOGIN_ID)<4 OR LENGTH(P_USER_LOGIN_ID)>12) THEN
        RAISE ERR_INVALID_FORMAT_LENGTH;
    END IF;

-- 비밀번호 조건 검사(8자이상 16자이하)
    IF(LENGTH(P_USER_PASSWORD)<8 OR LENGTH(P_USER_PASSWORD)>16) THEN
        RAISE ERR_INVALID_FORMAT_LENGTH;
    END IF;
    
-- 비밀번호 확인
    IF(P_USER_PASSWORD != P_USER_PASSWORD_CHECK) THEN
        RAISE ERR_WRONG_PWD;
    END IF;
    
-- 주민번호 유효성 검사
    IF NOT REGEXP_LIKE(P_USER_SSN, '^[0-9]{6}[1-4][0-9]{6}$') THEN
        RAISE ERR_INVALID_SSN;
    END IF;
    
-- 주민번호 중복 검사
    SELECT COUNT(*) INTO V_HAS_SSN
    FROM USER_PROFILE
    WHERE USER_SSN = P_USER_SSN;
    
    IF(V_HAS_SSN != 0) THEN
        RAISE ERR_DUPLICATE_SSN;
    END IF;

-- 주민번호 미성년자 제외 검사
    V_BIRTH := TO_DATE(
        CASE
            WHEN SUBSTR(P_USER_SSN,7,1) IN ('3','4') THEN '20'
            ELSE '19'
        END || SUBSTR(P_USER_SSN,1,6), 'YYYYMMDD'
    );

    V_AGE := TRUNC(MONTHS_BETWEEN(SYSDATE, V_BIRTH)/12);
    
    IF(V_AGE<19) THEN
        RAISE ERR_UNDERAGE;
    END IF;

-- 이메일 유효성 검사
    -- ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$
     IF NOT REGEXP_LIKE(P_USER_EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
        RAISE ERR_INVALID_EMAIL;
    END IF;

-- 1. USERS INSERT
    INSERT INTO USERS VALUES(USERS_SEQ.NEXTVAL);
    
-- 2. USER_ACCOUNT INSERT
    INSERT INTO USER_ACCOUNT
    VALUES(USERS_SEQ.CURRVAL, P_USER_LOGIN_ID, P_USER_PASSWORD);

-- 3. USER_PROFILE INSERT
    INSERT INTO USER_PROFILE
    VALUES(USERS_SEQ.CURRVAL, P_USER_NAME, P_USER_SSN, P_USER_EMAIL, P_USER_PHONE
    , P_USER_ZIPCODE, P_USER_ADDRESS, P_USER_ADDRESS_DETAIL);
    

      
-- 4. ACCOUNT_EVENT_HISTORY INSERT
    INSERT INTO ACCOUNT_EVENT_HISTORY
    VALUES(ACCOUNT_EVENT_HISTORY_SEQ.NEXTVAL, USERS_SEQ.CURRVAL, 1, SYSDATE);

-- 예외 처리
    EXCEPTION 
        WHEN ERR_DUPLICATE_ID THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20001, '이미 존재하는 아이디입니다.');
        WHEN ERR_DUPLICATE_SSN THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20002, '이미 존재하는 주민등록번호입니다.');
        WHEN ERR_INVALID_SSN THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20003, '유효하지 않은 주민등록번호입니다.');   
        WHEN ERR_INVALID_FORMAT_LENGTH THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20005, '입력 범위가 맞지 않습니다.');
        WHEN ERR_UNDERAGE THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20006, '미성년자입니다.'); 
        WHEN ERR_WRONG_PWD THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20007, '비밀번호가 일치하지 않습니다.'); 
        WHEN ERR_INVALID_EMAIL THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20008, '올바른 이메일 형식이 아닙니다.');
        WHEN ERR_NULL_VALUE THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20014, '필수 입력 항목이 누락되었습니다.');
END;
/
-- Procedure PRC_USER_SIGNUP이(가) 컴파일되었습니다.


-- ○ 3. 특정 경매코드에 대해 현재 마감기한이 지났는지 확인하는 함수
--      진행중: 0, 마감: 1, 에러: -1
CREATE OR REPLACE FUNCTION FN_IS_AUCTION_FINISHED
(P_AUCTION_ID   IN AUCTION_REGISTRATION.AUCTION_ID%TYPE
)
RETURN NUMBER
IS
    V_START_DATE    DATE;
    V_AUCTION_PERIOD NUMBER;
    V_RESULT NUMBER;
BEGIN
    -- 경매 테이블에서 등록시간과 경매기간 조회
    SELECT AR.CREATED_AT, TO_NUMBER(REGEXP_REPLACE(AP.AUCTION_PERIOD_NAME, '[^0-9]', '')) 
            INTO V_START_DATE, V_AUCTION_PERIOD
    FROM AUCTION_REGISTRATION AR 
        JOIN AUCTION_PERIOD AP
        ON AP.AUCTION_PERIOD_ID = AR.AUCTION_PERIOD_ID
    WHERE AR.AUCTION_ID = P_AUCTION_ID;
    
    IF (SYSDATE < (V_START_DATE+V_AUCTION_PERIOD)) THEN
        RETURN 0;   -- 경매 중
    ELSE
        RETURN 1;   -- 경매 종료
    END IF;
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN -1; --(경매 정보가 없는 경우에 대한 예외 처리)
        WHEN OTHERS THEN
            RETURN -1;
END;
/
--Function FN_IS_AUCTION_FINISHED이(가) 컴파일되었습니다.



CREATE OR REPLACE FUNCTION FN_GET_AUCTION_DUE_DATE
(P_AUCTION_ID   IN AUCTION_REGISTRATION.AUCTION_ID%TYPE
)
RETURN VARCHAR2
IS
    V_START_DATE    DATE;
    V_AUCTION_PERIOD NUMBER;
BEGIN
    -- 경매 테이블에서 등록시간과 경매기간 조회
    SELECT AR.CREATED_AT, TO_NUMBER(REGEXP_REPLACE(AP.AUCTION_PERIOD_NAME, '[^0-9]', '')) 
            INTO V_START_DATE, V_AUCTION_PERIOD
    FROM AUCTION_REGISTRATION AR 
        JOIN AUCTION_PERIOD AP
        ON AP.AUCTION_PERIOD_ID = AR.AUCTION_PERIOD_ID
    WHERE AR.AUCTION_ID = P_AUCTION_ID;
    
    
    RETURN TO_CHAR(V_START_DATE+V_AUCTION_PERIOD, 'YYYY-MM-DD HH24:MI');

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN '-'; 
        WHEN OTHERS THEN
            RETURN '-';
END;
/
-- Function FN_GET_AUCTION_DUE_DATE이(가) 컴파일되었습니다.


-- ○ 4. 회원 잔여 머니 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_USER_MONEY_BALANCE
(P_USER_ID IN USERS.USER_ID%TYPE
)
RETURN NUMBER
IS
    V_MONEY1    NUMBER;
    V_MONEY2    NUMBER;
BEGIN

-- 머니입출금이력테이블에서 아이디로 조회해서 금액 계산한 값 +
-- 머니 충전 이력 테이블에서 아이디로 조회해서 금액 계산한 값

    SELECT NVL(SUM(AMOUNT), 0) INTO V_MONEY1
    FROM MONEY_TRANSACTION_HISTORY
    WHERE USER_ID = P_USER_ID;
    
    SELECT NVL(SUM(CHARGE_AMOUNT),0) INTO V_MONEY2
    FROM MONEY_CHARGE_HISTORY
    WHERE USER_ID = P_USER_ID;
    
    RETURN V_MONEY1+V_MONEY2;
    
    EXCEPTION 
        WHEN OTHERS THEN
            RETURN -1;
END;
--Function FN_GET_USER_MONEY_BALANCE이(가) 컴파일되었습니다.







-- ○ 2. 회원탈퇴 프로시저
-- 회원 탈퇴 클릭 시, 회원 상세 정보 테이블에 있는 정보를 회원 탈퇴 테이블에 INSERT, 회원 계정 이벤트 이력에 INSERT
-- 진행 중인 경매가 있는지 확인, 진행 중인 입찰이 있는지 확인, 진행중인 낙찰이 있는지 확인, 잔여머니가 있는지 확인
-- 
CREATE OR REPLACE PROCEDURE PRC_USER_DELETE
( P_USER_ID IN USERS.USER_ID%TYPE
)
IS
     -- 커서 정의 (경매테이블)
     CURSOR CUR_USER_AUCTION IS
            SELECT AR.AUCTION_ID
            FROM AUCTION_REGISTRATION AR
                JOIN PRODUCT P 
            ON AR.PRODUCT_ID = P.PRODUCT_ID
            WHERE P.USER_ID = P_USER_ID;
            
    CURSOR CUR_USER_BID IS
        SELECT AR.AUCTION_ID
        FROM AUCTION_REGISTRATION AR
            JOIN AUCTION_BID_PARTICIPATION ABP
            ON ABP.AUCTION_ID = AR.AUCTION_ID
        WHERE ABP.USER_ID = P_USER_ID;

    V_AUCTION_ID AUCTION_REGISTRATION.AUCTION_ID%TYPE;
    V_BID_RESULT_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE;
    V_HAS_BID NUMBER;
    V_HAS_BID_2 NUMBER;
    V_PENALTY_SCORE    NUMBER;
    V_PENALTY_ID   PENALTY_HISTORY.PENALTY_ID%TYPE;
    V_NAME USER_PROFILE.USER_NAME%TYPE;
    V_SSN USER_PROFILE.USER_SSN%TYPE; 
    V_PHONE USER_PROFILE.USER_PHONE%TYPE; 
    V_EMAIL USER_PROFILE.USER_EMAIL%TYPE;
    V_ZIPCODE USER_PROFILE.USER_ZIPCODE%TYPE; 
    V_ADDRESS USER_PROFILE.USER_ADDRESS%TYPE;
    V_DETAIL USER_PROFILE.USER_ADDRESS_DETAIL%TYPE;
    
    ERR_HAS_ACTIVE_AUCTION EXCEPTION;
    ERR_HAS_ACTIVE_BID EXCEPTION;
    ERR_HAS_ACTIVE_WINNING EXCEPTION;
    ERR_HAS_MONEY EXCEPTION;
    ERR_HAS_PENALTY EXCEPTION;
    
BEGIN
    -- 진행 중인 경매 검사
    
        OPEN CUR_USER_AUCTION;
        LOOP
            FETCH CUR_USER_AUCTION INTO V_AUCTION_ID;
            EXIT WHEN CUR_USER_AUCTION%NOTFOUND;
            
            IF(FN_IS_AUCTION_FINISHED(V_AUCTION_ID) = 0) THEN
                CLOSE CUR_USER_AUCTION;
                RAISE ERR_HAS_ACTIVE_AUCTION;
            END IF;
        END LOOP;
        CLOSE CUR_USER_AUCTION;
        
    -- 진행 중인 입찰 검사
        -- 입찰 참여 테이블에서 USER_ID로 조회해서 나온 경매코드들로
        -- 그 경매코드가 진행중인지 검사
        
        OPEN CUR_USER_BID;
        LOOP
            FETCH CUR_USER_BID INTO V_AUCTION_ID;
            EXIT WHEN CUR_USER_BID%NOTFOUND;
            
            IF(FN_IS_AUCTION_FINISHED(V_AUCTION_ID) = 0) THEN
                CLOSE CUR_USER_BID;
                RAISE ERR_HAS_ACTIVE_BID;
            END IF;
        END LOOP;
         CLOSE CUR_USER_BID;

        -- 진행 중인 낙찰 검사
            SELECT COUNT(*) INTO V_HAS_BID
            FROM AUCTION_WINNING_RESULT AWR
            JOIN AUCTION_BID_PARTICIPATION ABP ON AWR.BID_ID = ABP.BID_ID
            WHERE ABP.USER_ID = P_USER_ID
            AND AWR.BID_RESULT_ID NOT IN (SELECT BID_RESULT_ID FROM BID_FAILURE_HISTORY) -- 실패 이력 없고
            AND AWR.BID_RESULT_ID NOT IN ( -- 거래 완료 이력도 없는 것 카운트
                SELECT BID_RESULT_ID FROM AUCTION_WINNING_PAYMENT AWP
                JOIN DELIVERY_COMPLETED DC ON AWP.PAYMENT_ID = DC.PAYMENT_ID
                JOIN PURCHASE_CONFIRM_HISTORY PCH ON DC.SHIPPING_ID = PCH.SHIPPING_ID
                JOIN TRANSACTION_COMPLETED TC ON PCH.PURCHASE_CONFIRM_ID = TC.PURCHASE_CONFIRM_ID);

            IF V_HAS_BID > 0 THEN
                RAISE ERR_HAS_ACTIVE_WINNING;
            END IF;
        
    -- 잔여머니가 있는지
        IF (FN_GET_USER_MONEY_BALANCE(P_USER_ID)>0) THEN
            RAISE ERR_HAS_MONEY;
        END IF;
    
    -- 회원의 상태가 영구정지 상태인지
        SELECT NVL(SUM(PENALTY_SCORE), 0) INTO V_PENALTY_SCORE
        FROM PENALTY_HISTORY
        WHERE USER_ID = P_USER_ID
        AND PENALTY_ID NOT IN (SELECT PENALTY_ID FROM PENALTY_CANCEL);

        IF V_PENALTY_SCORE >= 4 THEN
            RAISE ERR_HAS_PENALTY;
        END IF;

    
    -- USER_PROFILE 조회
        SELECT USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE
        , USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL 
        INTO V_NAME, V_SSN, V_EMAIL, V_PHONE, V_ZIPCODE, V_ADDRESS, V_DETAIL
        FROM USER_PROFILE
        WHERE USER_ID = P_USER_ID;

    -- DELETED_USER INSERT
        INSERT INTO DELETED_USER(USER_ID, USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE, USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL)
        VALUES(P_USER_ID, V_NAME, V_SSN, V_EMAIL, V_PHONE, V_ZIPCODE, V_ADDRESS, V_DETAIL);
    
    -- USER_PROFILE DELETE
        DELETE
        FROM USER_PROFILE
        WHERE USER_ID = P_USER_ID;

    -- ACCOUNT_EVENT_HISTORY INSERT
        INSERT INTO ACCOUNT_EVENT_HISTORY
        VALUES(ACCOUNT_EVENT_HISTORY_SEQ.NEXTVAL, P_USER_ID, 2, SYSDATE);
    
    EXCEPTION
        WHEN ERR_HAS_ACTIVE_AUCTION THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20016, '진행 중인 경매가 존재합니다.');
        WHEN ERR_HAS_ACTIVE_BID THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20026, '진행 중인 입찰이 존재합니다.');
        WHEN ERR_HAS_ACTIVE_WINNING THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20027, '진행 중인 낙찰이 존재합니다.');
        WHEN ERR_HAS_PENALTY THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20028, '영구정지 회원은 탈퇴가 불가능합니다.');
        WHEN ERR_HAS_MONEY THEN   
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20029, '잔여머니가 존재합니다.');
    
END;
/


-- 뷰 목록 ======================================================================

-- 1. 회원 정보 조회 뷰 VW_USER_INFO
CREATE OR REPLACE VIEW VW_USER_INFO
AS
SELECT U.USER_ID, UA.USER_LOGIN_ID, UA.USER_PASSWORD
, UP.USER_NAME, UP.USER_SSN, UP.USER_EMAIL, UP.USER_PHONE
, UP.USER_ZIPCODE, UP.USER_ADDRESS, UP.USER_ADDRESS_DETAIL
, FN_GET_USER_MONEY_BALANCE(U.USER_ID) AS TOTAL_MONEY
FROM USERS U JOIN USER_ACCOUNT UA
ON U.USER_ID = UA.USER_ID
JOIN USER_PROFILE UP
ON UA.USER_ID = UP.USER_ID;

SELECT *
FROM VW_USER_INFO;
/

-- 2. 상품 통합 조회  VW_PRODUCT_LIST
CREATE OR REPLACE VIEW VW_PRODUCT_LIST
AS
SELECT 
    P.PRODUCT_ID, P.USER_ID, P.MANUFACTURER_ID, PM.MANUFACTURER_NAME, PM.PRODUCT_COUNTRY_ID, PC.PRODUCT_COUNTRY_NAME
    , P.PRODUCT_GRADE_ID, PG.PRODUCT_GRADE_NAME, P.PRODUCT_GENRE_ID, PGR.PRODUCT_GENRE_NAME, P.PRODUCT_SIZE_ID, PS.PRODUCT_SIZE_NAME
    , P.PRODUCT_RELEASE_NAME, P.PRODUCT_ALIAS, P.WORK_NAME, P.CHARACTER_NAME, P.PURCHASE_DATETIME
    ,CASE WHEN P.IS_OPENED = 0 THEN '개봉' ELSE '미개봉' END AS IS_OPENED
    ,CASE WHEN P.IS_PARTS_MISSING = 0 THEN '정상' ELSE '누락' END AS IS_PARTS_MISSING
    ,P.DESCRIPTIONS
    ,P.IMAGE_PATH_1
    ,P.IMAGE_PATH_2
    ,P.IMAGE_PATH_3
    ,MAX(DECODE(PI.IMAGE_ORDER, 1, PI.FILE_PATH)) AS IMAGE_PATH_4
    ,MAX(DECODE(PI.IMAGE_ORDER, 2, PI.FILE_PATH)) AS IMAGE_PATH_5
    ,MAX(DECODE(PI.IMAGE_ORDER, 3, PI.FILE_PATH)) AS IMAGE_PATH_6
    ,MAX(DECODE(PI.IMAGE_ORDER, 4, PI.FILE_PATH)) AS IMAGE_PATH_7
    ,MAX(DECODE(PI.IMAGE_ORDER, 5, PI.FILE_PATH)) AS IMAGE_PATH_8
    ,MAX(DECODE(PI.IMAGE_ORDER, 6, PI.FILE_PATH)) AS IMAGE_PATH_9
    ,MAX(DECODE(PI.IMAGE_ORDER, 7, PI.FILE_PATH)) AS IMAGE_PATH_10
    ,CASE WHEN P.IS_PUBLIC = 0 THEN '비공개' ELSE '공개' END AS IS_PUBLIC
    ,TO_CHAR(P.CREATED_AT, 'YYYY-MM-DD') AS CREATED_AT
FROM PRODUCT P
    JOIN PRODUCT_MANUFACTURER PM ON P.MANUFACTURER_ID = PM.MANUFACTURER_ID
    JOIN PRODUCT_COUNTRY PC      ON PM.PRODUCT_COUNTRY_ID = PC.PRODUCT_COUNTRY_ID
    JOIN PRODUCT_GRADE PG        ON P.PRODUCT_GRADE_ID = PG.PRODUCT_GRADE_ID
    JOIN PRODUCT_GENRE PGR       ON P.PRODUCT_GENRE_ID = PGR.PRODUCT_GENRE_ID
    JOIN PRODUCT_SIZE PS         ON P.PRODUCT_SIZE_ID = PS.PRODUCT_SIZE_ID
    LEFT JOIN PRODUCT_IMAGE PI   ON P.PRODUCT_ID = PI.PRODUCT_ID
GROUP BY 
    P.PRODUCT_ID, P.USER_ID,
    P.MANUFACTURER_ID, PM.MANUFACTURER_NAME, PM.PRODUCT_COUNTRY_ID, PC.PRODUCT_COUNTRY_NAME, 
    P.PRODUCT_GRADE_ID, PG.PRODUCT_GRADE_NAME,
    P.PRODUCT_GENRE_ID, PGR.PRODUCT_GENRE_NAME, 
    P.PRODUCT_SIZE_ID, PS.PRODUCT_SIZE_NAME, 
    P.PRODUCT_RELEASE_NAME, P.PRODUCT_ALIAS, P.WORK_NAME, P.CHARACTER_NAME,
    P.PURCHASE_DATETIME, P.IS_OPENED, P.IS_PARTS_MISSING, P.DESCRIPTIONS,
    P.IMAGE_PATH_1, P.IMAGE_PATH_2, P.IMAGE_PATH_3, P.IS_PUBLIC, P.CREATED_AT;
    
    





-- 뷰	경매 목록 조회 뷰	VW_AUCTION_LIST
/*
CREATE OR REPLACE VIEW VW_AUCTION_LIST
AS
SELECT 
    AR.AUCTION_ID, AR.AUCTION_TITLE, AR.AUCTION_CONTENT, AR.START_PRICE,
    AR.AUCTION_PERIOD_ID, AP.AUCTION_PERIOD_NAME,
    TO_CHAR(AR.CREATED_AT, 'YYYY-MM-DD HH24:MI') AS AUCTION_START_DATE,
    FN_GET_AUCTION_DUE_DATE(AR.AUCTION_ID) AS AUCTION_END_DATE,
    CASE WHEN FN_IS_AUCTION_FINISHED(AR.AUCTION_ID) = 0 THEN '경매 진행중'
        ELSE '경매 마감' 
        END AS IS_FINISHED,
    VPI.PRODUCT_ID, VPI.PRODUCT_RELEASE_NAME, VPI.PRODUCT_ALIAS,
    VPI.MANUFACTURER_NAME, VPI.PRODUCT_GRADE_NAME, VPI.IMAGE_PATH_1,
    (
        SELECT BID_PRICE
        FROM (
            SELECT BID_PRICE, 
                   ROW_NUMBER() OVER (ORDER BY BID_PRICE DESC, CREATED_AT ASC) AS RANK
            FROM AUCTION_BID_PARTICIPATION
            WHERE AUCTION_ID = AR.AUCTION_ID
        )
        WHERE RANK = 2
    ) AS BID_CURRENT_PRICE, 
    (SELECT MAX(BID_PRICE) FROM AUCTION_BID_PARTICIPATION WHERE AUCTION_ID = AR.AUCTION_ID) AS BID_MAX_PRICE,
    (SELECT COUNT(*) FROM AUCTION_BID_PARTICIPATION WHERE AUCTION_ID = AR.AUCTION_ID) AS BID_COUNT
FROM AUCTION_REGISTRATION AR
    JOIN VW_PRODUCT_LIST VPI ON AR.PRODUCT_ID = VPI.PRODUCT_ID
    JOIN AUCTION_PERIOD AP   ON AR.AUCTION_PERIOD_ID = AP.AUCTION_PERIOD_ID
;
*/


CREATE OR REPLACE VIEW VW_AUCTION_LIST
AS
WITH BID_RANK AS (
    SELECT 
        AUCTION_ID, BID_PRICE,
        ROW_NUMBER() OVER (PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS RK
    FROM AUCTION_BID_PARTICIPATION
)
SELECT 
    AR.AUCTION_ID, AR.AUCTION_TITLE, AR.AUCTION_CONTENT, AR.START_PRICE,
    AR.AUCTION_PERIOD_ID, AP.AUCTION_PERIOD_NAME,
    TO_CHAR(AR.CREATED_AT, 'YYYY-MM-DD HH24:MI') AS AUCTION_START_DATE,
    FN_GET_AUCTION_DUE_DATE(AR.AUCTION_ID) AS AUCTION_END_DATE,
    CASE WHEN FN_IS_AUCTION_FINISHED(AR.AUCTION_ID) = 0 THEN '경매 진행중'
         ELSE '경매 마감' 
    END AS IS_FINISHED,
    VPI.PRODUCT_ID, VPI.PRODUCT_RELEASE_NAME, VPI.PRODUCT_ALIAS,
    VPI.MANUFACTURER_NAME, VPI.PRODUCT_GRADE_NAME, VPI.IMAGE_PATH_1,
    NVL((SELECT BID_PRICE FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 2), AR.START_PRICE) AS BID_CURRENT_PRICE,
    (SELECT BID_PRICE FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 1) AS BID_MAX_PRICE,
    (SELECT COUNT(*) FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID) AS BID_COUNT
FROM AUCTION_REGISTRATION AR
JOIN VW_PRODUCT_LIST VPI ON AR.PRODUCT_ID = VPI.PRODUCT_ID
JOIN AUCTION_PERIOD AP   ON AR.AUCTION_PERIOD_ID = AP.AUCTION_PERIOD_ID;

SELECT *
FROM VW_AUCTION_LIST;




/*
CREATE OR REPLACE VIEW VW_AUCTION_LIST
AS
WITH BID_RANK AS (
    -- 모든 입찰 기록에 대해 경매별 순위를 미리 매김
    SELECT 
        AUCTION_ID,
        BID_PRICE,
        ROW_NUMBER() OVER (PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, CREATED_AT ASC) AS RK
    FROM AUCTION_BID_PARTICIPATION
)
SELECT 
    AR.AUCTION_ID, AR.AUCTION_TITLE, AR.AUCTION_CONTENT, AR.START_PRICE,
    AR.AUCTION_PERIOD_ID, AP.AUCTION_PERIOD_NAME,
    TO_CHAR(AR.CREATED_AT, 'YYYY-MM-DD HH24:MI') AS AUCTION_START_DATE,
    FN_GET_AUCTION_DUE_DATE(AR.AUCTION_ID) AS AUCTION_END_DATE,
    CASE WHEN FN_IS_AUCTION_FINISHED(AR.AUCTION_ID) = 0 THEN '경매 진행중'
         ELSE '경매 마감' 
    END AS IS_FINISHED,
    VPI.PRODUCT_ID, VPI.PRODUCT_RELEASE_NAME, VPI.PRODUCT_ALIAS,
    VPI.MANUFACTURER_NAME, VPI.PRODUCT_GRADE_NAME, VPI.IMAGE_PATH_1,
    
    -- 2등 가격 (RK=2인 데이터만 가져옴)
    (SELECT BID_PRICE FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 2) AS BID_CURRENT_PRICE,
    
    -- 1등 가격 (RK=1인 데이터만 가져옴)
    (SELECT BID_PRICE FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 1) AS BID_MAX_PRICE,
    
    -- 입찰 건수
    (SELECT COUNT(*) FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID) AS BID_COUNT
FROM AUCTION_REGISTRATION AR
JOIN VW_PRODUCT_LIST VPI ON AR.PRODUCT_ID = VPI.PRODUCT_ID
JOIN AUCTION_PERIOD AP   ON AR.AUCTION_PERIOD_ID = AP.AUCTION_PERIOD_ID;
*/

-- 뷰	경매 상세 조회 뷰	VW_AUCTION_DETAIL
-- 뷰	경매 현재 순위 조회 뷰	VW_AUCTION_BID_RANK
-- 뷰	경매 낙찰 결과 조회 뷰	VW_AUCTION_WINNING_RESULT
-- 뷰	내 입찰 경매 조회 뷰	VW_MY_BIDDING_AUCTION
-- 뷰	내 낙찰 상품 조회 뷰	VW_MY_WINNING_AUCTION
-- 뷰	내 판매 경매 조회 뷰	VW_MY_SELLING_AUCTION

-- 뷰	머니 거래 내역 조회 뷰	VW_MONEY_HISTORY
-- 뷰	회원 패널티 요약 조회 뷰	VW_USER_PENALTY_SUMMARY
-- 뷰	회원 활성 패널티 조회 뷰	VW_USER_ACTIVE_PENALTY
-- 뷰	신고 목록 조회 뷰	VW_REPORT_LIST
-- 뷰	상품 신고 조회 뷰	VW_PRODUCT_REPORT_LIST
-- 뷰	경매 신고 조회 뷰	VW_AUCTION_REPORT_LIST
-- 뷰	관리자 경매 모니터링 조회 뷰	VW_ADMIN_AUCTION_MONITOR
-- 뷰	관리자 회원 제재 조회 뷰	VW_ADMIN_USER_PENALTY
-- 뷰	자동 구매확정 대상 조회 뷰	VW_AUTO_PURCHASE_CONFIRM_TARGET
-- 뷰	미결제 낙찰 대상 조회 뷰	VW_UNPAID_WINNING_TARGET
-- 뷰	경매 종료 대상 조회 뷰	VW_AUCTION_CLOSE_TARGET




-- 뷰 목록 ======================================================================