SELECT USER
FROM DUAL;

-- ○ 1. 회원가입 생성 프로시저
-- 회원 가입 시 회원 고유키, 회원 계정, 회원 정보, 회원 계정이벤트 이력 등에 이력 추가
CREATE OR REPLACE PROCEDURE PRC_USER_SIGNUP
( P_USER_LOGIN_ID IN VARCHAR2
, P_USER_PASSWORD IN VARCHAR2
, P_USER_PASSWORD_CHECK IN VARCHAR2
, P_USER_NAME IN VARCHAR2
, P_USER_SSN IN CHAR
, P_USER_EMAIL IN VARCHAR2
, P_USER_PHONE IN CHAR
, P_USER_ZIPCODE IN VARCHAR2
, P_USER_ADDRESS IN VARCHAR2
, P_USER_ADDRESS_DETAIL IN VARCHAR2
)
IS
    V_HAS_ID NUMBER(1);
    V_HAS_SSN NUMBER(1);
    V_BIRTH DATE;
    V_AGE NUMBER(3);
    
    
    ERR_DUPLICATE_ID EXCEPTION;
    ERR_DUPLICATE_SSN EXCEPTION;
    ERR_INVALID_SSN EXCEPTION;
    ERR_INVALID_FORMAT_LENGTH EXCEPTION;
    ERR_UNDERAGE EXCEPTION;
    ERR_WRONG_PWD EXCEPTION;
    ERR_INVALID_EMAIL EXCEPTION;
    ERR_NULL_VALUE EXCEPTION;

BEGIN
-- NULL 검사
    IF (P_USER_LOGIN_ID IS NULL OR P_USER_PASSWORD IS NULL 
        OR P_USER_PASSWORD IS NULL OR P_USER_NAME IS NULL OR P_USER_SSN IS NULL
        OR P_USER_SSN IS NULL OR P_USER_EMAIL IS NULL OR P_USER_PHONE IS NULL
        OR P_USER_ZIPCODE IS NULL OR P_USER_ADDRESS IS NULL OR P_USER_ADDRESS_DETAIL IS NULL)   THEN
            RAISE ERR_NULL_VALUE;
    END IF;

-- 아이디 중복 검사
    SELECT COUNT(*) INTO V_HAS_ID
    FROM USER_ACCOUNT
    WHERE USER_LOGIN_ID = P_USER_LOGIN_ID;
    
    IF(V_HAS_ID != 0) THEN
        RAISE ERR_DUPLICATE_ID;
    END IF;
    
-- 아이디 조건 검사(4글자이상 12자이하)
    IF(LENGTH(P_USER_LOGIN_ID)<4 OR LENGTH(P_USER_LOGIN_ID)>12) THEN
        RAISE ERR_INVALID_FORMAT_LENGTH;
    END IF;

-- 비밀번호 조건 검사(8자이상 16자이하)
    IF(LENGTH(P_USER_PASSWORD)<8 OR LENGTH(P_USER_PASSWORD)>16) THEN
        RAISE ERR_INVALID_FORMAT_LENGTH;
    END IF;
    
-- 비밀번호 확인
    IF(P_USER_PASSWORD != P_USER_PASSWORD_CHECK) THEN
        RAISE ERR_WRONG_PWD;
    END IF;
    
-- 주민번호 유효성 검사
    IF NOT REGEXP_LIKE(P_USER_SSN, '^[0-9]{6}[1-4][0-9]{6}$') THEN
        RAISE ERR_INVALID_SSN;
    END IF;
    
-- 주민번호 중복 검사
    SELECT COUNT(*) INTO V_HAS_SSN
    FROM USER_PROFILE
    WHERE USER_SSN = P_USER_SSN;
    
    IF(V_HAS_SSN != 0) THEN
        RAISE ERR_DUPLICATE_SSN;
    END IF;

-- 주민번호 미성년자 제외 검사
    V_BIRTH := TO_DATE(
        CASE
            WHEN SUBSTR(P_USER_SSN,7,1) IN ('3','4') THEN '20'
            ELSE '19'
        END || SUBSTR(P_USER_SSN,1,6), 'YYYYMMDD'
    );

    V_AGE := TRUNC(MONTHS_BETWEEN(SYSDATE, V_BIRTH)/12);
    
    IF(V_AGE<19) THEN
        RAISE ERR_UNDERAGE;
    END IF;

-- 이메일 유효성 검사
    -- ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$
     IF NOT REGEXP_LIKE(P_USER_EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
        RAISE ERR_INVALID_EMAIL;
    END IF;

-- 1. USERS INSERT
    INSERT INTO USERS VALUES(USERS_SEQ.NEXTVAL);
    
-- 2. USER_ACCOUNT INSERT
    INSERT INTO USER_ACCOUNT
    VALUES(USERS_SEQ.CURRVAL, P_USER_LOGIN_ID, P_USER_PASSWORD);

-- 3. USER_PROFILE INSERT
    INSERT INTO USER_PROFILE
    VALUES(USERS_SEQ.CURRVAL, P_USER_NAME, P_USER_SSN, P_USER_EMAIL, P_USER_PHONE
    , P_USER_ZIPCODE, P_USER_ADDRESS, P_USER_ADDRESS_DETAIL);
    

      
-- 4. ACCOUNT_EVENT_HISTORY INSERT
    INSERT INTO ACCOUNT_EVENT_HISTORY
    VALUES(ACCOUNT_EVENT_HISTORY_SEQ.NEXTVAL, USERS_SEQ.CURRVAL, 1, SYSDATE);

-- 예외 처리
    EXCEPTION 
        WHEN ERR_DUPLICATE_ID THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20001, '이미 존재하는 아이디입니다.');
        WHEN ERR_DUPLICATE_SSN THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20002, '이미 존재하는 주민등록번호입니다.');
        WHEN ERR_INVALID_SSN THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20003, '유효하지 않은 주민등록번호입니다.');   
        WHEN ERR_INVALID_FORMAT_LENGTH THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20005, '입력 범위가 맞지 않습니다.');
        WHEN ERR_UNDERAGE THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20006, '미성년자입니다.'); 
        WHEN ERR_WRONG_PWD THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20007, '비밀번호가 일치하지 않습니다.'); 
        WHEN ERR_INVALID_EMAIL THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20008, '올바른 이메일 형식이 아닙니다.');
        WHEN ERR_NULL_VALUE THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20014, '필수 입력 항목이 누락되었습니다.');
END;
/
-- Procedure PRC_USER_SIGNUP이(가) 컴파일되었습니다.


-- ○ 3. 특정 경매코드에 대해 현재 마감기한이 지났는지 확인하는 함수
--      진행중: 0, 마감: 1, 에러: -1
CREATE OR REPLACE FUNCTION FN_IS_AUCTION_FINISHED
(P_AUCTION_ID   IN AUCTION_REGISTRATION.AUCTION_ID%TYPE
)
RETURN NUMBER
IS
    V_START_DATE    DATE;
    V_AUCTION_PERIOD NUMBER;
    V_RESULT NUMBER;
BEGIN
    -- 경매 테이블에서 등록시간과 경매기간 조회
    SELECT AR.CREATED_AT, TO_NUMBER(REGEXP_REPLACE(AP.AUCTION_PERIOD_NAME, '[^0-9]', '')) 
            INTO V_START_DATE, V_AUCTION_PERIOD
    FROM AUCTION_REGISTRATION AR 
        JOIN AUCTION_PERIOD AP
        ON AP.AUCTION_PERIOD_ID = AR.AUCTION_PERIOD_ID
    WHERE AR.AUCTION_ID = P_AUCTION_ID;
    
    IF (SYSDATE < (V_START_DATE+V_AUCTION_PERIOD)) THEN
        RETURN 0;   -- 경매 중
    ELSE
        RETURN 1;   -- 경매 종료
    END IF;
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN -1; --(경매 정보가 없는 경우에 대한 예외 처리)
        WHEN OTHERS THEN
            RETURN -1;
END;
/
--Function FN_IS_AUCTION_FINISHED이(가) 컴파일되었습니다.



CREATE OR REPLACE FUNCTION FN_GET_AUCTION_DUE_DATE
(P_AUCTION_ID   IN AUCTION_REGISTRATION.AUCTION_ID%TYPE
)
RETURN VARCHAR2
IS
    V_START_DATE    DATE;
    V_AUCTION_PERIOD NUMBER;
BEGIN
    -- 경매 테이블에서 등록시간과 경매기간 조회
    SELECT AR.CREATED_AT, TO_NUMBER(REGEXP_REPLACE(AP.AUCTION_PERIOD_NAME, '[^0-9]', '')) 
            INTO V_START_DATE, V_AUCTION_PERIOD
    FROM AUCTION_REGISTRATION AR 
        JOIN AUCTION_PERIOD AP
        ON AP.AUCTION_PERIOD_ID = AR.AUCTION_PERIOD_ID
    WHERE AR.AUCTION_ID = P_AUCTION_ID;
    
    
    RETURN TO_CHAR(V_START_DATE+V_AUCTION_PERIOD, 'YYYY-MM-DD HH24:MI');

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN '-'; 
        WHEN OTHERS THEN
            RETURN '-';
END;
/
-- Function FN_GET_AUCTION_DUE_DATE이(가) 컴파일되었습니다.


-- ○ 4. 회원 잔여 머니 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_USER_MONEY_BALANCE
(P_USER_ID IN USERS.USER_ID%TYPE
)
RETURN NUMBER
IS
    V_MONEY1    NUMBER;
    V_MONEY2    NUMBER;
BEGIN

-- 머니입출금이력테이블에서 아이디로 조회해서 금액 계산한 값 +
-- 머니 충전 이력 테이블에서 아이디로 조회해서 금액 계산한 값

    SELECT NVL(SUM(AMOUNT), 0) INTO V_MONEY1
    FROM MONEY_TRANSACTION_HISTORY
    WHERE USER_ID = P_USER_ID;
    
    SELECT NVL(SUM(CHARGE_AMOUNT),0) INTO V_MONEY2
    FROM MONEY_CHARGE_HISTORY
    WHERE USER_ID = P_USER_ID;
    
    RETURN V_MONEY1+V_MONEY2;
    
    EXCEPTION 
        WHEN OTHERS THEN
            RETURN -1;
END;
--Function FN_GET_USER_MONEY_BALANCE이(가) 컴파일되었습니다.







-- ○ 2. 회원탈퇴 프로시저
-- 회원 탈퇴 클릭 시, 회원 상세 정보 테이블에 있는 정보를 회원 탈퇴 테이블에 INSERT, 회원 계정 이벤트 이력에 INSERT
-- 진행 중인 경매가 있는지 확인, 진행 중인 입찰이 있는지 확인, 진행중인 낙찰이 있는지 확인, 잔여머니가 있는지 확인
-- 
CREATE OR REPLACE PROCEDURE PRC_USER_DELETE
( P_USER_ID IN USERS.USER_ID%TYPE
)
IS
     -- 커서 정의 (경매테이블)
     CURSOR CUR_USER_AUCTION IS
            SELECT AR.AUCTION_ID
            FROM AUCTION_REGISTRATION AR
                JOIN PRODUCT P 
            ON AR.PRODUCT_ID = P.PRODUCT_ID
            WHERE P.USER_ID = P_USER_ID;
            
    CURSOR CUR_USER_BID IS
        SELECT AR.AUCTION_ID
        FROM AUCTION_REGISTRATION AR
            JOIN AUCTION_BID_PARTICIPATION ABP
            ON ABP.AUCTION_ID = AR.AUCTION_ID
        WHERE ABP.USER_ID = P_USER_ID;

    V_AUCTION_ID AUCTION_REGISTRATION.AUCTION_ID%TYPE;
    V_BID_RESULT_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE;
    V_HAS_BID NUMBER;
    V_HAS_BID_2 NUMBER;
    V_PENALTY_SCORE    NUMBER;
    V_PENALTY_ID   PENALTY_HISTORY.PENALTY_ID%TYPE;
    V_NAME USER_PROFILE.USER_NAME%TYPE;
    V_SSN USER_PROFILE.USER_SSN%TYPE; 
    V_PHONE USER_PROFILE.USER_PHONE%TYPE; 
    V_EMAIL USER_PROFILE.USER_EMAIL%TYPE;
    V_ZIPCODE USER_PROFILE.USER_ZIPCODE%TYPE; 
    V_ADDRESS USER_PROFILE.USER_ADDRESS%TYPE;
    V_DETAIL USER_PROFILE.USER_ADDRESS_DETAIL%TYPE;
    
    ERR_HAS_ACTIVE_AUCTION EXCEPTION;
    ERR_HAS_ACTIVE_BID EXCEPTION;
    ERR_HAS_ACTIVE_WINNING EXCEPTION;
    ERR_HAS_MONEY EXCEPTION;
    ERR_HAS_PENALTY EXCEPTION;
    
BEGIN
    -- 진행 중인 경매 검사
    
        OPEN CUR_USER_AUCTION;
        LOOP
            FETCH CUR_USER_AUCTION INTO V_AUCTION_ID;
            EXIT WHEN CUR_USER_AUCTION%NOTFOUND;
            
            IF(FN_IS_AUCTION_FINISHED(V_AUCTION_ID) = 0) THEN
                CLOSE CUR_USER_AUCTION;
                RAISE ERR_HAS_ACTIVE_AUCTION;
            END IF;
        END LOOP;
        CLOSE CUR_USER_AUCTION;
        
    -- 진행 중인 입찰 검사
        -- 입찰 참여 테이블에서 USER_ID로 조회해서 나온 경매코드들로
        -- 그 경매코드가 진행중인지 검사
        
        OPEN CUR_USER_BID;
        LOOP
            FETCH CUR_USER_BID INTO V_AUCTION_ID;
            EXIT WHEN CUR_USER_BID%NOTFOUND;
            
            IF(FN_IS_AUCTION_FINISHED(V_AUCTION_ID) = 0) THEN
                CLOSE CUR_USER_BID;
                RAISE ERR_HAS_ACTIVE_BID;
            END IF;
        END LOOP;
         CLOSE CUR_USER_BID;

        -- 진행 중인 낙찰 검사
            SELECT COUNT(*) INTO V_HAS_BID
            FROM AUCTION_WINNING_RESULT AWR
            JOIN AUCTION_BID_PARTICIPATION ABP ON AWR.BID_ID = ABP.BID_ID
            WHERE ABP.USER_ID = P_USER_ID
            AND AWR.BID_RESULT_ID NOT IN (SELECT BID_RESULT_ID FROM BID_FAILURE_HISTORY) -- 실패 이력 없고
            AND AWR.BID_RESULT_ID NOT IN ( -- 거래 완료 이력도 없는 것 카운트
                SELECT BID_RESULT_ID FROM AUCTION_WINNING_PAYMENT AWP
                JOIN DELIVERY_COMPLETED DC ON AWP.PAYMENT_ID = DC.PAYMENT_ID
                JOIN PURCHASE_CONFIRM_HISTORY PCH ON DC.SHIPPING_ID = PCH.SHIPPING_ID
                JOIN TRANSACTION_COMPLETED TC ON PCH.PURCHASE_CONFIRM_ID = TC.PURCHASE_CONFIRM_ID);

            IF V_HAS_BID > 0 THEN
                RAISE ERR_HAS_ACTIVE_WINNING;
            END IF;
        
    -- 잔여머니가 있는지
        IF (FN_GET_USER_MONEY_BALANCE(P_USER_ID)>0) THEN
            RAISE ERR_HAS_MONEY;
        END IF;
    
    -- 회원의 상태가 영구정지 상태인지
        SELECT NVL(SUM(PENALTY_SCORE), 0) INTO V_PENALTY_SCORE
        FROM PENALTY_HISTORY
        WHERE USER_ID = P_USER_ID
        AND PENALTY_ID NOT IN (SELECT PENALTY_ID FROM PENALTY_CANCEL);

        IF V_PENALTY_SCORE >= 4 THEN
            RAISE ERR_HAS_PENALTY;
        END IF;

    
    -- USER_PROFILE 조회
        SELECT USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE
        , USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL 
        INTO V_NAME, V_SSN, V_EMAIL, V_PHONE, V_ZIPCODE, V_ADDRESS, V_DETAIL
        FROM USER_PROFILE
        WHERE USER_ID = P_USER_ID;

    -- DELETED_USER INSERT
        INSERT INTO DELETED_USER(USER_ID, USER_NAME, USER_SSN, USER_EMAIL, USER_PHONE, USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL)
        VALUES(P_USER_ID, V_NAME, V_SSN, V_EMAIL, V_PHONE, V_ZIPCODE, V_ADDRESS, V_DETAIL);
    
    -- USER_PROFILE DELETE
        DELETE
        FROM USER_PROFILE
        WHERE USER_ID = P_USER_ID;

    -- ACCOUNT_EVENT_HISTORY INSERT
        INSERT INTO ACCOUNT_EVENT_HISTORY
        VALUES(ACCOUNT_EVENT_HISTORY_SEQ.NEXTVAL, P_USER_ID, 2, SYSDATE);
    
    EXCEPTION
        WHEN ERR_HAS_ACTIVE_AUCTION THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20016, '진행 중인 경매가 존재합니다.');
        WHEN ERR_HAS_ACTIVE_BID THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20026, '진행 중인 입찰이 존재합니다.');
        WHEN ERR_HAS_ACTIVE_WINNING THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20027, '진행 중인 낙찰이 존재합니다.');
        WHEN ERR_HAS_PENALTY THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20028, '영구정지 회원은 탈퇴가 불가능합니다.');
        WHEN ERR_HAS_MONEY THEN   
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20029, '잔여머니가 존재합니다.');
    
END;
/


-- 뷰 목록 ======================================================================

-- 1. 회원 정보 조회 뷰 VW_USER_INFO
CREATE OR REPLACE VIEW VW_USER_INFO
AS
SELECT U.USER_ID, UA.USER_LOGIN_ID, UA.USER_PASSWORD
, UP.USER_NAME, UP.USER_SSN, UP.USER_EMAIL, UP.USER_PHONE
, UP.USER_ZIPCODE, UP.USER_ADDRESS, UP.USER_ADDRESS_DETAIL
, FN_GET_USER_MONEY_BALANCE(U.USER_ID) AS TOTAL_MONEY
FROM USERS U JOIN USER_ACCOUNT UA
ON U.USER_ID = UA.USER_ID
JOIN USER_PROFILE UP
ON UA.USER_ID = UP.USER_ID;

SELECT *
FROM VW_USER_INFO;
/

-- 2. 상품 통합 조회  VW_PRODUCT_LIST
CREATE OR REPLACE VIEW VW_PRODUCT_LIST
AS
SELECT 
    P.PRODUCT_ID, P.USER_ID, P.MANUFACTURER_ID, PM.MANUFACTURER_NAME, PM.PRODUCT_COUNTRY_ID, PC.PRODUCT_COUNTRY_NAME
    , P.PRODUCT_GRADE_ID, PG.PRODUCT_GRADE_NAME, P.PRODUCT_GENRE_ID, PGR.PRODUCT_GENRE_NAME, P.PRODUCT_SIZE_ID, PS.PRODUCT_SIZE_NAME
    , P.PRODUCT_RELEASE_NAME, P.PRODUCT_ALIAS, P.WORK_NAME, P.CHARACTER_NAME, P.PURCHASE_DATETIME
    ,CASE WHEN P.IS_OPENED = 0 THEN '개봉' ELSE '미개봉' END AS IS_OPENED
    ,CASE WHEN P.IS_PARTS_MISSING = 0 THEN '정상' ELSE '누락' END AS IS_PARTS_MISSING
    ,P.DESCRIPTIONS
    ,P.IMAGE_PATH_1
    ,P.IMAGE_PATH_2
    ,P.IMAGE_PATH_3
    ,MAX(DECODE(PI.IMAGE_ORDER, 1, PI.FILE_PATH)) AS IMAGE_PATH_4
    ,MAX(DECODE(PI.IMAGE_ORDER, 2, PI.FILE_PATH)) AS IMAGE_PATH_5
    ,MAX(DECODE(PI.IMAGE_ORDER, 3, PI.FILE_PATH)) AS IMAGE_PATH_6
    ,MAX(DECODE(PI.IMAGE_ORDER, 4, PI.FILE_PATH)) AS IMAGE_PATH_7
    ,MAX(DECODE(PI.IMAGE_ORDER, 5, PI.FILE_PATH)) AS IMAGE_PATH_8
    ,MAX(DECODE(PI.IMAGE_ORDER, 6, PI.FILE_PATH)) AS IMAGE_PATH_9
    ,MAX(DECODE(PI.IMAGE_ORDER, 7, PI.FILE_PATH)) AS IMAGE_PATH_10
    ,CASE WHEN P.IS_PUBLIC = 0 THEN '비공개' ELSE '공개' END AS IS_PUBLIC
    ,TO_CHAR(P.CREATED_AT, 'YYYY-MM-DD') AS CREATED_AT
FROM PRODUCT P
    JOIN PRODUCT_MANUFACTURER PM ON P.MANUFACTURER_ID = PM.MANUFACTURER_ID
    JOIN PRODUCT_COUNTRY PC      ON PM.PRODUCT_COUNTRY_ID = PC.PRODUCT_COUNTRY_ID
    JOIN PRODUCT_GRADE PG        ON P.PRODUCT_GRADE_ID = PG.PRODUCT_GRADE_ID
    JOIN PRODUCT_GENRE PGR       ON P.PRODUCT_GENRE_ID = PGR.PRODUCT_GENRE_ID
    JOIN PRODUCT_SIZE PS         ON P.PRODUCT_SIZE_ID = PS.PRODUCT_SIZE_ID
    LEFT JOIN PRODUCT_IMAGE PI   ON P.PRODUCT_ID = PI.PRODUCT_ID
GROUP BY 
    P.PRODUCT_ID, P.USER_ID,
    P.MANUFACTURER_ID, PM.MANUFACTURER_NAME, PM.PRODUCT_COUNTRY_ID, PC.PRODUCT_COUNTRY_NAME, 
    P.PRODUCT_GRADE_ID, PG.PRODUCT_GRADE_NAME,
    P.PRODUCT_GENRE_ID, PGR.PRODUCT_GENRE_NAME, 
    P.PRODUCT_SIZE_ID, PS.PRODUCT_SIZE_NAME, 
    P.PRODUCT_RELEASE_NAME, P.PRODUCT_ALIAS, P.WORK_NAME, P.CHARACTER_NAME,
    P.PURCHASE_DATETIME, P.IS_OPENED, P.IS_PARTS_MISSING, P.DESCRIPTIONS,
    P.IMAGE_PATH_1, P.IMAGE_PATH_2, P.IMAGE_PATH_3, P.IS_PUBLIC, P.CREATED_AT;
    
    





-- 뷰	경매 목록 조회 뷰	VW_AUCTION_LIST
/*
CREATE OR REPLACE VIEW VW_AUCTION_LIST
AS
SELECT 
    AR.AUCTION_ID, AR.AUCTION_TITLE, AR.AUCTION_CONTENT, AR.START_PRICE,
    AR.AUCTION_PERIOD_ID, AP.AUCTION_PERIOD_NAME,
    TO_CHAR(AR.CREATED_AT, 'YYYY-MM-DD HH24:MI') AS AUCTION_START_DATE,
    FN_GET_AUCTION_DUE_DATE(AR.AUCTION_ID) AS AUCTION_END_DATE,
    CASE WHEN FN_IS_AUCTION_FINISHED(AR.AUCTION_ID) = 0 THEN '경매 진행중'
        ELSE '경매 마감' 
        END AS IS_FINISHED,
    VPI.PRODUCT_ID, VPI.PRODUCT_RELEASE_NAME, VPI.PRODUCT_ALIAS,
    VPI.MANUFACTURER_NAME, VPI.PRODUCT_GRADE_NAME, VPI.IMAGE_PATH_1,
    (
        SELECT BID_PRICE
        FROM (
            SELECT BID_PRICE, 
                   ROW_NUMBER() OVER (ORDER BY BID_PRICE DESC, CREATED_AT ASC) AS RANK
            FROM AUCTION_BID_PARTICIPATION
            WHERE AUCTION_ID = AR.AUCTION_ID
        )
        WHERE RANK = 2
    ) AS BID_CURRENT_PRICE, 
    (SELECT MAX(BID_PRICE) FROM AUCTION_BID_PARTICIPATION WHERE AUCTION_ID = AR.AUCTION_ID) AS BID_MAX_PRICE,
    (SELECT COUNT(*) FROM AUCTION_BID_PARTICIPATION WHERE AUCTION_ID = AR.AUCTION_ID) AS BID_COUNT
FROM AUCTION_REGISTRATION AR
    JOIN VW_PRODUCT_LIST VPI ON AR.PRODUCT_ID = VPI.PRODUCT_ID
    JOIN AUCTION_PERIOD AP   ON AR.AUCTION_PERIOD_ID = AP.AUCTION_PERIOD_ID
;
*/


CREATE OR REPLACE VIEW VW_AUCTION_LIST
AS
WITH BID_RANK AS (
    SELECT 
        AUCTION_ID, BID_PRICE,
        ROW_NUMBER() OVER (PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS RK
    FROM AUCTION_BID_PARTICIPATION
)
SELECT 
    AR.AUCTION_ID, AR.AUCTION_TITLE, AR.AUCTION_CONTENT, AR.START_PRICE,
    AR.AUCTION_PERIOD_ID, AP.AUCTION_PERIOD_NAME,
    TO_CHAR(AR.CREATED_AT, 'YYYY-MM-DD HH24:MI') AS AUCTION_START_DATE,
    FN_GET_AUCTION_DUE_DATE(AR.AUCTION_ID) AS AUCTION_END_DATE,
    CASE WHEN FN_IS_AUCTION_FINISHED(AR.AUCTION_ID) = 0 THEN '진행중'
         ELSE '마감' 
    END AS IS_FINISHED,
    VPI.PRODUCT_ID, VPI.PRODUCT_RELEASE_NAME, VPI.PRODUCT_ALIAS,
    VPI.MANUFACTURER_NAME, VPI.PRODUCT_GRADE_NAME, VPI.IMAGE_PATH_1,
    NVL((SELECT BID_PRICE FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 2), AR.START_PRICE) AS BID_CURRENT_PRICE,
    (SELECT BID_PRICE FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 1) AS BID_MAX_PRICE,
    (SELECT COUNT(*) FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID) AS BID_COUNT
FROM AUCTION_REGISTRATION AR
JOIN VW_PRODUCT_LIST VPI ON AR.PRODUCT_ID = VPI.PRODUCT_ID
JOIN AUCTION_PERIOD AP   ON AR.AUCTION_PERIOD_ID = AP.AUCTION_PERIOD_ID;

SELECT *
FROM VW_AUCTION_LIST;



-- 입찰 통합 뷰 (어떤 상품, 어떤 경매, 누가입찰, 입찰 순위, 입찰가, 
CREATE OR REPLACE VIEW VW_BID_LIST
AS
WITH BID_RANKING AS (
    -- 모든 입찰 기록에 대해 실시간 순위를 매김
    SELECT 
        BID_ID, AUCTION_ID, USER_ID, BID_PRICE, BID_TIME,
        ROW_NUMBER() OVER (PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS RK
    FROM AUCTION_BID_PARTICIPATION
)
SELECT 
    BR.BID_ID, BR.BID_PRICE,
    TO_CHAR(BR.BID_TIME, 'YYYY-MM-DD HH24:MI:SS.FF3') AS BID_TIME,
    BR.RK AS BID_RANK,
    CASE WHEN BR.RK = 1 THEN '낙찰유력' 
         WHEN BR.RK >4 THEN '순위권'
        ELSE '입찰중' END AS BID_STATUS,
    BR.USER_ID AS BIDDER_ID, UP.USER_ID , UA.USER_LOGIN_ID,
    AR.AUCTION_ID, AR.AUCTION_TITLE, AR.START_PRICE,
    FN_GET_AUCTION_DUE_DATE(AR.AUCTION_ID) AS AUCTION_END_DATE,
    CASE WHEN FN_IS_AUCTION_FINISHED(AR.AUCTION_ID) = 0 THEN '진행중' ELSE '마감' END AS AUCTION_STATUS,
    VPL.PRODUCT_ID, VPL.PRODUCT_RELEASE_NAME, VPL.MANUFACTURER_NAME,
    NVL(
        (SELECT BID_PRICE FROM BID_RANKING WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 2),
        AR.START_PRICE
    ) AS CURRENT_PRICE
FROM BID_RANKING BR
JOIN AUCTION_REGISTRATION AR ON BR.AUCTION_ID = AR.AUCTION_ID
JOIN USER_PROFILE UP ON BR.USER_ID = UP.USER_ID
JOIN USER_ACCOUNT UA ON UP.USER_ID = UA.USER_ID
JOIN VW_PRODUCT_LIST VPL ON AR.PRODUCT_ID = VPL.PRODUCT_ID;

SELECT *
FROM VW_BID_LIST;




--CREATE OR REPLACE VIEW VW_PENALTY_LIST
--AS
--SELECT 
--    PH.USER_ID, PH.PENALTY_ID, PH.PENALTY_SCORE,
--    FN_GET_USER_PENALTY_SCORE(PH.USER_ID) AS TOTAL_SCORE,
--    TO_CHAR(PS.PENALTY_START_DATE, 'YYYY-MM-DD HH24:MI') AS START_DATE,
--    TO_CHAR(PS.PENALTY_END_DATE, 'YYYY-MM-DD HH24:MI') AS END_DATE,
--    CASE WHEN PS.PENALTY_END_DATE > SYSDATE THEN 'Y' ELSE 'N' END AS IS_CURRENTLY_BANNED,
--    CASE WHEN PC.PENALTY_ID IS NOT NULL THEN 'Y' ELSE 'N' END AS IS_CANCEL
--FROM PENALTY_HISTORY PH
--     JOIN PENALTY_STATUS PS ON PH.PENALTY_ID = PS.PENALTY_ID
--     JOIN PENALTY_CANCEL PC ON PH.PENALTY_ID = PC.PENALTY_ID;
--     
--SELECT *
--FROM VW_PENALTY_LIST;


CREATE OR REPLACE VIEW VW_PENALTY_LIST
AS
WITH RAW_HISTORY AS (
    SELECT 
        PH.USER_ID, PH.PENALTY_ID, PH.PENALTY_SCORE, PH.CREATED_AT,
        SUM(CASE WHEN PC.PENALTY_ID IS NULL THEN PH.PENALTY_SCORE ELSE 0 END) 
            OVER (PARTITION BY PH.USER_ID ORDER BY PH.CREATED_AT ASC) AS ACCUMULATED_SCORE,
        PC.PENALTY_ID AS CANCEL_ID, PC.CANCEL_REASON
    FROM PENALTY_HISTORY PH
    LEFT JOIN PENALTY_CANCEL PC ON PH.PENALTY_ID = PC.PENALTY_ID
)
SELECT 
    RH.USER_ID, RH.PENALTY_ID, RH.PENALTY_SCORE AS GIVEN_SCORE,
    RH.ACCUMULATED_SCORE AS ACCUMULATED_SCORE,
    FN_GET_USER_PENALTY_SCORE(RH.USER_ID) AS TOTAL_SCORE,
    CASE 
        WHEN RH.CANCEL_ID IS NOT NULL THEN '취소'
        WHEN RH.ACCUMULATED_SCORE = 1 THEN '경고'
        WHEN RH.ACCUMULATED_SCORE = 2 THEN '7일 정지'
        WHEN RH.ACCUMULATED_SCORE = 3 THEN '30일 정지'
        WHEN RH.ACCUMULATED_SCORE >= 4 THEN '영구 정지'
        ELSE '정상'
    END AS PENALTY_STATUS,
    TO_CHAR(PS.PENALTY_START_DATE, 'YYYY-MM-DD HH24:MI') AS START_DATE,
    TO_CHAR(PS.PENALTY_END_DATE, 'YYYY-MM-DD HH24:MI') AS END_DATE,
    CASE 
        WHEN RH.CANCEL_ID IS NOT NULL THEN '취소완료'
        WHEN PS.PENALTY_END_DATE < SYSDATE THEN '기간만료'
        ELSE '제재 중'
    END AS HISTORY_STATUS
FROM RAW_HISTORY RH
LEFT JOIN PENALTY_STATUS PS ON RH.PENALTY_ID = PS.PENALTY_ID;


SELECT *
FROM VW_PENALTY_LIST;



CREATE OR REPLACE VIEW VW_AUCTION_BID_RANK
AS
SELECT 
    AUCTION_ID, USER_ID, BID_PRICE, 
    TO_CHAR(BID_TIME, 'YYYY-MM-DD HH24:MI:SS.FF3') AS BID_TIME,
    ROW_NUMBER() OVER (PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS CURRENT_RANK,
    COUNT(*) OVER (PARTITION BY AUCTION_ID) AS TOTAL_BIDDERS
FROM AUCTION_BID_PARTICIPATION;

-- VW_MONEY_HISTORY

CREATE OR REPLACE VIEW VW_MONEY_HISTORY
AS
SELECT 
    USER_ID,
    '충전' AS TRANSACTION_TYPE, 
    CHARGE_AMOUNT AS AMOUNT,     
    TO_CHAR(CHARGED_AT, 'YYYY-MM-DD HH24:MI:SS') AS TRANSACTION_DATE,
    MCM.MONEY_CHARGE_METHOD_NAME AS DESCRIPTION 
FROM MONEY_CHARGE_HISTORY MCH
JOIN MONEY_CHARGE_METHOD MCM ON MCH.MONEY_CHARGE_METHOD_ID = MCM.MONEY_CHARGE_METHOD_ID
UNION ALL
SELECT 
    USER_ID,
    MT.MONEY_TYPE_NAME AS TRANSACTION_TYPE, 
    AMOUNT,                 
    TO_CHAR(CREATED_AT, 'YYYY-MM-DD HH24:MI:SS') AS TRANSACTION_DATE,
    MT.MONEY_TYPE_NAME AS DESCRIPTION     
FROM MONEY_TRANSACTION_HISTORY MTH
JOIN MONEY_TYPE MT ON MTH.MONEY_TYPE_ID = MT.MONEY_TYPE_ID;




-- 뷰 목록 ======================================================================


CREATE OR REPLACE VIEW VW_AUCTION_URGENT_LIST
AS
SELECT VA.AUCTION_ID, VA.AUCTION_TITLE, VA.IMAGE_PATH_1, VA.BID_CURRENT_PRICE, UA.USER_LOGIN_ID, VA.AUCTION_END_DATE
   , ROW_NUMBER() OVER(ORDER BY VA.AUCTION_END_DATE DESC) AS RK
FROM VW_AUCTION_LIST VA 
    JOIN PRODUCT P ON VA.PRODUCT_ID = P.PRODUCT_ID
    JOIN USER_ACCOUNT UA ON P.USER_ID = UA.USER_ID
WHERE TO_DATE(AUCTION_END_DATE,'YYYY-MM-DD HH24:MI:SS') > SYSDATE;



--ROW_NUMBER() OVER (PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS RK



SELECT *
FROM VW_AUCTION_LIST;

-- 낙찰 입찰코드 조회 함수
-- 경매 마감이 된 건에 대해 auction_id, 입찰테이블을 줄세우기해서 1위 뽑아내기
CREATE OR REPLACE FUNCTION FN_GET_WINNING_BID_ID
( P_AUCTION_ID IN NUMBER
)
RETURN NUMBER
IS
    V_WINNIG_ID NUMBER;
BEGIN
    SELECT BID_ID INTO V_WINNIG_ID
    FROM VW_BID_LIST
    WHERE AUCTION_ID = P_AUCTION_ID AND BID_RANK = 1;
    
    RETURN V_WINNIG_ID;
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN -1;
        WHEN OTHERS THEN
            RETURN -1;

END;

SELECT *
FROM VW_BID_LIST;



-- 낙찰 실패 처리 프로시저
-- 낙찰결과테이블에서 낙찰결과코드가 유효한지 확인
-- 낙찰결과코드를 보고 언제 등록됐는지 확인 후
-- 낙찰 포기 눌렀을 때나 
-- 24시간이 지났으면서 낙찰입금테이블에 낙찰결과코드가 없다면
-- 낙찰 실패 이력에 insert






-- 신고 처리 프로시저
-- 신고 신청 테이블이 생성되면 그 목록을 보고 관리자가 처리를 한다
-- 신고신청코드(FK)
--관리자계정번호(FK)
--신고처리결과코드(FK)
--처리사유
--처리일자
-- 신고처리 결과 코드에 따라 승인이라면 신고 신청 코드를 가지고 신고대상코드가 상품이라면 상품테이블조회
-- 경매라면 신고경매테이블을 조회해서 각각의 코드에 따라가서 유저 아이디를 찾는다
-- 그리고 패널티 부여를 함(패널티 부여 프로시저)
-- 반려라면 그냥 인서트하고 끝
CREATE OR REPLACE PROCEDURE PRC_REPORT_PROCESS
(P_REPORT_SUBMISSION_ID IN REPORT_SUBMISSION.REPORT_SUBMISSION_ID%TYPE
, P_ADMIN_ACCOUNT_ID    IN ADMIN_ACCOUNT.ADMIN_ACCOUNT_ID%TYPE
, P_REPORT_RESULT_ID    IN REPORT_RESULT.REPORT_RESULT_ID%TYPE
, P_PROCESSED_REASON    IN REPORT_PROCESS.PROCESS_REASON%TYPE
)
IS
    V_TARGET_ID NUMBER;
    V_PRODUCT_ID PRODUCT.PRODUCT_ID%TYPE;
    V_AUCTION_ID AUCTION_REGISTRATION.AUCTION_ID%TYPE;
    V_USER_ID USERS.USER_ID%TYPE;
BEGIN
  
    IF (P_REPORT_RESULT_ID = 1) THEN
    
        SELECT REPORT_TARGET_ID INTO V_TARGET_ID
        FROM REPORT_SUBMISSION
        WHERE REPORT_SUBMISSION_ID = P_REPORT_SUBMISSION_ID;
        
        IF (V_TARGET_ID = 1) THEN
            
            SELECT PRODUCT_ID INTO V_PRODUCT_ID
            FROM PRODUCT_REPORT
            WHERE REPORT_SUBMISSION_ID = P_REPORT_SUBMISSION_ID;
            
            SELECT USER_ID INTO V_USER_ID
            FROM PRODUCT
            WHERE PRODUCT_ID = V_PRODUCT_ID;
            
        ELSIF (V_TARGET_ID = 2) THEN
        
            SELECT AUCTION_ID INTO V_AUCTION_ID
            FROM AUCTION_REPORT
            WHERE REPORT_SUBMISSION_ID = P_REPORT_SUBMISSION_ID;
            
            SELECT PRODUCT_ID INTO V_PRODUCT_ID
            FROM AUCTION_REGISTRATION
            WHERE AUCTION_ID = V_AUCTION_ID;
            
            SELECT USER_ID INTO V_USER_ID
            FROM PRODUCT
            WHERE PRODUCT_ID = V_PRODUCT_ID;
        END IF;
        
        -- 패널티 부여
        IF V_USER_ID IS NOT NULL THEN
            PRC_PENALTY_ASSIGN(V_USER_ID, P_ADMIN_ACCOUNT_ID, 1, 1);
        END IF;
    END IF;
    
    INSERT INTO REPORT_PROCESS(REPORT_PROCESS_ID, REPORT_SUBMISSION_ID, ADMIN_ACCOUNT_ID, REPORT_RESULT_ID, PROCESS_REASON, PROCESSED_AT)
    VALUES(REPORT_PROCESS_SEQ.NEXTVAL, P_REPORT_SUBMISSION_ID, P_ADMIN_ACCOUNT_ID, P_REPORT_RESULT_ID, P_PROCESSED_REASON, SYSDATE);
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20030, '해당 신고 내역이나 대상자를 찾을 수 없습니다.');
        WHEN OTHERS THEN
            ROLLBACK;
    
END;
/

DESC REPORT_PROCESS;




CREATE OR REPLACE PROCEDURE PRC_PENALTY_ASSIGN
( V_USER_ID             IN      USERS.USER_ID%TYPE
, V_ADMIN_ACCOUNT_ID    IN      ADMIN_ACCOUNT.ADMIN_ACCOUNT_ID%TYPE
, V_PENALTY_TYPE_ID     IN      PENALTY_HISTORY.PENALTY_SCORE%TYPE
, V_PENALTY_SCORE       IN      PENALTY_HISTORY.PENALTY_SCORE%TYPE
)
IS
	V_FLAG_ACTIVE_USER			CHAR(1);
	V_FLAG_BANNED_USER			CHAR(1);

	-- V_PENALTY_ID                PENALTY_HISTORY.PENALTY_ID%TYPE;
    V_TOTAL_PENALTY_SCORE       PENALTY_HISTORY.PENALTY_SCORE%TYPE;
    V_PENALTY_END_DATE          PENALTY_STATUS.PENALTY_END_DATE%TYPE;
    
    ERR_PENALTY_TO_DEACTIVATED_USER EXCEPTION;
    ERR_PENALTY_TO_BANNED_USER EXCEPTION;
    
BEGIN
	-- 회원 유효성 체크) 활동 회원인지 확인
	SELECT
		CASE WHEN EXISTS(SELECT 1 FROM USER_PROFILE WHERE USER_ID = V_USER_ID)
		     THEN 'Y'
		     
		     ELSE 'N'
		END INTO V_FLAG_ACTIVE_USER
	FROM DUAL;

	-- 활동하지 않는 회원이라면(=탈퇴한 회원이라면) 예외 발생 처리
	IF V_FLAG_ACTIVE_USER = 'N' THEN
		RAISE ERR_PENALTY_TO_DEACTIVATED_USER;
	END IF;
	

	-- 회원 유효성 체크) 영구 정지 처리된 회원이지 확인
	-- 유저의 현재 패널티 총점 확인
    SELECT SUM(PH.PENALTY_SCORE) INTO V_TOTAL_PENALTY_SCORE
    FROM PENALTY_HISTORY PH LEFT OUTER JOIN PENALTY_CANCEL PC
         ON PH.PENALTY_ID = PC.PENALTY_ID
    WHERE PH.USER_ID = V_USER_ID
      AND PENALTY_CANCEL_ID IS NULL;

	-- 영구 정지 점수(4점 이상)면 이미 영구 정지된 회원이므로 예외 발생
	IF V_TOTAL_PENALTY_SCORE >= 4 THEN
		RAISE ERR_PENALTY_TO_BANNED_USER;
	END IF;
	
	
	
	-- 회원 유효성 검사 이후) 패널티 부여 로직 수행
    -- 패널티 점수 부여
	--  ㄴ 패널티 점수 부여 후 정지 처리는 트리거로 수행
    INSERT INTO PENALTY_HISTORY (PENALTY_ID, USER_ID, PENALTY_TYPE_ID, ADMIN_ACCOUNT_ID, PENALTY_SCORE, CREATED_AT)
    VALUES (PENALTY_SEQ.NEXTVAL, V_USER_ID, V_PENALTY_TYPE_ID, V_ADMIN_ACCOUNT_ID, V_PENALTY_SCORE, SYSDATE);

	
	EXCEPTION
		-- 활동하지 않는 회원(=탈퇴 회원)에게 패널티 부여 시도
		WHEN ERR_PENALTY_TO_DEACTIVATED_USER
		THEN RAISE_APPLICATION_ERROR(-21000, '탈퇴한 회원에게는 패널티 부여가 불가능합니다.');
		
		-- 이미 영구정지된 회원에게 추가 패널티 부여 시도(=의미 없는 패널티 부여)
		WHEN ERR_PENALTY_TO_BANNED_USER
		THEN RAISE_APPLICATION_ERROR(-21001, '이미 영구 정지 처리된 회원에게는 추가 패널티 부여가 불가능합니다.');
		
		WHEN OTHERS
		THEN RAISE; -- 에러 전파 (ROLLBACK 은 프로시저 호출단에서 컨트롤)
END;
















