SELECT USER
FROM DUAL;
-- 안진모

-- 구매 확정 이력
CREATE TABLE PURCHASE_CONFIRM_HISTORY
(
PURCHASE_CONFIRM_ID NUMBER
,SHIPPING_ID NUMBER NOT NULL
,CREATED_AT DATE DEFAULT SYSDATE NOT NULL
,CONSTRAINT PURCHASE_CONFIRM_HISTORY_PURCHASE_CONFIRM_ID_PK PRIMARY KEY(PURCHASE_CONFIRM_ID)
,CONSTRAINT PURCHASE_CONFIRM_HISTORY_SHIPPING_ID_FK FOREIGN KEY(SHIPPING_ID)
                                                    REFERENCES DELIVERY_COMPLETED(SHIPPING_ID)                                             
)

-- 거래 완료
CREATE TABLE TRANSACTION_COMPLETED
(
TRANSACTION_ID NUMBER
,PURCHASE_CONFIRM_ID NUMBER NOT NULL 
,CREATED_AT DATE NOT NULL DEFAULT SYSDATE
,CONSTRAINT TRANSACTION_COMPLETED_TRANSACTION_ID_PK PRIMARY KEY(TRANSACTION_ID)
,CONSTRAINT TRANSACTION_COMPLETED_PURCHASE_CONFIRM_ID_FK FOREIGN KEY(PURCHASE_CONFIRM_ID)
                                                         REFERENCES PURCHASE_CONFIRM_HISTORY(PURCHASE_CONFIRM_ID)
)

-- 패널티 부여 구분
CREATE TABLE PENALTY_ASSIGN_TYPE
(
PENALTY_TYPE_CODE NUMBER
,PENALTY_TYPE_NAME VARCHAR2(50) NOT NULL
,CONSTRAINT PENALTY_ASSIGN_TYPE_PENALTY_ASSIGN_TYPE_CODE_PK PRIMARY KEY(PENALTY_TYPE_CODE)
,CONSTRAINT PENALTY_ASSIGN_TYPE_PENALTY_TYPE_NAME_UK UNIQUE(PENALTY_TYPE_NAME)
)

-- 패널티 이력
CREATE TABLE PENALTY_HISTORY
(
PENALTY_ID NUMBER
,USER_ID NUMBER NOT NULL
,PENALTY_TYPE_CODE NUMBER NOT NULL
,ADMIN_ACCOUNT_ID NUMBER NOT NULL
,PENALTY_SCORE NUMBER NOT NULL
,PENALTY_START_DATE DATE NOT NULL
,PENALTY_END_DATE DATE NOT NULL
,CREATED_AT DATE NOT NULL DEFAULT SYSDATE
,CONSTRAINT PENALTY_HISTORY_PENALTY_HISTORY_ID_PK PRIMARY KEY(PENALTY_ID)
,CONSTRAINT PENALTY_HISTORY_USER_ID_FK FOREIGN KEY(USER_ID)
                                        REFERENCES USER(USER_ID)
,CONSTRAINT PENALTY_HISTORY_PENALTY_TYPE_CODE_FK FOREIGN KEY(PENALTY_TYPE_CODE)
                                                  REFERENCES PENALTY_ASSIGN_TYPE(PENALTY_TYPE_CODE)
,CONSTRAINT PENALTY_HISTORY_ADMIN_ACCOUNT_ID_FK FOREIGN KEY(ADMIN_ACCOUNT_ID)
                                             REFERENCES ADMIN_ACCOUNT(ADMIN_ACCOUNT_ID)
,CONSTRAINT PENALTY_HISTORY_SCORE_CK CHECK(PENALTY_SCORE BETWEEN 1 AND 4)
)

-- 패널티 취소
CREATE TABLE PENALTY_CANCEL
(
PENALTY_CANCEL_ID NUMBER
,PENALTY_ID NUMBER NOT NULL
,ADMIN_ACCOUNT_ID NUMBER NOT NULL
,CANCEL_REASON VARCHAR2(500) NOT NULL
,CANCELED_AT DATE NOT NULL DEFAULT SYSDATE
,CONSTRAINT PENALTY_CANCEL_PENALTY_CANCEL_ID_PK PRIMARY KEY(PENALTY_CANCEL_ID)
,CONSTRAINT PENALTY_CANCEL_PENALTY_ID_FK FOREIGN KEY(PENALTY_ID)
                                        REFERENCES PENALTY_HISTORY(PENALTY_ID)
,CONSTRAINT PENALTY_CANCEL_ADMIN_ACCOUNT_ID_FK FOREIGN KEY(ADMIN_ACCOUNT_ID)
                                                REFERENCES ADMIN_ACCOUNT(ADMIN_ACCOUNT_ID)
,CONSTRAINT PENALTY_CANCEL_PENALTY_ID_UK UNIQUE(PENALTY_ID)                                                                                          
)

-- 신고 유형
CREATE TABLE REPORT_TYPE
(
REPORT_TYPE_CODE NUMBER
,REPORT_TYPE_NAME VARCHAR2(50) NOT NULL
,CONSTRAINT REPORT_TYPE_REPORT_TYPE_ID_PK PRIMARY KEY(REPORT_TYPE_CODE)
,CONSTRAINT REPORT_TYPE_REPORT_TYPE_NAME_UK UNIQUE(REPORT_TYPE_NAME)
)

-- 신고 대상
CREATE TABLE REPORT_TARGET
(
REPORT_TARGET_CODE NUMBER
,REPORT_TARGET_NAME VARCHAR2(50) NOT NULL
,CONSTRAINT REPORT_TARGET_REPORT_TARGET_ID_PK PRIMARY KEY(REPORT_TARGET_CODE)
,CONSTRAINT REPORT_TARGET_REPORT_TARGET_NAME_UK UNIQUE(REPORT_TARGET_NAME)
)

-- 신고 신청
CREATE TABLE REPORT_SUBMISSION
(
REPORT_ID NUMBER
,USER_ID NUMBER NOT NULL
,REPORT_TARGET_CODE NUMBER NOT NULL
,REPORT_TYPE_CODE NUMBER NOT NULL
,REPORT_REASON VARCHAR2(500)
,CREATED_AT DATE DEFAULT SYSDATE NOT NULL
,CONSTRAINT REPORT_SUBMISSION_REPORT_SUBMISSION_ID_PK PRIMARY KEY(REPORT_ID)
,CONSTRAINT REPORT_SUBMISSION_USER_ID_FK FOREIGN KEY(USER_ID)
                                         REFERENCES USER(USER_ID)
,CONSTRAINT REPORT_SUBMISSION_REPORT_TARGET_CODE_FK FOREIGN KEY(REPORT_TARGET_CODE)
                                                    REFERENCES REPORT_TARGET(REPORT_TYPE_CODE)
,CONSTRAINT REPORT_SUBMISSION_REPORT_TYPE_CODE_FK FOREIGN KEY(REPORT_TYPE_CODE)
                                                   REFERENCES REPORT_TYPE(REPORT_TYPE_CODE)
)

-- 상품 신고
CREATE TABLE PRODUCT_REPORT
(
PRODUCT_REPORT_ID NUMBER
,REPORT_ID NUMBER NOT NULL
,PRODUCT_ID NUMBER NOT NULL
,CONSTRAINT PRODUCT_REPORT_PRODUCT_REPORT_ID_PK PRIMARY KEY(PRODUCT_REPORT_ID)
,CONSTRAINT PRODUCT_REPORT_REPORT_ID_FK FOREIGN KEY(REPORT_ID)
                                        REFERENCES REPORT_SUBMISSION(REPORT_ID)
,CONSTRAINT PRODUCT_REPORT_PRODUCT_ID_FK FOREIGN KEY(PRODUCT_ID)
                                         REFERENCES PRODUCT(PRODUCT_ID)
)

-- 경매 신고
CREATE TABLE AUCTION_REPORT
(
AUCTION_REPORT_ID
,REPORT_ID NOT NULL
,AUCTION_ID NOT NULL
,CONSTRAINT AUCTION_REPORT_AUCTION_REPORT_ID_PK PRIMARY KEY(AUCTION_REPORT_ID)
,CONSTRAINT AUCTION_REPORT_REPORT_ID_FK FOREIGN KEY(REPORT_ID)
                                        REFERENCES REPORT_SUBMISSION(REPORT_ID)
,CONSTRAINT AUCTION_REPORT_AUCTION_ID_FK FOREIGN KEY(AUCTION_ID)
                                          REFERENCES AUCTION_REGISTRATION(AUCTION_ID)
)

-- 신고 처리 결과
CREATE TABLE REPORT_RESULT
(
REPORT_RESULT_CODE NUMBER
,REPORT_RESULT_NAME VARCHAR2(50) NOT NULL
,CONSTRAINT REPORT_RESULT_REPROT_RESULT_ID_PK PRIMARY KEY(REPORT_RESULT_CODE)
,CONSTRAINT REPORT_RESULT_REPORT_RESULT_NAME_UK UNIQUE(REPORT_RESULT_NAME)
)

-- 신고 처리
CREATE TABLE REPORT_PROCESS
(
REPORT_PROCESS_ID NUMBER
,REPORT_ID NUMBER NOT NULL
,ADMIN_ACCOUNT_ID NUMBER NOT NULL
,REPORT_RESULT_CODE NUMBER NOT NULL
,PROCESS_REASON VARCHAR2(500) NOT NULL
,PROCESSED_AT DATE DEFAULT SYSDATE NOT NULL
,CONSTRAINT REPORT_PROCESS_REPORT_PROCESS_ID_PK PRIMARY KEY(REPORT_PROCESS_ID)
,CONSTRAINT REPORT_PROCESS_REPORT_ID_FK FOREIGN KEY(REPORT_ID)
                                        REFERENCES REPORT_SUBMISSION(REPORT_ID)
,CONSTRAINT REPORT_PROCESS_ADMIN_ACCOUNT_ID_FK FOREIGN KEY(ADMIN_ACCOUNT_ID)
                                                REFERENCES ADMIN_ACCOUNT(ADMIN_ACCOUNT_ID)
,CONSTRAINT REPORT_PROCESS_REPORT_RESULT_CODE_FK FOREIGN KEY(REPORT_RESULT_CODE)                                               
                                                  REFERENCES REPORT_RESULT(REPORT_RESULT_CODE)
)



















