
SELECT AUCTION_ID, IS_FINISHED
FROM VW_AUCTION_LIST
WHERE PRODUCT_ID = 1
;

SELECT P.PRODUCT_ID, P.PRODUCT_RELEASE_NAME
, P.PRODUCT_ALIAS, P.IMAGE_PATH_1, P.IS_PUBLIC, P.CREATED_AT
, VA.AUCTION_ID, VA.IS_FINISHED
FROM PRODUCT P LEFT OUTER JOIN VW_AUCTION_LIST VA
ON P.PRODUCT_ID = VA.PRODUCT_ID
WHERE P.USER_ID = ?


SELECT *
FROM VW_PENALTY_LIST;

DESC VW_PENALTY_LIST;

USER_ID, PENALTY_ID, GIVEN_SCORE, AUCCMULATED_SCORE, TOTAL_SCORE, HISTORY_STATUS;


SELECT VP.USER_ID, VP.USER_LOGIN_ID, VP.PENALTY_ID, VP.GIVEN_SCORE
, VP.ACCUMULATED_SCORE, VP.TOTAL_SCORE, VP.HISTORY_STATUS
, PC.PENALTY_CANCEL_ID , PC.CANCEL_REASON, PC.CANCELED_AT,
FROM VW_PENALTY_LIST VP 
LEFT OUTER JOIN PENALTY_CANCEL PC
ON VP.PENALTY_ID = PC.PENALTY_ID;




CREATE OR REPLACE VIEW VW_PENALTY_DETAIL_LIST
AS
SELECT PH.PENALTY_ID, PH.USER_ID, PA.PENALTY_TYPE_NAME, PH.ADMIN_ACCOUNT_ID
, PH.PENALTY_SCORE, PH.CREATED_AT
, PS.PENALTY_START_DATE, PS.PENALTY_END_DATE
,PH.ADMIN_ACCOUNT_ID AS PENALTY_ASSIGN_ADMIN
,PC.PENALTY_CANCEL_ID, PC.CANCEL_REASON, PC.CANCELED_AT
, PC.ADMIN_ACCOUNT_ID AS PENALTY_CANCLE_ADMIN
FROM PENALTY_HISTORY PH JOIN PENALTY_ASSIGN_TYPE PA
ON PH.PENALTY_TYPE_ID = PA.PENALTY_TYPE_ID
JOIN PENALTY_STATUS PS ON PH.PENALTY_ID = PS.PENALTY_ID
LEFT OUTER JOIN PENALTY_CANCEL PC ON PH.PENALTY_ID = PC.PENALTY_ID;






CREATE OR REPLACE VIEW VW_PENALTY_DETAIL_LIST
AS
WITH RAW_HISTORY AS (
    SELECT 
        PH.PENALTY_ID, 
        PH.USER_ID, 
        PH.PENALTY_TYPE_ID,
        PH.ADMIN_ACCOUNT_ID AS PENALTY_ASSIGN_ADMIN,
        PH.PENALTY_SCORE, 
        PH.CREATED_AT,
        SUM(CASE WHEN PC.PENALTY_ID IS NULL THEN PH.PENALTY_SCORE ELSE 0 END) 
            OVER (PARTITION BY PH.USER_ID ORDER BY PH.CREATED_AT ASC) AS ACCUMULATED_SCORE,
        PC.PENALTY_CANCEL_ID, 
        PC.CANCEL_REASON, 
        PC.CANCELED_AT,
        PC.ADMIN_ACCOUNT_ID AS PENALTY_CANCEL_ADMIN
    FROM PENALTY_HISTORY PH
    LEFT OUTER JOIN PENALTY_CANCEL PC ON PH.PENALTY_ID = PC.PENALTY_ID
)
SELECT 
    UA.USER_LOGIN_ID,   
    RH.USER_ID, 
    RH.PENALTY_ID, 
    PA.PENALTY_TYPE_NAME, 
    RH.PENALTY_SCORE AS GIVEN_SCORE,       
    RH.ACCUMULATED_SCORE,                   
    FN_GET_USER_PENALTY_SCORE(RH.USER_ID) AS TOTAL_SCORE, 
    CASE 
        WHEN RH.PENALTY_CANCEL_ID IS NOT NULL THEN '취소완료'
        WHEN PS.PENALTY_END_DATE < SYSDATE THEN '기간만료'
        ELSE '제재 중'
    END AS HISTORY_STATUS,

    RH.CREATED_AT AS PENALTY_CREATED_AT,
    PS.PENALTY_START_DATE, 
    PS.PENALTY_END_DATE,
    RH.PENALTY_ASSIGN_ADMIN,
    RH.PENALTY_CANCEL_ID, 
    RH.CANCEL_REASON, 
    RH.CANCELED_AT,
    RH.PENALTY_CANCEL_ADMIN
FROM RAW_HISTORY RH
JOIN USER_ACCOUNT UA ON RH.USER_ID = UA.USER_ID
JOIN PENALTY_ASSIGN_TYPE PA ON RH.PENALTY_TYPE_ID = PA.PENALTY_TYPE_ID
JOIN PENALTY_STATUS PS ON RH.PENALTY_ID = PS.PENALTY_ID;

SELECT *
FROM VW_PENALTY_DETAIL_LIST;



SELECT PENALTY_ID, PENALTY_TYPE_NAME, GIVEN_SCORE, ACCUMULATED_SCORE
, TOTAL_SCORE, HISTORY_STATUS, PENALTY_CREATED_AT
, PENALTY_START_DATE, PENALTY_END_DATE
, PENALTY_ASSIGN_ADMIN
, PENALTY_CANCEL_ID, CANCEL_REASON, CANCELED_AT
, PENALTY_CANCEL_ADMIN
FROM VW_PENALTY_DETAIL_LIST
WHERE USER_ID = ?



select *
from VW_AUCTION_LIST
where user_id = 1;



select *
from AUCTION_CANCEL_HISTORY;



CREATE OR REPLACE VIEW VW_AUCTION_LIST
AS
WITH BID_RANK AS (
    SELECT 
        AUCTION_ID, BID_PRICE,
        ROW_NUMBER() OVER (PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS RK
    FROM AUCTION_BID_PARTICIPATION
)
SELECT 
    AR.AUCTION_ID, VPI.USER_ID, AR.AUCTION_TITLE, AR.AUCTION_CONTENT, AR.START_PRICE,
    AR.AUCTION_PERIOD_ID, AP.AUCTION_PERIOD_NAME,
    TO_DATE(AR.CREATED_AT, 'YYYY-MM-DD HH24:MI') AS AUCTION_START_DATE,
    TO_DATE(FN_GET_AUCTION_DUE_DATE(AR.AUCTION_ID),'YYYY-MM-DD HH24:MI') AS AUCTION_END_DATE,
    CASE WHEN (FN_IS_AUCTION_FINISHED(AR.AUCTION_ID) = 0 AND ACH.AUCTION_CANCLE_ID IS NOT NULL)   THEN '경매취소'
         WHEN FN_IS_AUCTION_FINISHED(AR.AUCTION_ID) = 0 THEN '진행중'
         ELSE '마감' 
    END AS IS_FINISHED,
    VPI.PRODUCT_ID, VPI.PRODUCT_RELEASE_NAME, VPI.PRODUCT_ALIAS,
    VPI.MANUFACTURER_NAME, VPI.PRODUCT_GRADE_NAME, VPI.IMAGE_PATH_1,
    NVL((SELECT BID_PRICE FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 2), AR.START_PRICE) AS BID_CURRENT_PRICE,
    (SELECT BID_PRICE FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 1) AS BID_MAX_PRICE,
    (SELECT COUNT(*) FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID) AS BID_COUNT
FROM AUCTION_REGISTRATION AR
JOIN VW_PRODUCT_LIST VPI ON AR.PRODUCT_ID = VPI.PRODUCT_ID
JOIN AUCTION_PERIOD AP   ON AR.AUCTION_PERIOD_ID = AP.AUCTION_PERIOD_ID
LEFT OUTER JOIN AUCTION_CANCEL_HISTORY ACH ON AR.AUCTION_ID = ACH.AUCTION_ID
;


---

CREATE OR REPLACE VIEW VW_AUCTION_LIST
AS
WITH BID_RANK AS (
    SELECT 
        AUCTION_ID, BID_PRICE,
        ROW_NUMBER() OVER (PARTITION BY AUCTION_ID ORDER BY BID_PRICE DESC, BID_TIME ASC) AS RK
    FROM AUCTION_BID_PARTICIPATION
)
SELECT 
    AR.AUCTION_ID, 
    VPI.USER_ID, 
    AR.AUCTION_TITLE, 
    AR.AUCTION_CONTENT, 
    AR.START_PRICE,
    AR.AUCTION_PERIOD_ID, 
    AP.AUCTION_PERIOD_NAME,
    TO_DATE(AR.CREATED_AT, 'YYYY-MM-DD HH24:MI') AS AUCTION_START_DATE,
    TO_DATE(FN_GET_AUCTION_DUE_DATE(AR.AUCTION_ID),'YYYY-MM-DD HH24:MI') AS AUCTION_END_DATE,
    

    CASE 
        WHEN ACH.AUCTION_ID IS NOT NULL THEN '경매취소'  
        WHEN FN_IS_AUCTION_FINISHED(AR.AUCTION_ID) = 0 THEN '진행중'
        ELSE '마감' 
    END AS IS_FINISHED,

    VPI.PRODUCT_ID, 
    VPI.PRODUCT_RELEASE_NAME, 
    VPI.PRODUCT_ALIAS,
    VPI.MANUFACTURER_NAME, 
    VPI.PRODUCT_GRADE_NAME, 
    VPI.IMAGE_PATH_1,
    
    -- 입찰가 정보
    NVL((SELECT BID_PRICE FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 2), AR.START_PRICE) AS BID_CURRENT_PRICE,
    (SELECT BID_PRICE FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID AND RK = 1) AS BID_MAX_PRICE,
    (SELECT COUNT(*) FROM BID_RANK WHERE AUCTION_ID = AR.AUCTION_ID) AS BID_COUNT
FROM AUCTION_REGISTRATION AR
JOIN VW_PRODUCT_LIST VPI ON AR.PRODUCT_ID = VPI.PRODUCT_ID
JOIN AUCTION_PERIOD AP   ON AR.AUCTION_PERIOD_ID = AP.AUCTION_PERIOD_ID
LEFT OUTER JOIN AUCTION_CANCEL_HISTORY ACH ON AR.AUCTION_ID = ACH.AUCTION_ID;



SELECT *
FROM VW_AUCTION_LIST;




				SELECT VR.AUCTION_ID, AL.AUCTION_TITLE, NVL(VR.WINNING_BID_PRICE,0) AS FINAL_PRICE, AL.AUCTION_END_DATE, 
				CASE
                WHEN AL.IS_FINISHED = '경매취소' THEN '경매취소' 
                WHEN BID_FAIL_YN = 'N' AND PURCHASE_CONFIRM_YN = 'N' THEN '거래진행중'
				WHEN BID_FAIL_YN = 'N' AND PURCHASE_CONFIRM_YN = 'Y' THEN '거래완료'
				ELSE '유찰'
				END AS TRANSACTION_STATUS
				, VR.PURCHASE_CONFIRM_DATE, 
				CASE WHEN BID_FAIL_TYPE = 1 THEN '결제기한만료'
				WHEN BID_FAIL_TYPE = 2 THEN '낙찰포기'
				END AS BID_FAIL_TYPE
				FROM VW_AUCTION_LIST AL 
				LEFT OUTER JOIN VW_AUCTION_WINNING_RESULT VR ON AL.AUCTION_ID = VR.AUCTION_ID
				WHERE AL.USER_ID = 1 AND AL.AUCTION_END_DATE<SYSDATE AND AL.IS_FINISHED != '진행중'
				ORDER BY AL.AUCTION_END_DATE DESC



select *
from VW_AUCTION_WINNING_RESULT;


SELECT *
FROM DELIVERY_COMPLETED;

INSERT INTO DELIVERY_COMPLETED(SHIPPING_ID, PAYMENT_ID)
VALUES(SHIPPING_SEQ.NEXTVAL, ?)



SELECT AWP.PAYMENT_ID
FROM AUCTION_BID_PARTICIPATION ABP
LEFT OUTER JOIN AUCTION_WINNING_RESULT AWR ON ABP.BID_ID = AWR.BID_ID
LEFT OUTER JOIN AUCTION_WINNING_PAYMENT AWP ON AWR.BID_RESULT_ID = AWP.BID_RESULT_ID
;
WHERE ABP.AUCTION_ID = ?











