select user from dual;

-- 낙찰 결제 프로시저(컴파일O,테스트X)
CREATE OR REPLACE PROCEDURE PRC_WINNING_PAYMENT_CREATE
(
V_USER_ID USERS.USER_ID%TYPE
,V_RESULT_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE
,V_AMOUNT MONEY_TRANSACTION_HISTORY.AMOUNT%TYPE
)
AS
    N_BID_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE;
    N_AUCTION_ID AUCTION_BID_PARTICIPATION.AUCTION_ID%TYPE;
    N_USER_ID USERS.USER_ID%TYPE;
    N_MONEY_TYPE MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_CREATE_AT AUCTION_REGISTRATION.CREATED_AT%TYPE;
    N_AUCTION_PERIOD_ID AUCTION_PERIOD.AUCTION_PERIOD_ID%TYPE;
    
    N_AUCTION_PERIOD_NAME AUCTION_PERIOD.AUCTION_PERIOD_NAME%TYPE;
    
    N_END_CREATE_AT AUCTION_REGISTRATION.CREATED_AT%TYPE;
    
    N_START_PRICE AUCTION_REGISTRATION.START_PRICE%TYPE;
    
    N_AUCTION_PRICE AUCTION_BID_PARTICIPATION.BID_PRICE%TYPE;
    
    NEW_ERR EXCEPTION;
    NEW_ERR1 EXCEPTION;
BEGIN
 
    SELECT BID_ID INTO N_BID_ID
    FROM AUCTION_WINNING_RESULT
    WHERE BID_RESULT_ID = V_RESULT_ID;
    
    SELECT AUCTION_ID,USER_ID INTO N_AUCTION_ID,N_USER_ID
    FROM AUCTION_BID_PARTICIPATION
    WHERE BID_ID = N_BID_ID;
    
    IF(N_USER_ID != V_USER_ID)
        THEN RAISE NEW_ERR1;
    END IF;
    
    SELECT MONEY_TYPE_ID INTO N_MONEY_TYPE
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '결제 대금 입금';
    
    SELECT CREATED_AT,AUCTION_PERIOD_ID,START_PRICE INTO N_CREATE_AT,N_AUCTION_PERIOD_ID,N_START_PRICE
    FROM AUCTION_REGISTRATION
    WHERE AUCTION_ID = N_AUCTION_ID;
    
    SELECT AUCTION_PERIOD_NAME INTO N_AUCTION_PERIOD_NAME
    FROM AUCTION_PERIOD
    WHERE AUCTION_PERIOD_ID = N_AUCTION_PERIOD_ID;
    
    N_AUCTION_PERIOD_NAME := REPLACE(N_AUCTION_PERIOD_NAME,'일','');
    N_AUCTION_PERIOD_NAME := REPLACE(N_AUCTION_PERIOD_NAME,'시간','');
    
    N_END_CREATE_AT := N_CREATE_AT + N_AUCTION_PERIOD_NAME;
    
    IF(N_END_CREATE_AT > SYSTIMESTAMP)
        THEN RAISE NEW_ERR;
    END IF;
    
--    SELECT NVL(BID_ID,N_START_PRICE) INTO N_AUCTION_PRICE
--    FROM AUCTION_BID_PARTICIPATION
--    WHERE AUCTION_ID = N_AUCTION_ID
--    ORDER BY BID_PRICE DESC
--    OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY;
    
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID
    ,MONEY_TYPE_ID,AUCTION_ID,AMOUNT)
    VALUES(MONEY_TRANSACTION_SEQ.NEXTVAL,V_USER_ID
    ,N_MONEY_TYPE,N_AUCTION_ID,V_AMOUNT);
    
    INSERT INTO AUCTION_WINNING_PAYMENT(PAYMENT_ID
    ,BID_RESULT_ID,MONEY_ID)
    VALUES(PAYMENT_SEQ.NEXTVAL,V_RESULT_ID
    ,MONEY_TRANSACTION_SEQ.CURRVAL);
    
    COMMIT;
    
    EXCEPTION 
        WHEN NEW_ERR
        THEN RAISE_APPLICATION_ERROR(-20100,'경매기간이 마감되어 결제가 불가능합니다');
        ROLLBACK;
        WHEN NEW_ERR1
        THEN RAISE_APPLICATION_ERROR(-20101,'결제자와 입찰자가 다릅니다.');
        ROLLBACK;
        WHEN OTHERS
        THEN DBMS_OUTPUT.PUT_LINE('예외 발생 :'|| SQLERRM);
END;

-- 발송 완료 처리 프로시저(미완)
CREATE OR REPLACE PROCEDURE PRC_DELIVERY_COMPLETE
(
V_USER_ID USERS.USER_ID%TYPE
,V_PAYMENT_ID AUCTION_WINNING_PAYMENT.PAYMENT_ID%TYPE
)
AS
    NEW_ERR EXCEPTION;
BEGIN
    
    INSERT INTO DELIVERY_COMPLETED(SHIPPING_ID,PAYMENT_ID)
    VALUES(SHIPPING_SEQ.NEXTVAL,V_PAYMENT_ID);
  
    
    EXCEPTION
        WHEN NEW_ERR
        THEN RIASE_APPLICATION_ERROR(-20106,'에러내용');
        
END;


-- 구매 확정 및 거래 완료 프로시저(컴파일O,테스트X)
CREATE OR REPLACE PROCEDURE PRC_PURCHASE_CONFIRM
(
V_USER_ID USERS.USER_ID%TYPE
,V_RESULT_ID AUCTION_WINNING_RESULT.BID_RESULT_ID%TYPE
)
IS
    N_CHECK NUMBER;
    N_PAYMENT_ID AUCTION_WINNING_PAYMENT.PAYMENT_ID%TYPE;
    N_SHIPPING_ID DELIVERY_COMPLETED.SHIPPING_ID%TYPE;
    
    N_MONEY_TYPE1 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE2 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    
    N_MONEY_TYPE3 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    N_MONEY_TYPE4 MONEY_TYPE.MONEY_TYPE_ID%TYPE;
    
    N_AUCTION_ID AUCTION_REGISTRATION.AUCTION_ID%TYPE;
    
    NEW_ERR EXCEPTION;
    NEW_ERR2 EXCEPTION;
BEGIN
    
    
    SELECT NVL(PAYMENT_ID,0) INTO N_PAYMENT_ID
    FROM AUCTION_WINNING_PAYMENT
    WHERE BID_RESULT_ID = V_RESULT_ID;
    
    IF(N_PAYMENT_ID = 0)
        THEN RAISE NEW_ERR;
    END IF;
    
    SELECT NVL(SHIPPING_ID,0) INTO N_SHIPPING_ID
    FROM DELIVERY_COMPLETED
    WHERE PAYMENT_ID = N_PAYMENT_ID;
    
    IF(N_SHIPPING_ID = 0)
        THEN RAISE NEW_ERR2;
    END IF;

    INSERT INTO PURCHASE_CONFIRM_HISTORY(PURCHASE_CONFIRM_ID,SHIPPING_ID)
    VALUES(PURCHASE_CONFIRM_SEQ.NEXTVAL,N_SHIPPING_ID);
    
    
    SELECT MONEY_TYPE_ID INTO N_MONEY_TYPE1
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 환급';
    
    SELECT MONEY_TYPE_ID INTO N_MONEY_TYPE2
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 환급';
    
    SELECT MONEY_TYPE_ID INTO N_MONEY_TYPE3
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '구매 보증금 납부';
    
    SELECT MONEY_TYPE_ID INTO N_MONEY_TYPE4
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '판매 보증금 납부';
    
    SELECT B.AUCTION_ID INTO N_AUCTION_ID
    FROM AUCTION_WINNING_RESULT A LEFT JOIN AUCTION_BID_PARTICIPATION B
    ON A.BID_ID = B.BID_ID
    WHERE A.BID_RESULT_ID = V_RESULT_ID;
    
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_SEQ.NEXTVAL,USER_ID,N_MONEY_TYPE1,AUCTION_ID,AMOUNT
    FROM MONEY_TRANSACTION_HISTORY
    WHERE AUCTION_ID = N_AUCTION_ID
    AND MONEY_TYPE_ID = N_MONEY_TYPE3;

    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
    SELECT MONEY_SEQ.NEXTVAL,USER_ID,N_MONEY_TYPE2,AUCTION_ID,AMOUNT
    FROM MONEY_TRANSACTION_HISTORY
    WHERE USER_ID = V_USER_ID
    AND AUCTION_ID = N_AUCTION_ID
    AND MONEY_TYPE_ID = N_MONEY_TYPE4; 
    
    INSERT INTO TRANSACTION_COMPLETED(TRANSACTION_ID,PURCHASE_CONFIRM_ID)
    VALUES(TRANSACTION_SEQ.NEXTVAL,PURCHASE_CONFIRM_SEQ.CURRVAL);
    
    COMMIT;
    
    EXCEPTION 
        WHEN NEW_ERR
        THEN ROLLBACK;
        RAISE_APPLICATION_ERROR(-20102,'입금되지않은 낙찰입니다.');
        
        WHEN NEW_ERR2
        THEN ROLLBACK;
        RAISE_APPLICATION_ERROR(-20103,'발송되지않은 낙찰입니다.');
        
END;

-- 머니 충전 프로시저(보류)
CREATE OR REPLACE PROCEDURE PRC_MONEY_CHARGE
(
V_USER_ID USERS.USER_ID%TYPE
,V_MONEY_CHARGE_METHOD_ID MONEY_CHARGE_METHOD.MONEY_CHARGE_METHOD_ID%TYPE
,V_CHARGE_AMOUNT MONEY_CHARGE_HISTORY.CHARGE_AMOUNT%TYPE
)
AS
BEGIN
    
END;

--결제 -
--판매 보증금 납부 -
--구매 보증금 납부 -
--판매 보증금 환급 +
--구매 보증금 환급 +
--결제 취소(환불)
--결제 대금 입금 - 
--보증금 몰수 (금액은 0으로 두고 이력처리)

-- 회원 잔여 머니 조회 함수(컴파일O,테스트X)
CREATE OR REPLACE FUNCTION FN_GET_USER_MONEY_BALANCE
(
V_USER_ID USERS.USER_ID%TYPE
)
RETURN NUMBER
AS
    RESULT MONEY_TRANSACTION_HISTORY.AMOUNT%TYPE;
    CHARGE_MONEY MONEY_CHARGE_HISTORY.CHARGE_AMOUNT%TYPE;
    MINUS_MONEY MONEY_TRANSACTION_HISTORY.AMOUNT%TYPE;
    PLUS_MONEY MONEY_TRANSACTION_HISTORY.AMOUNT%TYPE;
BEGIN
    RESULT := 0;
    
    SELECT NVL(SUM(CHARGE_AMOUNT),0) INTO CHARGE_MONEY
    FROM MONEY_CHARGE_HISTORY
    WHERE USER_ID = V_USER_ID;
    
    RESULT := RESULT+NUMBER(CHARGE_MONEY);
    
    SELECT NVL(SUM(A.AMOUNT),0) INTO MINUS_MONEY
    FROM MONEY_TRANSACTION_HISTORY A LEFT JOIN MONEY_TYPE B
    ON A.MONEY_TYPE_ID = B.MONEY_TYPE_ID
    WHERE A.USER_ID = V_USER_ID
    AND B.MONEY_TYPE_NAME IN ('결제','판매 보증금 납부','구매 보증금 납부'
    ,'결제 대금 입금');
    
    RESULT := RESULT-MINUS_MONEY;
    
    SELECT NVL(SUM(A.AMOUNT),0) INTO PLUS_MONEY
    FROM MONEY_TRANSACTION_HISTORY A LEFT JOIN MONEY_TYPE B
    ON A.MONEY_TYPE_ID = B.MONEY_TYPE_ID
    WHERE A.USER_ID = V_USER_ID
    AND B.MONEY_TYPE_NAME IN ('판매 보증금 환급','구매 보증금 환급');
    
    RESULT := RESULT+PLUS_MONEY;
    
    RETURN RESULT;
END;


-- 낙찰 결제 기한 확인 스케줄러(컴파일O,테스트X)
BEGIN
    DBMS_SCHEDULER.CREATE_JOB
    (
    JOB_NAME => 'SCH_AUCTION_CLOSE'
    ,JOB_TYPE => 'STORED_PROCEDURE'
    ,JOB_ACTION => 'REC_AUCTION_CLOSE'
    ,REPEAT_INTERVAL => 'FREQ=MINUTELY'
    ,ENABLED => FALSE
    );
END;

-- 낙찰 결제 기한 확인 스케줄러(프로시저)(컴파일O,테스트X)
CREATE OR REPLACE PROCEDURE REC_AUCTION_CLOSE
IS
    N_BID_FAIL_TYPE_ID BID_FAILURE_TYPE.BID_FAIL_TYPE_ID%TYPE;
    N_MONEY_TYPE_ID MONEY_TYPE.MONEY_TYPE_ID%TYPE;
BEGIN

    SELECT NVL(BID_FAIL_TYPE_ID,0) INTO N_BID_FAIL_TYPE_ID
    FROM BID_FAILURE_TYPE
    WHERE BID_FAIL_TYPE_NAME = '기한만료';
    
    IF(N_BID_FAIL_TYPE_ID = 0)
        THEN RAISE_APPLICATION_ERROR(-20105,'낙찰실패타입 테이블에 "기한만료" 코드명이 존재하지 않습니다');
    END IF;

    INSERT INTO BID_FAILURE_HISTORY(BID_FAIL_HISTORY_ID,BID_RESULT_ID,BID_FAIL_TYPE_ID)
    SELECT BID_FAIL_HISTORY_SEQ.NEXTVAL,M.BID_RESULT_ID,N_BID_FAIL_TYPE_ID
    FROM
        (
            SELECT A.BID_RESULT_ID
            ,CASE 
             WHEN A.CREATED_AT IS NULL THEN '오류'
             WHEN A.CREATED_AT+1 >= SYSDATE THEN '안전'
             WHEN A.CREATED_AT+1 < SYSDATE THEN '마감'
             ELSE '오류'
             END AS CREATED_AT
            FROM AUCTION_WINNING_RESULT A LEFT JOIN AUCTION_WINNING_PAYMENT B
            ON A.BID_RESULT_ID = B.BID_RESULT_ID
            LEFT JOIN BID_FAILURE_HISTORY C
            ON A.BID_RESULT_ID = C.BID_RESULT_ID
            WHERE B.BID_RESULT_ID IS NULL AND C.BID_RESULT_ID IS NULL
        )M
    WHERE M.CREATED_AT = '마감';
    
    SELECT NVL(MONEY_TYPE_ID,0) INTO N_MONEY_TYPE_ID
    FROM MONEY_TYPE
    WHERE MONEY_TYPE_NAME = '보증금 몰수';
    
    IF(N_MONEY_TYPE_ID = 0)
        THEN RAISE_APPLICATION_ERROR(-20106,'머니 분류 테이블에 "보증금 몰수" 코드명이 존재하지 않습니다');
    END IF;
    
    INSERT INTO MONEY_TRANSACTION_HISTORY(MONEY_ID,USER_ID,MONEY_TYPE_ID
    ,AUCTION_ID,AMOUNT)
     SELECT MONEY_SEQ.NEXTVAL,C.USER_ID,N_MONEY_TYPE_ID,C.AUCTION_ID,0
     FROM BID_FAILURE_HISTORY A INNER JOIN AUCTION_WINNING_RESULT B
     ON A.BID_RESULT_ID = B.BID_RESULT_ID
     INNER JOIN AUCTION_BID_PARTICIPATION C
     ON B.BID_ID = C.BID_ID
     LEFT JOIN MONEY_TRANSACTION_HISTORY D
     ON C.AUCTION_ID = D.AUCTION_ID AND C.USER_ID = D.USER_ID
     AND D.MONEY_TYPE_ID = N_MONEY_TYPE_ID
     WHERE D.MONEY_ID IS NULL;
     
    COMMIT;
    
    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN RAISE_APPLICATION_ERROR(-20105,'낙찰실패타입 테이블에 "기한만료" 코드명이 존재하지 않습니다');
    
END;

-- 구매 확정 자동 처리 스케줄러(컴파일O,테스트X)
BEGIN
    DBMS_SCHEDULER.CREATE_JOB
    (
        JOB_NAME => 'SCH_AUTO_PURCHASE_CONFIRM'
        ,JOB_TYPE => 'STORED_PROCEDURE'
        ,JOB_ACTION => 'PRC_AUTO_PURCHASE_CONFIRM'
        ,REPEAT_INTERVAL => 'FREQ=MINUTELY'
        ,ENABLED => FALSE
    );
END;

-- 구매 확정 자동 처리 스케줄러(프로시저)(컴파일O,테스트X)
CREATE OR REPLACE PROCEDURE PRC_AUTO_PURCHASE_CONFIRM
IS
BEGIN

    INSERT INTO PURCHASE_CONFIRM_HISTORY(PURCHASE_CONFIRM_ID,SHIPPING_ID)
    SELECT PURCHASE_CONFIRM_SEQ.NEXTVAL,M.SHIPPING_ID
    FROM
        (
            SELECT A.SHIPPING_ID
            FROM DELIVERY_COMPLETED A LEFT JOIN PURCHASE_CONFIRM_HISTORY B
            ON A.SHIPPING_ID = B.SHIPPING_ID
            WHERE B.SHIPPING_ID IS NULL
            AND A.CREATED_AT+3 < SYSDATE
        )M
    
    SELECT
    FROM PURCHASE_CONFIRM_HISTORY A LEFT JOIN TRANSACTION_COMPLETED B
    ON A.SHIPPING_ID = B.SHIPPING_ID
    WHERE B
    
    COMMIT;
END;

-- 탈퇴 회원 정리 스케줄러
BEGIN
    DBMS_SCHEDULER.CREATE_JOB
    (
        JOB_NAME => 'SCH_DELETED_USER_CLEANUP'
        ,JOB_TYPE => 'STORED_PROCEDURE'
        ,JOB_ACTION => 'PRC_DELETED_USER_CLEANUP' 
        ,REPEAT_INTERVAL => 'FREQ=DAILY; BYHOUR=0'
        ,ENABLED => FALSE
    );
END;


-- 탈퇴 회원 정리 스케줄러(프로시저)
CREATE OR REPLACE PROCEDURE PRC_DELETED_USER_CLEANUP
IS
    N_ACCOUNT_EVENT_TYPE_ID ACCOUNT_EVENT_TYPE.ACCOUNT_EVENT_TYPE_ID%TYPE;
BEGIN
    SELECT NVL(ACCOUNT_EVENT_TYPE_ID,0) INTO N_ACCOUNT_EVENT_TYPE_ID
    FROM ACCOUNT_EVENT_TYPE
    WHERE EVENT_NAME = '탈퇴';

    IF(N_ACCOUNT_EVENT_TYPE_ID = 0)
        THEN RAISE_APPLICATION_ERROR(-20106,'계정 이벤트 분류 코드명에 "탈퇴"인 이벤트명이없습니다');
    END IF;
    
    DELETE 
    FROM DELETED_USER A
    WHERE EXISTS
    (SELECT 1
    FROM ACCOUNT_EVENT_HISTORY B
    WHERE A.USER_ID = B.USER_ID
    AND B.ACCOUNT_EVENT_TYPE_ID = N_ACCOUNT_EVENT_TYPE_ID
    AND ADD_MONTHS(B.CREATED_AT,3) > SYSDATE  
    );
    
    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN RAISE_APPLICATION_ERROR(-20106,'계정 이벤트 분류 코드명에 "탈퇴"인 이벤트명이 비어있습니다');
END;


